### ISSUE TITLE
Concurrent user creation issues

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10078]
Triggering batch user creations (from the Enterprise API at least) fails for some users.

**Related traces**

Main issue: an script is too fast (and big) got route64 limits:

```
[ALERT] USER 'BARUCH29' SETUP FAILED (SERVER ID: 239371)
Exception: Fog::DNS::AWS::Error
Throttling => Rate exceeded

Server attributes:
#<Server id: 239371, user_id: 247569, subdomain: "baruch29", ip_address: "useb.ep.carto.com", port: 443, state: "creating_user", server_type: "dedicated", remote_user_id: "d68e20a6-874b-4e26-8b19-3898acca8faa", created_at: "2016-10-07 00:12:59", updated_at: "2016-10-07 00:13:20", setup_failed_at: "2016-10-07 00:13:20", database_host: "10.0.254.184">

/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/excon-0.49.0/lib/excon/middlewares/expects.rb:6:in `response_call'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/excon-0.49.0/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/excon-0.49.0/lib/excon/connection.rb:389:in `response'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/excon-0.49.0/lib/excon/connection.rb:253:in `request'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/excon-0.49.0/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:10:in `error_call'
```

[Trace](https://rollbar.com/vizzuality/CartoDB/items/20456/?item_page=0&item_count=100&#traceback):

``` ruby
PG::Error: ERROR: tuple concurrently updated

+ 18 non-project frames
19
File "/home/ubuntu/www/production.cartodb.com/releases/20160928141817/app/models/user/db_service.rb", line 925 in add_python
20
File "/home/ubuntu/www/production.cartodb.com/releases/20160928141817/app/models/user/db_service.rb", line 179 in load_cartodb_functions
21
File "/home/ubuntu/www/production.cartodb.com/releases/20160928141817/app/models/user/db_service.rb", line 1011 in create_own_schema
22
File "/home/ubuntu/www/production.cartodb.com/releases/20160928141817/app/models/user/db_service.rb", line 118 in new_organization_user_main_db_setup
23
File "/home/ubuntu/www/production.cartodb.com/releases/20160928141817/app/models/user.rb", line 1404 in setup_user
24
File "/home/ubuntu/www/production.cartodb.com/releases/20160928141817/app/models/user.rb", line 248 in after_create
+ 17 non-project frames
42
File "/home/ubuntu/www/production.cartodb.com/releases/20160928141817/app/models/carto/user_creation.rb", line 238 in save_user
+ 51 non-project frames
94
File "/home/ubuntu/www/production.cartodb.com/releases/20160928141817/lib/resque/user_jobs.rb", line 54 in perform
+ 26 non-project frames
```

[Trace](https://rollbar.com/vizzuality/CartoDB/items/20264/occurrences/17400797183/):

``` ruby
PG::Error: ERROR: duplicate key value violates unique constraint "pg_proc_proname_args_nsp_index"
DETAIL: Key (proname, proargtypes, pronamespace)=(_cdb_userquotainbytes, , 2200) already exists.
CONTEXT: SQL statement "CREATE OR REPLACE FUNCTION "public"._CDB_UserQuotaInBytes() RETURNS int8 AS $X$ SELECT 524288000::int8 $X$ LANGUAGE sql IMMUTABLE"
PL/pgSQL function cdb_setuserquotainbytes(text,bigint) line 12 at EXECUTE

+ 18 non-project frames
19
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user/db_service.rb", line 228 in block in rebuild_quota_trigger_with_database
+ 6 non-project frames
26
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user/db_service.rb", line 218 in rebuild_quota_trigger_with_database
27
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user/db_service.rb", line 209 in block in rebuild_quota_trigger
28
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user.rb", line 616 in in_database
29
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user/db_service.rb", line 208 in rebuild_quota_trigger
30
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user/db_service.rb", line 204 in load_cartodb_functions
31
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user/db_service.rb", line 1023 in create_own_schema
32
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user/db_service.rb", line 118 in new_organization_user_main_db_setup
33
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user.rb", line 1404 in setup_user
34
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/user.rb", line 248 in after_create
+ 17 non-project frames
52
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/app/models/carto/user_creation.rb", line 238 in save_user
+ 51 non-project frames
104
File "/home/ubuntu/www/production.cartodb.com/releases/20161006160014/lib/resque/user_jobs.rb", line 54 in perform
```

[Trace](https://rollbar.com/vizzuality/CartoDB/items/11928/?item_page=0&item_count=100&#instances):

``` ruby
    #<Sequel::DatabaseError: PG::Error: ERROR: duplicate key value violates unique constraint "cdb_conf_pkey"
DETAIL: Key (key)=(geocoder_server_config) already exists.
CONTEXT: SQL statement "INSERT INTO cartodb.CDB_CONF (KEY, VALUE) VALUES ($1, $2);"
PL/pgSQL function cdb_conf_setconf(text,json) line 4 at EXECUTE
```

Consider using [resque-throttle](https://github.com/scotttam/resque-throttle), at least for Route64 rate limit.

Related: CartoDB/cartodb/issues/9791

cc @CartoDB/builder-backend @xavijam @jsanz

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
