### ISSUE TITLE
Some dashboards work ok within the Builder, but not in the embed

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#10591]
### Context
Spontaneous change in behavior. Without any edition of the dashboard, both of the dashboards above stopped working in the embeds, but they are oke within the Builder.

### Steps to Reproduce
No human interaction 

### Current Result
The dashboard works OK within the builder, but not the embed

### Expected result
Plain common embed behavior

### Browser and version
Any 

### Links
First example was
https://team.carto.com/u/abel/builder/c5374a22-08d8-11e6-8d25-0ecd1babdde5/embed

Console errors:
```
Error: Map instantiation failed
    at Object.error (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/common_editor3.js:9:21150)
    at Object.error (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/common_editor3.js:32:31859)
    at N.d.<anonymous> (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/common_editor3.js:33:21778)
    at Object.success (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/common_editor3.js:33:13811)
    at k (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:45:2603)
    at Object.fireWith [as resolveWith] (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:45:3415)
    at c (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:46:8151)
    at HTMLScriptElement.c (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:46:14711)
    at HTMLScriptElement.dispatch (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:45:13611)
    at HTMLScriptElement.q.handle (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:45:10386)

tracker.js:10 Dashboard has some errors: Error: Map instantiation failed(…)a.(anonymous function) @ tracker.js:10`
```

Newest one is 
https://team.carto.com/u/abel/builder/24b7a3e6-ecf2-11e5-90a4-0e674067d321/embed

Console errors:

```
Error: Map instantiation failed
    at Object.error (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/common_editor3.js:9:21150)
    at Object.error (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/common_editor3.js:32:31859)
    at N.d.<anonymous> (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/common_editor3.js:33:21778)
    at Object.success (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/common_editor3.js:33:13811)
    at k (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:45:2603)
    at Object.fireWith [as resolveWith] (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:45:3415)
    at c (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:46:8151)
    at HTMLScriptElement.c (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:46:14711)
    at HTMLScriptElement.dispatch (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:45:13611)
    at HTMLScriptElement.q.handle (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.4.10/javascripts/vendor_editor3.js:45:10386)

tracker.js:10 Dashboard has some errors: Error: Map instantiation failed(…)a.(anonymous function) @ tracker.js:10
```

### Additional info (2nd dashboard)
```
["Dataview "3057b090-3261-4a7c-bfbe-2bb5863f79b4" is missing `source.id` attribute",…]
0
:
"Dataview "3057b090-3261-4a7c-bfbe-2bb5863f79b4" is missing `source.id` attribute"
1
:
"Dataview "b7ec20ab-cdc6-48b1-a299-d89bd9a60afb" is missing `source.id` attribute"
2
:
"Dataview "4e7bb5ff-97ec-409f-97f3-5dc7822adce0" is missing `source.id` attribute"
3
:
"Dataview "ab2a0fea-6c40-49b7-9551-b82048b1e013" is missing `source.id` attribute"
4
:
"Dataview "c8a22613-c9a3-4236-99e2-7d19989c1e6b" is missing `source.id` attribute"
5
:
"Dataview "b566f54c-1b5d-49aa-8050-5792f0b11398" is missing `source.id` attribute"
```

cc @xavijam

**Comment by gfiorav** [comment]
The widgets (dataviews) in these maps are an old, unsupported version that don't use `source_id` pointers (and hence can't be pointed to anything but the latest analysis in a layer).

There are a few early maps that are affected and will be fixed manually! Thanks for reporting.

**Comment by michellechandra** [comment]
Perhaps related, or maybe unrelated? Paul Ramsey (pramsey account) is experiencing a similar issue with a map he created in the Builder. The map renders fine in his Builder UI but the widgets don't work in the embed version.

URL to map: https://pramsey.carto.com/builder/95fa5248-a533-11e6-b8f0-0e3ff518bd15/embed
Dataset in pramsey account is called "donors." Please note, this dataset contains private info and needs to stay private.

### Screenshot of Console Error:
![screen shot 2016-11-07 at 14 02 21](https://cloud.githubusercontent.com/assets/5423288/20078687/78299e96-a4f6-11e6-9f32-a66a9b6afa6f.png)

### Error is:
"Cannot read property 'start' of undefined

cc @pramsey

**Comment by javitonino** [comment]
@michellechandra I checked and that map seems to have a different issue, not related to this one. For me, one of the widgets works, but not he other. Anyway, can you report as a separate issue?
