### ISSUE TITLE
cannot import table with "date" as column name

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#11455]
Tried to import following CSV file from openpaths.cc service, failed with 99999 error

```
lat,lon,alt,date,device,os,version
37.7679824829,-122.392570496,14,2013-06-08 21:28:32,"iPhone5,2",6.1.4,1.1
```

 
### Additional info
Checked from log details - ogr2ogr does not give errors, but the result table is not created (import id 83bd6a0d-b112-47b8-944b-c9d9c638f310) . When I renamed field **date** to **data_date**, then import was ok. So probably the error is because **"date"** is reserved SQL keyword which cannot be used as field name in postgres.

**Comment by saleiva** [comment]
this should be for engine I believe cc/ @rafatower

**Comment by rafatower** [comment]
Here's an excerpt from the logs:
```
2017-02-05 14:23:14 UTC: ogr2ogr exit code:       0
2017-02-05 14:23:14 UTC: Georeferencing...
2017-02-05 14:23:14 UTC: Disabling autovacuum for "cdb_importer"."importer_a0da2424ebae11e6a0d30e3a376473ab"
2017-02-05 14:23:14 UTC: Creating the_geom from wkb_geometry column
2017-02-05 14:23:14 UTC: replace empty strings by nulls?
2017-02-05 14:23:14 UTC: no string column found, nothing replaced
2017-02-05 14:23:14 UTC: geometrifying
2017-02-05 14:23:14 UTC: casting wkb_geometry to geometry
2017-02-05 14:23:14 UTC: Converting to 2D point
2017-02-05 14:23:14 UTC: geometrified
2017-02-05 14:23:14 UTC: Renaming column wkb_geometry TO the_geom
2017-02-05 14:23:14 UTC: Enabling autovacuum for "cdb_importer"."importer_a0da2424ebae11e6a0d30e3a376473ab"
2017-02-05 14:23:14 UTC: Georeferenced
2017-02-05 14:23:14 UTC: Finished importing data from /tmp/imports/20170205-3971-7jmz14/openpaths_jaaguar.csv
2017-02-05 14:23:14 UTC: Proceeding to register
2017-02-05 14:23:14 UTC: Before renaming from importer_a0da2424ebae11e6a0d30e3a376473ab to openpaths_jaaguar
2017-02-05 14:23:14 UTC: Before moving schema 'openpaths_jaaguar' from cdb_importer to jaakl
2017-02-05 14:23:14 UTC: Before persisting metadata 'openpaths_jaaguar' data_import_id: 83bd6a0d-b112-47b8-944b-c9d9c638f310
2017-02-05 14:23:15 UTC: Exception: PG::Error: ERROR:  table "openpaths_jaaguar" does not exist
```

So ogr2ogr seems to work ok, then fail at some later point.

Here's the stacktrace:
```
lib/importer/lib/cartodb-migrator/migrator.rb:102:in `rescue in migrate!'
lib/importer/lib/cartodb-migrator/migrator.rb:107:in `migrate!'
app/models/table.rb:294:in `import_to_cartodb'
app/models/table.rb:391:in `before_create'
app/models/table/user_table.rb:190:in `before_create'
app/models/table.rb:89:in `save'
app/models/table_registrar.rb:18:in `register'
app/connectors/importer.rb:231:in `persist_metadata'
app/connectors/importer.rb:80:in `register'
app/connectors/importer.rb:54:in `block in run'
app/connectors/importer.rb:53:in `each'
app/connectors/importer.rb:53:in `run'
app/models/data_import.rb:734:in `execute_importer'
app/models/data_import.rb:420:in `dispatch'
app/models/data_import.rb:187:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

and here's the line where it fails (trying to rescue from an exception btw): https://github.com/CartoDB/cartodb/blob/862f293b2857ee6c0435b574747e1c55a0f89c90/lib/importer/lib/cartodb-migrator/migrator.rb#L102

I tried to reproduce the issue with the csv provided but I couldn't:
https://team.carto.com/u/rtorre/dataset/test_date

So I'd look for another explanation.

**Comment by rafatower** [comment]
This is the original exception from resque logs:
```
PG::Error: ERROR:  relation "openpaths_jaaguar" does not exist
LINE 1: SELECT count(*) as count from openpaths_jaaguar

lib/importer/lib/cartodb-migrator/migrator.rb:84:in `migrate!'
app/models/table.rb:294:in `import_to_cartodb'
app/models/table.rb:391:in `before_create'
app/models/table/user_table.rb:190:in `before_create'
app/models/table.rb:89:in `save'
app/models/table_registrar.rb:18:in `register'
app/connectors/importer.rb:231:in `persist_metadata'
app/connectors/importer.rb:80:in `register'
app/connectors/importer.rb:54:in `block in run'
app/connectors/importer.rb:53:in `each'
app/connectors/importer.rb:53:in `run'
app/models/data_import.rb:734:in `execute_importer'
app/models/data_import.rb:420:in `dispatch'
app/models/data_import.rb:187:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

https://github.com/CartoDB/cartodb/blob/862f293b2857ee6c0435b574747e1c55a0f89c90/lib/importer/lib/cartodb-migrator/migrator.rb#L84

As there's no other error and at that point the table was already imported and renamed I can only think of two possible explanations:
- the table was deleted trhough sql api, or
- a race condition in ghost tables

**Comment by rafatower** [comment]
I cannot find any more evidence to support any of the hypotheses, nor reproduce the issue. Can you reproduce it, @jaakla ?

**Comment by jaakla** [comment]
Right, now upload of the same table was ok, so my theory was wrong and *date* as column name is ok. So cannot repro it myself.

**Comment by rafatower** [comment]
I'm closing this as non-reproducible, but let's reopen if it happens again and continue the investigation from there.
