### ISSUE TITLE
Basemap selector doesn't work in Builder, but does in Editor 

### ISSUE THREAD

**Issue by Prindle19** [CartoDB/cartodb#11747]
### Context
Clicking on the basemap selector for a map when using Builder results in a blank pane. The console shows the error: 

editor3.js:39 Uncaught Error: Can't create basemapModel for basemap of type: Nokia
    at D.createBasemapModel (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/editor3.js:39:5469)
    at N.d.<anonymous> (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/editor3.js:37:28266)
    at https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/vendor_editor3.js:66:3517
    at Function.u.map.u.collect (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/vendor_editor3.js:66:4576)
    at N.d.<anonymous> (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/editor3.js:37:28220)
    at https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/vendor_editor3.js:66:3517
    at Function.u.each.u.forEach (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/vendor_editor3.js:66:4420)
    at u.(anonymous function) [as each] (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/vendor_editor3.js:66:17545)
    at N.d._initCollections (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/editor3.js:37:28199)
    at N.d.initialize (https://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/4.6.25/javascripts/editor3.js:37:28080)
 
However, if I disable Builder for the same user and default back to Editor, the basemap selector works as expected.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1.  Build CartoDB docker image from https://github.com/chriswhong/docker-cartodb
2.  Try to create a map and change the basemap in Builder.

### Current Result
Console error and blank basemap selector.

### Expected result
Working basemap selector.

### Browser and version
Version 57.0.2987.88 beta (64-bit)

**Comment by xavijam** [comment]
Hi @Prindle19, sorry but we don't provide support for custom installations, I encourage you to ask in our [google group](https://groups.google.com/forum/#!forum/cartodb) in case someone has faced the same problem using that installation.
