### ISSUE TITLE
Privacy change of table with no map error

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12137]
STR:

1. Create a new user.
2. Create a new map importing nyc_subway_entrance Data Library dataset.

You get this trace in the console:

```
debug: Privacy change of table with no map
#<NoMethodError: undefined method `save' for nil:NilClass>
/Users/juanignaciosl/Development/carto/cartodb/app/models/table/privacy_manager.rb:14:in `apply_privacy_change'
/Users/juanignaciosl/Development/carto/cartodb/app/models/table.rb:449:in `after_save'
/Users/juanignaciosl/Development/carto/cartodb/app/models/carto/user_table.rb:54:in `block in <class:UserTable>'
```

Nevertheless, table is imported and map is created.

Please do some research about what's happening. That error shouldn't appear, and the permission of the imported table should be right: it should be private if the user has private tables, public otherwise.

cc @CartoDB/builder-backend

**Comment by juanignaciosl** [comment]
Full trace:


```
  Sequel::Postgres::Database (0.7ms)  INSERT INTO "tags" ("name", "user_id", "table_id") VALUES ('Cultural datasets', '8282e54e-457a-468a-9ab4-ea6767c9628b', 'fdfc7c5c-872c-40c9-8c3f-e198b23aa823') RETURNING *
  Sequel::Postgres::Database (0.4ms)  COMMIT
debug: Privacy change of table with no map
#<NoMethodError: undefined method `save' for nil:NilClass>
/Users/juanignaciosl/Development/carto/cartodb/app/models/table/privacy_manager.rb:14:in `apply_privacy_change'
/Users/juanignaciosl/Development/carto/cartodb/app/models/table.rb:449:in `after_save'
/Users/juanignaciosl/Development/carto/cartodb/app/models/carto/user_table.rb:54:in `block in <class:UserTable>'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:449:in `_run__4457769665746640759__save__701720496523676779__callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/callbacks.rb:264:in `create_or_update'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/persistence.rb:84:in `save'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/validations.rb:50:in `save'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/attribute_methods/dirty.rb:22:in `save'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:208:in `transaction'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:259:in `block in save'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:258:in `save'
/Users/juanignaciosl/Development/carto/cartodb/app/models/table.rb:423:in `after_create'
/Users/juanignaciosl/Development/carto/cartodb/app/models/carto/user_table.rb:53:in `block in <class:UserTable>'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:439:in `_run__4457769665746640759__create__701720496523676779__callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/callbacks.rb:268:in `create'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/persistence.rb:348:in `create_or_update'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/callbacks.rb:264:in `block in create_or_update'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:447:in `_run__4457769665746640759__save__701720496523676779__callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `__run_callback'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/callbacks.rb:264:in `create_or_update'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/persistence.rb:104:in `save!'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/validations.rb:56:in `save!'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:264:in `block in save!'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:208:in `transaction'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/activerecord-3.2.22/lib/active_record/transactions.rb:264:in `save!'
/Users/juanignaciosl/Development/carto/cartodb/app/models/table.rb:96:in `save'
/Users/juanignaciosl/Development/carto/cartodb/app/models/table_registrar.rb:18:in `register'
/Users/juanignaciosl/Development/carto/cartodb/app/connectors/importer.rb:232:in `persist_metadata'
/Users/juanignaciosl/Development/carto/cartodb/app/connectors/importer.rb:81:in `register'
/Users/juanignaciosl/Development/carto/cartodb/app/connectors/importer.rb:55:in `block in run'
/Users/juanignaciosl/Development/carto/cartodb/app/connectors/importer.rb:54:in `each'
/Users/juanignaciosl/Development/carto/cartodb/app/connectors/importer.rb:54:in `run'
/Users/juanignaciosl/Development/carto/cartodb/app/models/data_import.rb:745:in `execute_importer'
/Users/juanignaciosl/Development/carto/cartodb/app/models/data_import.rb:428:in `dispatch'
/Users/juanignaciosl/Development/carto/cartodb/app/models/data_import.rb:189:in `run_import!'
/Users/juanignaciosl/Development/carto/cartodb/lib/resque/importer_jobs.rb:9:in `block in perform'
/Users/juanignaciosl/Development/carto/cartodb/lib/resque/base_job.rb:21:in `call'
/Users/juanignaciosl/Development/carto/cartodb/lib/resque/base_job.rb:21:in `run_action'
/Users/juanignaciosl/Development/carto/cartodb/lib/resque/importer_jobs.rb:9:in `perform'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/juanignaciosl/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/bin/rake:22:in `load'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/bin/rake:22:in `<main>'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/juanignaciosl/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
user: #<Sequel::Postgres::Dataset: "SELECT * FROM \"users\" WHERE (\"id\" = '8282e54e-457a-468a-9ab4-ea6767c9628b')">
table_id: fdfc7c5c-872c-40c9-8c3f-e198b23aa823
table_name: nyc_subway_entrance
data_import_id: 36a42dd2-f353-429b-bd1e-75adeae3aec9
```

It appears at resque console.

@mayoral could you confirm that *resque* console doesn't display this, please? If it doesn't, I'll debug this, because it's likely to be related to my environment. Thanks!

**Comment by mayoral** [comment]
You're right, @juanignaciosl. I can see the trace on the resque console. Investigating...

**Comment by juanignaciosl** [comment]
That investigation should be interesting for you because you'll get to know a little bit about the importer and details about the models, both static (visualization <-> map relationships) and dynamic (visualization types).
