### ISSUE TITLE
Any kind of authentication throws 500 errors if a organization uses LDAP auth and LDAP server is down

### ISSUE THREAD

**Issue by jvillarf** [CartoDB/cartodb#12148]
## Description

**Related ticket:** https://github.com/CartoDB/onpremises/issues/342
**Onpremise version**: builder-2.1.0-pre3

### Scenario

Organization1: Using local authentication
Organization2: Using LDAP authentication

Everything works fine, but as soon as we bring **LDAP Server down**, no matter if you use **local**, or any other kind of authentication, a **500 Internal server error** is shown.

**Error**
```` bash
Started POST "/sessions/create" for 127.0.0.1 at 2017-05-16 17:59:40 +0000
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"hooJrEQNnI5Ab9MN0I+KAExFNTVr25lP2Bf15aJtUQQ=", "google_access_token"=>"", "google_access_filled"=>"0", "email"=>"admin-saml", "password"=>"[FILTERED]"}
Completed 500 Internal Server Error in 3005.3ms

Net::LDAP::Error (Host ldap.localhost.lan was unreachable (No route to host - connect(2) for "ldap.localhost.lan" port 389)):
  app/models/carto/ldap/configuration.rb:78:in `block in authenticate'
  app/models/carto/ldap/configuration.rb:77:in `each'
  app/models/carto/ldap/configuration.rb:77:in `find'
  app/models/carto/ldap/configuration.rb:77:in `authenticate'
  app/models/carto/ldap/manager.rb:18:in `block in authenticate'
  app/models/carto/ldap/manager.rb:17:in `each'
  app/models/carto/ldap/manager.rb:17:in `authenticate'
  config/initializers/warden.rb:150:in `authenticate!'
  app/controllers/sessions_controller.rb:60:in `create'
  app/controllers/application_controller.rb:101:in `wrap_in_profiler'
````

```` bash

Started POST "/sessions/create" for 83.53.244.247 at 2017-05-17 16:36:29 +0000
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"IP+yunOv1RaRjdawgZh1t3DYSmYUSHx+P7p5HkusC0k=", "google_access_token"=>"", "google_access_filled"=>"0", "email"=>"carto", "password"=>"[FILTERED]"}
Completed 500 Internal Server Error in 6.2ms

Net::LDAP::Error (Server 139.59.156.247 refused connection on port 389.):
  app/models/carto/ldap/configuration.rb:78:in `block in authenticate'
  app/models/carto/ldap/configuration.rb:77:in `each'
  app/models/carto/ldap/configuration.rb:77:in `find'
  app/models/carto/ldap/configuration.rb:77:in `authenticate'
  app/models/carto/ldap/manager.rb:18:in `block in authenticate'
  app/models/carto/ldap/manager.rb:17:in `each'
  app/models/carto/ldap/manager.rb:17:in `authenticate'
  config/initializers/warden.rb:150:in `authenticate!'
  app/controllers/sessions_controller.rb:60:in `create'
  app/controllers/application_controller.rb:101:in `wrap_in_profiler'
````

### Expected result

- Organization users using any kind of authentication, but **LDAP**, should be able to login.
- Organization users using LDAP authentication, shouldn't be able to login. If possible, we might want to show a **login error**, instead of a **500 Internal Server** one.

![test2](https://cloud.githubusercontent.com/assets/15977491/26165315/c9d22888-3b2f-11e7-98c4-0caeffdf5ae9.png)

#SMOKES_OAUTH01

**Comment by juanignaciosl** [comment]
Prioritized, as it's relevant for next release. Please write down deadline needs, if any 🤗

**Comment by jvillarf** [comment]
@juanignaciosl onpremises **2.1.0** version was meant to be released by the end of May. Since this is a blocking issue, it would be great if it can be done by the beginning of the next week. Thanks.
