### ISSUE TITLE
Failing UserMigration tests

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12956]
Master CI. [Error trace](https://ci.cartodb.net/job/CartoDB-master-testing/1067/console).

```
16:46:40   1) UserMigration failing organization organizations should rollback import failing in JobImport#run!
16:46:40      Failure/Error: org_import.run_import.should eq true
16:46:40        
16:46:40        expected: true
16:46:40             got: false
16:46:40        
16:46:40        (compared using ==)
16:46:40      # ./spec/models/carto/user_migration_spec.rb:218:in `block (3 levels) in <top (required)>'
16:46:40 
16:46:40   2) UserMigration failing organization organizations should rollback import failing creating user database and roles
16:46:40      Failure/Error: org_import.run_import.should eq true
16:46:40        
16:46:40        expected: true
16:46:40             got: false
16:46:40        
16:46:40        (compared using ==)
16:46:40      # ./spec/models/carto/user_migration_spec.rb:230:in `block (3 levels) in <top (required)>'
16:46:40 
16:46:40   3) UserMigration failing organization organizations should rollback import failing importing visualizations
16:46:40      Failure/Error: org_import.run_import.should eq true
16:46:40        
16:46:40        expected: true
16:46:40             got: false
16:46:40        
16:46:40        (compared using ==)
16:46:40      # ./spec/models/carto/user_migration_spec.rb:242:in `block (3 levels) in <top (required)>'
16:46:40 
16:46:40   4) UserMigration failing organization organizations should rollback should fail if importing an already existing organization with metadata
16:46:40      Failure/Error: org_import.run_import.should eq true
16:46:40        
16:46:40        expected: true
16:46:40             got: false
16:46:40        
16:46:40        (compared using ==)
16:46:40      # ./spec/models/carto/user_migration_spec.rb:246:in `block (3 levels) in <top (required)>'
```

It's likely to be a random error, but it'd be nice to fix it if possible.

**Comment by javitonino** [comment]
Linking with https://github.com/CartoDB/cartodb/pull/12959, I did not realise there was an issue.
