### ISSUE TITLE
CartoDB - Install CartoDB SQL API- npm install failure

### ISSUE THREAD

**Issue by nilesh-phadtare** [CartoDB/cartodb#1343]
Hi All ,
     I am configuring CartoDb on Ubuntu 12.04  .   I have gone through all the steps mentioned on https://github.com/CartoDB/cartodb .
At Install CartoDB SQL API step , sollowing strps work normally. 
1. git clone git://github.com/CartoDB/CartoDB-SQL-API.git
2. cd CartoDB-SQL-API
3. git checkout master 

But next step which is npm install gives an error . Error log is given below.

npm http GET https://registry.npmjs.org/libxmljs
npm http 304 https://registry.npmjs.org/libxmljs
npm http GET https://registry.npmjs.org/embedly/0.3.2
npm http 404 https://registry.npmjs.org/embedly/0.3.2
npm ERR! unpack Could not read data for embedly@0.3.2
npm ERR! Error: version not found: 0.3.2 : embedly/0.3.2
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:14)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/indictrans/Documents/CartoDB-SQL-API/node_modules
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/indictrans/Documents/CartoDB-SQL-API/node_modules/npm-debug.log
npm ERR! not ok code 0

Please help me out.

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
