### ISSUE TITLE
Sync error_code is not cleared after a successful synchronisation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#1357]
A user reported that a 9999 error was displayed in spite of successful synchronisation. CartoDB is not clearing error_code field from synchronisations table.

cc @iriberri

**Comment by iriberri** [comment]
Notify SB/4782079

**Comment by rafatower** [comment]
The root cause of the failed sync was this:
```
undefined method `[]' for nil:NilClass

services/datasources/lib/datasources/url/gdrive.rb:193:in `get_resource'
services/importer/lib/importer/datasource_downloader.rb:99:in `set_downloaded_source_file'
services/importer/lib/importer/datasource_downloader.rb:31:in `run'
services/importer/lib/importer/runner.rb:229:in `block (2 levels) in single_resource_import'
```
which in turn seems to be a `result` without `data`.

**Comment by rafatower** [comment]
How to reproduce:
- Create a sync with URL (it should be successful)
- Add this patch and restart resque to force the error:
```Diff
diff --git a/services/importer/lib/importer/downloader.rb b/services/importer/lib/importer/downloader.rb
index a7fa477..6558460 100644
--- a/services/importer/lib/importer/downloader.rb
+++ b/services/importer/lib/importer/downloader.rb
@@ -70,6 +70,7 @@ module CartoDB
       end
 
       def modified?
+        return true # force download
         previous_etag           = http_options.fetch(:etag, false)
         previous_last_modified  = http_options.fetch(:last_modified, false)
         etag                    = etag_from(headers)
@@ -153,6 +154,8 @@ module CartoDB
 
         temp_name = filepath(DEFAULT_FILENAME << '_' << random_name)
 
+        raise "force an uncontrolled exception"
+
         downloaded_file = File.open(temp_name, 'wb')
         request = Typhoeus::Request.new(@translated_url, typhoeus_options)
         request.on_headers do |response|
```
- rerun the sync, in order to do so, most likely need to hack the sync:
```Ruby
u = User.where(username: 'development').first; nil
t = Table.new(user_table: u.tables.where(name: 'elders').first); nil
s = t.synchronization
s.fetch
s.ran_at = s.ran_at - 1.month
```
- rerun the sync again
