### ISSUE TITLE
Error in Windshaft-cartodb installation  step of CartoDb

### ISSUE THREAD

**Issue by nilesh-phadtare** [CartoDB/cartodb#1378]
Hi,
 I am trying to install cartodb on  ubuntu 12.04 . I have done all the steps mentioned on https://github.com/CartoDB/cartodb and I am stuck to Install Windshaft-cartodb Step. 
Following steps worked fine -
git clone git://github.com/CartoDB/Windshaft-cartodb.git
cd Windshaft-cartodb
git checkout master
npm install
cp config/environments/development.js.example config/environments/development.js 
whenever I hit the command  node app.js development 
it gives me following error - 

module.js:340
    throw err;
    ^
Error: Cannot find module 'mapnik'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/indictrans/Documents/Windshaft-cartodb/node_modules/windshaft/lib/windshaft/server.js:8:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I installed mapnik  using sudo apt-get install libmapnik libmapnik-dev mapnik-utils python-mapnik  .
also i tried npm install mapnik .
but still problem persists . 

I have googled lot on this issue but each time gave same solution.
I have also installed TileMill to map Mapnik dependecy but it is not working.
please help me out.
Thanks in advance .

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
