### ISSUE TITLE
Tests failing due to AccounType model

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13853]
We are getting a lot of random failures like:

```
6011.log-  1) Superadmin's users API user create with password success
6011.log-     Failure/Error: account_type = FactoryGirl.create(:account_type_free)
6011.log-     ActiveRecord::RecordNotUnique:
6011.log-       PG::Error: ERROR:  duplicate key value violates unique constraint "account_types_pkey"
6011.log-       DETAIL:  Key (account_type)=(FREE) already exists.
6011.log-       : INSERT INTO "account_types" ("account_type", "created_at", "rate_limit_id", "updated_at") VALUES ('FREE', '2018-04-17 08:19:00.477985', '5319c944-bcd8-4546-87e8-aa0c48c026e2', '2018-04-17 08:19:00.477985') RETURNING "account_type"
6011.log-     # ./config/initializers/zz_patch_reconnect.rb:40:in `block in exec_query'
6011.log-     # ./config/initializers/zz_patch_reconnect.rb:62:in `block (2 levels) in wrap_execute'
6011.log-     # ./config/initializers/zz_patch_reconnect.rb:61:in `block in wrap_execute'
6011.log-     # ./config/initializers/zz_patch_reconnect.rb:68:in `with_auto_reconnect'
6011.log-     # ./config/initializers/zz_patch_reconnect.rb:60:in `wrap_execute'
6011.log-     # ./config/initializers/zz_patch_reconnect.rb:39:in `exec_query'
6011.log-     # ./spec/requests/superadmin/users_spec.rb:34:in `block (2 levels) in <top (required)>'
6011.log-     # ./zeus_plan.rb:58:in `test'
6011.log-     # -e:1:in `<main>'
```

The problem is that it tries to create account types that already exist.

@alrocar can you take a look? This makes some PRs to randomly fail to test, even when they are ok.

**Comment by alrocar** [comment]
I'm priorizing this.

I think I'm just gonna replace the calls to `FactoryGirl` by a helper method we have in place that checks account_type existence before create a new one.
