### ISSUE TITLE
Warning in .carto imports

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14297]
```
WARNING: Can't mass-assign protected attributes for Carto::UserTable: name
        app/models/table.rb:93:in `update'
        app/models/carto/visualization.rb:660:in `propagate_name'
        app/models/carto/visualization.rb:641:in `propagate_privacy_and_name_to'
        app/models/carto/visualization.rb:558:in `store'
        app/models/carto/visualization.rb:554:in `store_using_table'
        app/models/table/privacy_manager.rb:78:in `block in propagate_to'
        app/models/table/privacy_manager.rb:74:in `each'
        app/models/table/privacy_manager.rb:74:in `propagate_to'
        app/models/table/privacy_manager.rb:27:in `block in apply_privacy_change'
        app/models/table/privacy_manager.rb:134:in `revertable_privacy_change'
        app/models/table/privacy_manager.rb:26:in `apply_privacy_change'
        app/models/table.rb:408:in `after_save'
        app/models/carto/user_table.rb:275:in `service_after_save'
        app/models/carto/map.rb:177:in `save_table'
        app/services/carto/visualizations_export_persistence_service.rb:67:in `block in save_import'
        app/services/carto/visualizations_export_persistence_service.rb:17:in `save_import'
        app/services/carto/user_metadata_export_service.rb:417:in `block (2 levels) in import_user_visualizations_from_directory'
        app/services/carto/user_metadata_export_service.rb:415:in `each'
        app/services/carto/user_metadata_export_service.rb:415:in `block in import_user_visualizations_from_directory'
        app/services/carto/user_metadata_export_service.rb:481:in `with_non_viewer_user'
        app/services/carto/user_metadata_export_service.rb:414:in `import_user_visualizations_from_directory'
        app/services/carto/organization_metadata_export_service.rb:276:in `block in import_metadata_from_directory'
        app/services/carto/organization_metadata_export_service.rb:271:in `import_metadata_from_directory'
        app/models/carto/user_migration_import.rb:154:in `block in import_visualizations'
        app/models/carto/user_migration_import.rb:153:in `import_visualizations'
        app/models/carto/user_migration_import.rb:96:in `import'
        app/models/carto/user_migration_import.rb:44:in `run_import'
```

**Comment by javitonino** [comment]
@alrocar Stalebot reminded me of this. I don't think it's very important, but it may be masking some errors in the Sequel vs Carto models. Anyway, just FYI. I'm out!

**Comment by gonzaloriestra** [comment]
ClubHouse issue: https://app.clubhouse.io/cartoteam/story/83464/warning-in-carto-imports
