### ISSUE TITLE
Can't export visualizations using rake

### ISSUE THREAD

**Issue by chrowe** [CartoDB/cartodb#14584]
### Context
Trying to export a visualization on the command line using rake

### Steps to Reproduce
1. Navigate to `cartodb` dir
2. Run `./script/export.sh [visualizations id]
```
#!/bin/bash

export RAILS_ENV=production

MAPID=$1
echo $MAPID

bundle exec rake --trace cartodb:vizs:export_user_visualization_json[$MAPID] > $MAPID.json
```
based on https://cartodb.readthedocs.io/en/latest/operations/exporting_importing_visualizations.html?highlight=export

### Current Result
```
./export.sh 8caad134-b1c0-4c62-8add-22909916115c
8caad134-b1c0-4c62-8add-22909916115c
(in /home/ubuntu/cartodb)
** Invoke cartodb:vizs:export_user_visualization_json (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute cartodb:vizs:export_user_visualization_json
unknown OID 49759: failed to recognize type of 'bbox'. It will be treated as String.
rake aborted!
uninitialized constant CartoDB::Visualization::VizJSON
/home/ubuntu/cartodb/app/services/carto/visualizations_export_service.rb:62:in `export_to_json'
/home/ubuntu/cartodb/lib/tasks/viz_maintenance.rake:85:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => cartodb:vizs:export_user_visualization_json
```
and an empty `[visualizations id].json` file is created.

### Expected result
A `[visualizations id].json` file is created that contains all needed config to be able to import on another server.

### Browser and version
non (command line)

### .carto file
n/a

### Additional info
Using https://github.com/ruralinnovation/carto/tree/production

**Comment by gonzaloriestra** [comment]
ClubHouse issue: https://app.clubhouse.io/cartoteam/story/83455/can-t-export-visualizations-using-rake

**Comment by gonzaloriestra** [comment]
Hi, sorry for the late response.

That rake is deprecated, but you can use [this one](https://github.com/CartoDB/cartodb/blob/f04f0a9b5840bb80c9d3d6fd700287b1709a68e1/lib/tasks/viz_maintenance.rake#L79) or export through the UI.
