### ISSUE TITLE
Compatibility with Postgres 12

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/cartodb#15047]
### Context

Since I updated to PG12, builder processes error out at the start.

### Steps to Reproduce

1. Run builder or resque processes in a PG12 installation. 

### Current Result

Builder:
```
Started CARTO Builder.
Using rack adapter
/opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:208: warning: Failed to set the default_internal encoding to UTF8: 'no connection to the server
'
/opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:152:in `async_exec': Sequel::DatabaseDisconnectError: PG::UnableToSend: no connection to the server (Sequel::DatabaseConnectionError)
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-rails-1.0.1/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `block in instrument'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `instrument'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-rails-1.0.1/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:152:in `execute_query'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:140:in `block in execute'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:116:in `check_disconnect_errors'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:140:in `execute'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:245:in `block in connect'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:245:in `each'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:245:in `connect'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool.rb:122:in `make_new'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:270:in `synchronize'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:279:in `test_connection'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:58:in `connect'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/core.rb:122:in `connect'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-rails-1.0.1/lib/sequel_rails/configuration.rb:60:in `connect'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-rails-1.0.1/lib/sequel_rails/configuration.rb:8:in `setup'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-rails-1.0.1/lib/sequel_rails/railtie.rb:75:in `block in <class:Railtie>'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:347:in `each'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:347:in `call'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        from /opt/ruby2.5/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `public_send'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `method_missing'
        from /opt/carto/builder/config/environment.rb:19:in `<top (required)>'
        from /opt/carto/builder/config.ru:19:in `require'
        from /opt/carto/builder/config.ru:19:in `block in <main>'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `instance_eval'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `initialize'
        from /opt/carto/builder/config.ru:1:in `new'
        from /opt/carto/builder/config.ru:1:in `<main>'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:42:in `for'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:170:in `load_adapter'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:74:in `start'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/bin/thin:23:in `load'
        from /opt/carto/builder/vendor/bundle/ruby/2.5.0/bin/thin:23:in `<main>'
{:adapter=>"postgres", :host=>"localhost", :port=>5432, :direct_port=>5432, :database=>"carto_db_development", :username=>"postgres", :password=>nil, :conn_validator_timeout=>900, :connect_timeout=>2.5, :pool=>50, :prepared_statements=>false, :max_connections=>50}
{:host=>"localhost", :port=>5432, :dbname=>"carto_db_development", :user=>"postgres", :connect_timeout=>2.5}
D, [2019-08-09T11:33:23.025602 #15599] DEBUG -- :   Sequel::Postgres::Database (0.1ms)  SET standard_conforming_strings = ON
SET standard_conforming_strings = ON
#<Sequel::Postgres::Adapter:0x000055a4423d34e8>
no connection to the server
carto-builder.service: Main process exited, code=exited, status=1/FAILURE
carto-builder.service: Failed with result 'exit-code'.
```

Resque:
```
Started CARTO Builder queue.
/opt/carto/builder/vendor/bundle/ruby/2.5.0/gems/sequel-5.22.0/lib/sequel/adapters/postgres.rb:208: warning: Failed to set the default_internal encoding to UTF8: 'no connection to the server
'
rake aborted!
Sequel::DatabaseDisconnectError: PG::UnableToSend: no connection to the server
Tasks: TOP => environment
(See full trace by running task with --trace)
{:adapter=>"postgres", :host=>"localhost", :port=>5432, :direct_port=>5432, :database=>"carto_db_development", :username=>"postgres", :password=>nil, :conn_validator_timeout=>900, :connect_timeout=>2.5, :pool=>50, :prepared_statements=>false, :max_connections=>50}
{:host=>"localhost", :port=>5432, :dbname=>"carto_db_development", :user=>"postgres", :connect_timeout=>2.5}
D, [2019-08-09T11:33:23.207326 #15629] DEBUG -- :   Sequel::Postgres::Database (0.1ms)  SET standard_conforming_strings = ON
SET standard_conforming_strings = ON
#<Sequel::Postgres::Adapter:0x00005605047a2740>
no connection to the server
carto-resque.service: Main process exited, code=exited, status=1/FAILURE
carto-resque.service: Failed with result 'exit-code'.
```

### Additional info

The same installation (packages, configuration, etc) worked fine with PG11.

**Comment by Algunenano** [comment]
Accessing the database with those connection settings works fine:
```
$ psql -h localhost -U postgres -p 5432 carto_db_development -c "Select version()"
                                                   version                                                   
-------------------------------------------------------------------------------------------------------------
 PostgreSQL 12beta2 on x86_64-pc-linux-gnu, compiled by clang version 8.0.1 (tags/RELEASE_801/final), 64-bit
(1 row)
```

**Comment by Algunenano** [comment]
I was going to say this is almost embarrassing but it isn't. The issue is that the connection to the database is timing out (either because PG12 is slower or more likely because I've built it with all debugging active (symbols, trace, asserts, etc)). A better error message would have saved me hours :crying_cat_face:
