### ISSUE TITLE
Spamming WARNINGs in resque production.log

### ISSUE THREAD

**Issue by skgsergio** [CartoDB/cartodb#15064]
### Context
We were checking resque logs to track some issues and we saw this WARNING repeated a lot.

### Steps to Reproduce
Just check resque `production.log`.

### Current Result
Tons of WARNINGs like the following ones:

```
WARNING: Can't mass-assign protected attributes for Carto::UserTable: name, user_id
        app/models/table.rb:59:in `initialize'
        app/models/synchronization/member.rb:475:in `new'
        app/models/synchronization/member.rb:475:in `table'
        app/models/synchronization/member.rb:444:in `geocode_table'
        app/models/synchronization/member.rb:390:in `set_success_state_from'
        app/models/synchronization/member.rb:202:in `run'
        lib/resque/synchronization_jobs.rb:13:in `block in perform'
        lib/resque/base_job.rb:21:in `run_action'
        lib/resque/synchronization_jobs.rb:10:in `perform'
```
```
WARNING: Can't mass-assign protected attributes for Carto::UserTable: user_table
        app/models/table.rb:59:in `initialize'
        app/models/table_registrar.rb:11:in `new'
        app/models/table_registrar.rb:11:in `register'
        app/connectors/importer.rb:275:in `persist_metadata'
        app/connectors/importer.rb:127:in `register'
        app/connectors/importer.rb:89:in `block (2 levels) in register_results'
        app/connectors/importer.rb:88:in `each'
        app/connectors/importer.rb:88:in `block in register_results'
        lib/carto/bolt.rb:29:in `run_locked'
        app/connectors/importer.rb:87:in `register_results'
        app/connectors/importer.rb:74:in `run'
        app/models/data_import.rb:852:in `execute_importer'
        app/models/data_import.rb:441:in `dispatch'
        app/models/data_import.rb:189:in `run_import!'
        lib/resque/importer_jobs.rb:9:in `block in perform'
        lib/resque/base_job.rb:21:in `run_action'
        lib/resque/importer_jobs.rb:9:in `perform'
```

**Comment by alrocar** [comment]
@CartoDB/rt-managers Let's tackle this via RT, should be a quick fix and will help infra to better read logs.

Thanks!

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83595/spamming-warnings-in-resque-production-log
