### ISSUE TITLE
NoMethodError in Admin/visualizations#index 

### ISSUE THREAD

**Issue by jrgcampuzano** [CartoDB/cartodb#1698]
After the latest update I noticed this error in a fresh instalation using Docker, after that works well,

Log:

 Showing /cartodb/app/views/admin/visualizations/index.html.erb where line #7 raised:

undefined method `[]' for nil:NilClass

Extracted source (around line #7):

4: <%= content_for(:js) do -%>
5:   <%= javascript_include_tag 'cdb.js', 'models.js', 'templates.js', 'application.js', 'dashboard.js' -%>
6:   <script type="text/javascript">
7:     var username = "<%= current_user.username %>";
8:     var user_data = <%=raw current_user.data.to_json.html_safe %>;
9:     var config = <%=raw frontend_config.html_safe %>;
10:     var upgrade_url = "<%= upgrade_url %>";

Rails.root: /cartodb
Application Trace | Framework Trace | Full Trace

app/helpers/application_helper.rb:76:in `frontend_config'
app/views/admin/visualizations/index.html.erb:7:in`block in _app_views_admin_visualizations_index_html_erb___1696397319604820880_56484340'
app/views/admin/visualizations/index.html.erb:4:in `_app_views_admin_visualizations_index_html_erb___1696397319604820880_56484340'
app/controllers/admin/visualizations_controller.rb:22:in`block (2 levels) in index'
app/controllers/admin/visualizations_controller.rb:21:in `index'

Request

Parameters:

{"user_domain"=>nil}

**Comment by juanje** [comment]
Hi @jrgcampuzano, could you paste the whole error trace?

Until you give us the the error I can't be sure, but I'm almost sure that the problem comes from the config file `app_config.yml`.
There is probably a missing key (I bet it's the `:mixpanel` one). Most of the config keys need to exist, even if they are empty because you don't use that external service.

Check if you have the [mixpanel config key](https://github.com/CartoDB/cartodb/blob/master/config/app_config.yml.sample#L80-L83) missing or commented.
If it's the case, try to uncomment it and restart rails.

**Comment by jrgcampuzano** [comment]
Hi juanje,

Sorry for not getting right back to you, you can see the complete log below.
Regards,
Jorge

NoMethodError in Admin/visualizations#index

Showing /cartodb/app/views/admin/visualizations/index.html.erb where line #7 raised:

undefined method `[]' for nil:NilClass

Extracted source (around line #7):

4: <%= content_for(:js) do -%>
5:   <%= javascript_include_tag 'cdb.js', 'models.js', 'templates.js', 'application.js', 'dashboard.js' -%>
6:   <script type="text/javascript">
7:     var username = "<%= current_user.username %>";
8:     var user_data = <%=raw current_user.data.to_json.html_safe %>;
9:     var config = <%=raw frontend_config.html_safe %>;
10:     var upgrade_url = "<%= upgrade_url %>";

Rails.root: /cartodb
Application Trace | Framework Trace | Full Trace

app/helpers/application_helper.rb:76:in `frontend_config'
app/views/admin/visualizations/index.html.erb:7:in `block in _app_views_admin_visualizations_index_html_erb___1941451056950070316_68288200'
app/views/admin/visualizations/index.html.erb:4:in `_app_views_admin_visualizations_index_html_erb___1941451056950070316_68288200'
app/controllers/admin/visualizations_controller.rb:25:in `block (2 levels) in index'
app/controllers/admin/visualizations_controller.rb:24:in `index'

Request

Parameters:

{"user_domain"=>nil}

Show session dump

Show env dump
Response

Headers:

None

**Comment by jrgcampuzano** [comment]
Console log:

Rendered admin/visualizations/index.html.erb within layouts/application (396.8                                                                                                                               ms)
Completed 500 Internal Server Error in 441ms
[Rollbar] Reporting exception: undefined method `[]' for nil:NilClass
[Rollbar] Exception not reported because Rollbar is disabled

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    4: <%= content_for(:js) do -%>
    5:   <%= javascript_include_tag 'cdb.js', 'models.js', 'templates.js', 'appl                                                                                                                               ication.js', 'dashboard.js' -%>
    6:   <script type="text/javascript">
    7:     var username = "<%= current_user.username %>";
    8:     var user_data = <%=raw current_user.data.to_json.html_safe %>;
    9:     var config = <%=raw frontend_config.html_safe %>;
    10:     var upgrade_url = "<%= upgrade_url %>";
  app/helpers/application_helper.rb:76:in `frontend_config'
  app/views/admin/visualizations/index.html.erb:7:in `block in _app_views_admin_                                                                                                                               visualizations_index_html_erb___1941451056950070316_68288200'
  app/views/admin/visualizations/index.html.erb:4:in `_app_views_admin_visualiza                                                                                                                               tions_index_html_erb___1941451056950070316_68288200'
  app/controllers/admin/visualizations_controller.rb:25:in `block (2 levels) in                                                                                                                                index'
  app/controllers/admin/visualizations_controller.rb:24:in `index'


  Rendered /usr/local/rvm/gems/ruby-1.9.3-p547/gems/actionpack-3.2.2/lib/action_                                                                                                                               dispatch/middleware/templates/rescues/_trace.erb (3.1ms)
  Rendered /usr/local/rvm/gems/ruby-1.9.3-p547/gems/actionpack-3.2.2/lib/action_                                                                                                                               dispatch/middleware/templates/rescues/_request_and_response.erb (1.2ms)
  Rendered /usr/local/rvm/gems/ruby-1.9.3-p547/gems/actionpack-3.2.2/lib/action_                                                                                                                               dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (                                                                                                                               15.2ms)


Started GET "/favicon.ico" for 189.230.28.66 at 2015-01-23 21:41:47 +0000
[Rollbar] Reporting exception: No route matches [GET] "/favicon.ico"
[Rollbar] Exception not reported because Rollbar is disabled

ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  actionpack (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `c                                                                                                                               all'
  rollbar (0.12.14) lib/rollbar/middleware/rails/show_exceptions.rb:19:in `call_                                                                                                                               with_rollbar'
  actionpack (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `ca                                                                                                                               ll'
  railties (3.2.2) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.2) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in `                                                                                                                               call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/static.rb:61:in `call'
  railties (3.2.2) lib/rails/engine.rb:479:in `call'
  railties (3.2.2) lib/rails/application.rb:220:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in `call'
  railties (3.2.2) lib/rails/rack/log_tailer.rb:14:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `catch'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.4.1) lib/rack/handler/thin.rb:13:in `run'
  rack (1.4.1) lib/rack/server.rb:265:in `start'
  railties (3.2.2) lib/rails/commands/server.rb:70:in `start'
  railties (3.2.2) lib/rails/commands.rb:55:in `block in <top (required)>'
  railties (3.2.2) lib/rails/commands.rb:50:in `tap'
  railties (3.2.2) lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:6:in `require'
  script/rails:6:in `<main>'


  Rendered /usr/local/rvm/gems/ruby-1.9.3-p547/gems/actionpack-3.2.2/lib/action_                                                                                                                               dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (1                                                                                                                               .0ms)


Started GET "/favicon.ico" for 189.230.28.66 at 2015-01-23 21:41:47 +0000
[Rollbar] Reporting exception: No route matches [GET] "/favicon.ico"
[Rollbar] Exception not reported because Rollbar is disabled

ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  actionpack (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `c                                                                                                                               all'
  rollbar (0.12.14) lib/rollbar/middleware/rails/show_exceptions.rb:19:in `call_                                                                                                                               with_rollbar'
  actionpack (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `ca                                                                                                                               ll'
  railties (3.2.2) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.2) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in `                                                                                                                               call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/static.rb:61:in `call'
  railties (3.2.2) lib/rails/engine.rb:479:in `call'
  railties (3.2.2) lib/rails/application.rb:220:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in `call'
  railties (3.2.2) lib/rails/rack/log_tailer.rb:14:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `catch'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.4.1) lib/rack/handler/thin.rb:13:in `run'
  rack (1.4.1) lib/rack/server.rb:265:in `start'
  railties (3.2.2) lib/rails/commands/server.rb:70:in `start'
  railties (3.2.2) lib/rails/commands.rb:55:in `block in <top (required)>'
  railties (3.2.2) lib/rails/commands.rb:50:in `tap'
  railties (3.2.2) lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:6:in `require'
  script/rails:6:in `<main>'


  Rendered /usr/local/rvm/gems/ruby-1.9.3-p547/gems/actionpack-3.2.2/lib/action_                                                                                                                               dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (0                                                                                                                               .6ms)

**Comment by mtwestra** [comment]
I am facing the same issue. Some further stack traces:

```
NoMethodError in Admin/visualizations#index

Showing /cartodb/app/views/admin/visualizations/index.html.erb where line #7 raised:

undefined method `[]' for nil:NilClass
Extracted source (around line #7):

4: <%= content_for(:js) do -%>
5:   <%= javascript_include_tag 'cdb.js', 'models.js', 'templates.js', 'application.js', 'dashboard.js' -%>
6:   <script type="text/javascript">
7:     var username = "<%= current_user.username %>";
8:     var user_data = <%=raw current_user.data.to_json.html_safe %>;
9:     var config = <%=raw frontend_config.html_safe %>;
10:     var upgrade_url = "<%= upgrade_url %>";
Rails.root: /cartodb

Application Trace | Framework Trace | Full Trace
app/helpers/application_helper.rb:76:in `frontend_config'
app/views/admin/visualizations/index.html.erb:7:in `block in _app_views_admin_visualizations_index_html_erb__4393918379638946914_59593300'
app/views/admin/visualizations/index.html.erb:4:in `_app_views_admin_visualizations_index_html_erb__4393918379638946914_59593300'
app/controllers/admin/visualizations_controller.rb:25:in `block (2 levels) in index'
app/controllers/admin/visualizations_controller.rb:24:in `index'

####Request

Parameters:

{"user_domain"=>nil}
Show session dump

_csrf_token: "4iUpBDUPZaeo/IbLIsfGF7uspZDWAxQDSSDKaIXkW21NS8="
session_id: "86d1770ccf5edfdf28a7f3ebdd0d0892e"
warden.user.cartodb.key: "cartodb"
Show env dump

GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate, sdch"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.8,es;q=0.6,fr;q=0.4,nl;q=0.2"
HTTP_CACHE_CONTROL: "max-age=0"
REMOTE_ADDR: "95.97.154.90"
SERVER_NAME: "cartodb.xxxxxxx.org"
SERVER_PROTOCOL: "HTTP/1.1"
```

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
