### ISSUE TITLE
Date column geocoded as if it were an IP

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#1857]
This [file](https://gist.githubusercontent.com/rafatower/a0df0afc0ccc3c4fcbbc/raw/52fb574e8fad51d89e22286dee7be84c72287116/date_time.csv) is being geocoded as if the column date contained IP's.

**Comment by rafatower** [comment]
Interestingly, I cannot reproduce it locally nor in staging :(

**Comment by rafatower** [comment]
I managed to reproduce it locally launching resque with ruby v `1.9.3-p0` as in production.

**Comment by rafatower** [comment]
The simplest test for this:
Good:
```
$ irb
1.9.3-p547 :001 > require 'ipaddr'
 => true 
1.9.3-p547 :002 > IPAddr.new("14/08/2014")
ArgumentError: invalid address
	from /home/developer/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/ipaddr.rb:544:in `in6_addr'
	from /home/developer/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/ipaddr.rb:481:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /home/developer/.rvm/rubies/ruby-1.9.3-p547/bin/irb:12:in `<main>'
```

Bad:
```
$ irb
irb(main):001:0> require 'ipaddr'
=> true
irb(main):002:0> IPAddr.new("14/08/2014")
=> #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/ff00:0000:0000:0000:0000:0000:0000:0000>
```

**Comment by rafatower** [comment]
If we take this sample file
```Ruby
# File test.rb
require 'ipaddr'

puts IPAddr.new("14/08/2014")
```
and run it through strace:
```
# Bad
$ strace -s 500 ruby /tmp/test.rb 2>&1 | grep ^open | grep ipaddr | grep -v ENOENT
open("/usr/lib/ruby/1.9.1/ipaddr.rb", O_RDONLY) = 5
open("/usr/lib/ruby/1.9.1/ipaddr.rb", O_RDONLY) = 5
```
and taking a look at the code, it seems to be indeed part of ruby 1.9.1 rather than 1.9.3 (you can check missing constants and stuff alike).

**Comment by rafatower** [comment]
Fixed
