### ISSUE TITLE
"Silently retrying renaming importer" errors

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2098]
https://rollbar.com/vizzuality/CartoDB/items/426/occurrences/4099178477/

**Comment by rafatower** [comment]
Stricking again, reopening this ticket

Duplicates https://github.com/CartoDB/cartodb/issues/1377

**Comment by rafatower** [comment]
Some of the last traces:
```
Silently retrying renaming importer_3a2e28d6e9c311e494590e6e1df11cbf to some_table_name_2 (current: some_table_name_2_20). 21 attempts.
Data import: 8f90f233-3616-4914-922a-6417407dc110.
ERROR: PG::Error: ERROR: relation "some_table_name_2_20" already exists

...
app/connectors/importer.rb:138:in `rescue in rename'
app/connectors/importer.rb:107:in `rename'
app/connectors/importer.rb:138:in `rescue in rename'
app/connectors/importer.rb:107:in `rename'
app/connectors/importer.rb:138:in `rescue in rename'
app/connectors/importer.rb:107:in `rename'
app/connectors/importer.rb:60:in `register'
app/connectors/importer.rb:50:in `block in run'
app/connectors/importer.rb:49:in `each'
app/connectors/importer.rb:49:in `run'
app/models/data_import.rb:588:in `new_importer'
app/models/data_import.rb:331:in `dispatch'
app/models/data_import.rb:158:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

**Comment by rafatower** [comment]
Here's the renaming code:
```ruby
        database.execute(%Q{
          ALTER TABLE "#{ORIGIN_SCHEMA}"."#{current_name}" RENAME TO "#{new_name}"
        })
```

Some previous failure in importer leaves leaked tables in cdb schema

**Comment by rafatower** [comment]
It is happening to one of our users used to monitor the platform. Alejandro cleaned it up

IMO the renaming should occur in the destination schema, something to change with the new importing/cartodbfication process cc/ @Kartones @javisantana 

I'm closing this again unless anybody is strongly opposed.
