### ISSUE TITLE
sync tables break visualizations 

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2569]
Given a multiuser account

if you have a visualization in which a layer has a SQL query that uses data from other account sync table when it's synced the visualizaion stops working (the query is reverted)

SB/4501439

**Comment by juanignaciosl** [comment]
It's a permissions problem:

1. Create sync table T with user A.
2. Give user B read permission on T.
3. Create visualization V with user B.
4. Sync table T.
5. Loading visualization V throws permission errors:

```
http://my-org-5-02.localhost.lan:8080/api/v2/sql?q=select%20*%20from%20(SELECT%20*%20FROM%20%22my-org-5-admin%22.test_support_1)%20__wrapped%20limit%200&api_key=e3b551e8a8d3db7bdaadaf3b4e2fcded495ac01b

{"error":["permission denied for relation test_support_1"],"stack":"error: permission denied for relation test_support_1\n    at Connection.parseE (/CartoDB-SQL-API/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:553:11)\n    at Connection.parseMessage (/CartoDB-SQL-API/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:382:17)\n    at null.<anonymous> (/CartoDB-SQL-API/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:105:18)\n    at Socket.EventEmitter.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:746:14)\n    at Socket.EventEmitter.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:408:10)\n    at emitReadable (_stream_readable.js:404:5)\n    at readableAddChunk (_stream_readable.js:165:9)\n    at Socket.Readable.push (_stream_readable.js:127:10)"}


http://my-org-5-02.localhost.lan:8181/api/v1/map?map_key=e3b551e8a8d3db7bdaadaf3b4e2fcded495ac01b

{"errors":["Postgis Plugin: ERROR:  permission denied for relation test_support_1\n\nin executeQuery Full sql was: 'SELECT * FROM (SELECT * FROM \"my-org-5-admin\".test_support_1) as cdbq LIMIT 0'\n  encountered during parsing of layer 'layer0' in Layer"]}

```

**Comment by juanignaciosl** [comment]
There's one working case that was making testing more confusing: import - trigger sync - give permission - create visualization . From now on, any sync that doesn't change data will keep viz working. Nevertheless, any other permutation of previous events work.
