### ISSUE TITLE
Regression in csv import test

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#2585]
- [x] Capture the `Encoding::UndefinedConversionError` and provide a meaningful error to the user rather than `99999`
- [x] Fix regression test
- [ ] Figure out difference between prod and clinker (I think it is ruby stdlib but not sure)
- [ ] Fix clinker environment to match production

See https://github.com/CartoDB/cartodb/issues/2107#issuecomment-76928412

Can be reproduced by importing https://raw.githubusercontent.com/CartoDB/cartodb/master/services/importer/spec/fixtures/in_cell_line_breaks.csv

It doesn't happen in clinker because the version of ogr2ogr2 was not upgraded in clinker.

```
developer@cartodbv3:~/src/cartodb$ bundle exec rspec ./services/importer/spec/acceptance/csv_spec.rb:128
Run options: include {:locations=>{"./services/importer/spec/acceptance/csv_spec.rb"=>[128]}}

csv regression tests
  imports records with cell line breaks (FAILED - 1)

Failures:

  1) csv regression tests imports records with cell line breaks
     Failure/Error: runner.db[%Q{
     Sequel::DatabaseError:
       PG::Error: ERROR:  relation "cdb_importer.importer_91398296c1ab11e4b3da3e06c05daa57" does not exist
       LINE 3:       FROM cdb_importer.importer_91398296c1ab11e4b3da3e06c05...
                          ^
     # ./services/importer/spec/acceptance/csv_spec.rb:140:in `block (2 levels) in <top (required)>'

Finished in 0.70106 seconds
1 example, 1 failure

Failed examples:

rspec ./services/importer/spec/acceptance/csv_spec.rb:128 # csv regression tests imports records with cell line breaks
```

```
2015-03-03 11:18:29 UTC: Filename: /tmp/imports/20150303-7340-1mabedw/in_cell_line_breaks.csv Size (bytes): 1497
2015-03-03 11:18:29 UTC: Importing data from /tmp/imports/20150303-7340-1mabedw/in_cell_line_breaks.csv
2015-03-03 11:18:29 UTC: File-based import load
2015-03-03 11:18:29 UTC: Errored importing data from /tmp/imports/20150303-7340-1mabedw/in_cell_line_breaks.csv:
2015-03-03 11:18:29 UTC: Encoding::UndefinedConversionError: "\x8D" to UTF-8 in conversion from Windows-1252 to UTF-8
2015-03-03 11:18:29 UTC: ----------------------------------------------------
2015-03-03 11:18:29 UTC: ["/home/developer/src/cartodb/services/importer/lib/importer/csv_normalizer.rb:128:in `each_line'"
 "/home/developer/src/cartodb/services/importer/lib/importer/csv_normalizer.rb:128:in `normalize'"
 "/home/developer/src/cartodb/services/importer/lib/importer/csv_normalizer.rb:52:in `run'"
 "/home/developer/src/cartodb/services/importer/lib/importer/loader.rb:117:in `block (2 levels) in normalize'"
 "/home/developer/src/cartodb/services/importer/lib/importer/importer_stats.rb:56:in `timing'"
 "/home/developer/src/cartodb/services/importer/lib/importer/loader.rb:110:in `block in normalize'"
 "/home/developer/src/cartodb/services/importer/lib/importer/loader.rb:107:in `each'"
 "/home/developer/src/cartodb/services/importer/lib/importer/loader.rb:107:in `inject'"
 "/home/developer/src/cartodb/services/importer/lib/importer/loader.rb:107:in `normalize'"
```

The failure is in the `File.open` with a particular encoding along these lines:
```Ruby
      def normalize(temporary_filepath)
        temporary_csv = ::CSV.open(temporary_filepath, 'w', col_sep: OUTPUT_DELIMITER)
        File.open(filepath, 'rb', external_encoding: encoding)
```

**Comment by rafatower** [comment]
I'm closing this for the moment. We'd need to investigate differences in clinker but I think it's not worth the effort right now
