### ISSUE TITLE
Import error by importing file named "fetch"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2718]
Steps:

1. Create any CSV file with name `fetch`. The same happens, for example, with a GeoJSON file. I suppose is a general thing.
2. Import it to CartoDB.

````
2015-03-11 11:18:50 UTC: Exception: PG::Error: ERROR:  syntax error at or near \"fetch\"\nLINE 2:           ALTER TABLE fetch
 2015-03-11 11:18:50 UTC: [\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-
3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'\"

[...]
````

DataImport ID example: 
` irb(main):002:0> DataImport['8e0c020b-2cea-4f5f-8460-b7408c45dcc4'].log `

**Comment by iriberri** [comment]
Something similar with name "intersect":


````
2015-05-17 20:31:29 UTC: Exception: PG::Error: ERROR:  syntax error at or near "intersect"
LINE 1: SELECT count(*) as count from intersect
                                      ^

2015-05-17 20:31:29 UTC: ["/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in `check_database_errors'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/dataset/actions.rb:778:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:523:in `fetch_rows'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/dataset/actions.rb:154:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel_pg-1.6.3/lib/sequel_pg/sequel_pg.rb:58:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/dataset/actions.rb:546:in `single_record'", 
`````

Import ID: 86b5d30f-2497-48c7-bb1a-d74370f31826

**Comment by iriberri** [comment]
The same with `both`

````
2015-06-01 02:55:24 UTC: Exception: PG::Error: ERROR:  syntax error at or near \"both\"\nLINE 2:           ALTER TABLE both\n
`````
irb(main):001:0> DataImport['55f42f19-434c-463b-bf1b-e33ff28cf272'].log
