### ISSUE TITLE
A broken sync makes a table lose the_geom_webmercator

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2725]
A user has reported problems with a sync table. Table sync failed because of a download error, but it should've not lost any column. Here's the trace:

```
UTC: DOWNLOAD ERROR: Code:500 Body:
2015-03-11 09:26:31 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/downloader.rb:185:in `download_and_store'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/downloader.rb:118:in `set_downloaded_source_file'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/downloader.rb:60:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/runner.rb:229:in `block (2 levels) in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/importer_stats.rb:56:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/runner.rb:228:in `block in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/importer_stats.rb:56:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/runner.rb:227:in `single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/runner.rb:92:in `run_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/runner.rb:85:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/importer_stats.rb:56:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/services/importer/lib/importer/runner.rb:84:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/app/models/synchronization/adapter.rb:19:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/app/models/synchronization/member.rb:188:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/lib/resque/synchronization_jobs.rb:11:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/20150310182413/lib/resque/synchronization_jobs.rb:10:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:19:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:19:in `<main>'"]+
2015-03-11 09:26:31 UTC: ******** synchronization failed ********
```
```

cc @rambo @rochoa @Kartones @rafatower

**Comment by iriberri** [comment]
Not anymore! :-) https://github.com/CartoDB/cartodb/pull/7543

We now only sync the table (overwrite the old by a new one) if everything (cartodbfication, and some special checks on cartodb_id and the_geom) is okay. The current behaviour provides always a supported CartoDB table after sync, which wasn't happening previously.
