### ISSUE TITLE
Country guessing not working in on-premise

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#2789]
This is caused by the missing api key for the `geocoding` account, which is intentional. It will issue the following warning during the content guessing phase:
```
WARNING: create_the_geom_from_country_guessing failed: CartoDB::SQLApi::PermissionError
```

The API key should not be needed for read-only operations on that account.

cc/ @azamorano

**Comment by rafatower** [comment]
Backtrace of the `PermissionError` exception:
```
/home/developer/src/cartodb/services/sql-api/sql_api.rb:47:in `raise_if_error'
/home/developer/src/cartodb/services/sql-api/sql_api.rb:35:in `handle_response'
/home/developer/src/cartodb/services/sql-api/sql_api.rb:28:in `fetch'
/home/developer/src/cartodb/services/importer/lib/importer/content_guesser.rb:197:in `countries'
/home/developer/src/cartodb/services/importer/lib/importer/content_guesser.rb:134:in `block in country_proportion'
/home/developer/src/cartodb/services/importer/lib/importer/content_guesser.rb:134:in `count'
/home/developer/src/cartodb/services/importer/lib/importer/content_guesser.rb:134:in `country_proportion'
/home/developer/src/cartodb/services/importer/lib/importer/content_guesser.rb:66:in `is_country_column?'
/home/developer/src/cartodb/services/importer/lib/importer/content_guesser.rb:39:in `block in country_column'
```

**Comment by rafatower** [comment]
Fixed by changing perms of the table to "public with link" so that clients without API key can perform the query.
