### ISSUE TITLE
invalid date 2015-03-18 on import

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2828]
https://cartodb.com/superadmin/users/86357/data_imports/9d116a8e-968a-41d9-ab8f-6c83886eeac7

```
{"item":{"data":{"data_source":"https://data.ny.gov/api/views/qq4h-8p86/rows.csv?accessType=DOWNLOAD","data_type":"url","table_name":null,"state":"complete","success":true,"logger":"19b1fd1f-e278-45c5-8a4c-5fcb3a77de34","updated_at":"2015-03-18T18:01:05+00:00","created_at":"2015-03-18T18:01:04+00:00","error_code":99999,"queue_id":null,"tables_created_count":0,"table_names":"","append":false,"migrate_table":null,"table_copy":null,"from_query":null,"synchronization_id":null,"id":"9d116a8e-968a-41d9-ab8f-6c83886eeac7","table_id":null,"user_id":"d7a8c798-1531-428e-bc6a-4d034e6604a1","service_name":"public_url","service_item_id":"https://data.ny.gov/api/views/qq4h-8p86/rows.csv?accessType=DOWNLOAD","stats":"[]","type_guessing":true,"quoted_fields_guessing":false,"content_guessing":false,"server":"que02.useb.cartodb.net","host":"10.0.128.22","resque_ppid":28284,"upload_host":"rui02.useb.cartodb.net","create_visualization":true,"visualization_id":null,"user_defined_limits":"{\"twitter_credits_limit\":0}"},"log":"2015-03-18 18:01:04 UTC: Running on server que02.useb.cartodb.net with PID: 20481\n2015-03-18 18:01:04 UTC: new_importer()\n2015-03-18 18:01:04 UTC: Fetching datasource public_url metadata for item id https://data.ny.gov/api/views/qq4h-8p86/rows.csv?accessType=DOWNLOAD\n2015-03-18 18:01:05 UTC: File will be downloaded from https://data.ny.gov/api/views/qq4h-8p86/rows.csv?accessType=DOWNLOAD\n2015-03-18 18:01:05 UTC: Before importer run\n2015-03-18 18:01:05 UTC: invalid date\n2015-03-18 18:01:05 UTC: [\"/home/ubuntu/www/production.cartodb.com/releases/20150318161151/services/importer/lib/importer/downloader.rb:267:in `httpdate'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150318161151/services/importer/lib/importer/downloader.rb:267:in `last_modified_from'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150318161151/services/importer/lib/importer/downloader.rb:115:in `set_downloaded_source_file'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150318161151/services/importer/lib/importer/downloader.rb:60:in `run'\", 
```

cc @Kartones @rafatower @sanderpick

**Comment by Kartones** [comment]
I'll fix it, either properly parsing their format or skipping it if comes borked
