### ISSUE TITLE
NaturalEarth imports non-deterministically import .shp or README as .csv

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#2858]
When importing this file:

http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries_lakes.zip

on different accounts, several times, it seems that sometimes chooses to import the README as a blank .csv (incorrect) and other times the .shp (correct).

It seems that both files are imported on the same temporary table. The order for the .zip is not deterministic, so sometimes the .shp fails and sometimes the .csv does.

See:

 ```
2015-03-23 09:51:30 UTC: Running on server que02.useb.cartodb.net with PID: 11111
2015-03-23 09:51:30 UTC: new_importer()
2015-03-23 09:51:30 UTC: Fetching datasource public_url metadata for item id http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries_lakes.zip
2015-03-23 09:51:31 UTC: File will be downloaded from http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries_lakes.zip
2015-03-23 09:51:31 UTC: Before importer run
2015-03-23 09:51:35 UTC: Starting import for /tmp/imports/20150323-11111-15hebj/ne_10m_admin_0_countries_lakes.zip
2015-03-23 09:51:35 UTC: Unpacking /tmp/imports/20150323-11111-15hebj/ne_10m_admin_0_countries_lakes.zip
2015-03-23 09:51:36 UTC: Filename: /tmp/imports/20150323-11111-pg1v6m/ne_10m_admin_0_countries_lakes.version.csv Size (bytes): 5
2015-03-23 09:51:36 UTC: Importing data from /tmp/imports/20150323-11111-pg1v6m/ne_10m_admin_0_countries_lakes.version.csv
2015-03-23 09:51:36 UTC: File-based import load
2015-03-23 09:51:36 UTC: Detected encoding UTF-8
2015-03-23 09:51:36 UTC: Using database connection with ....
2015-03-23 09:51:40 UTC: ogr2ogr call:      OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8  /usr/bin/ogr2ogr2 -f PostgreSQL -oo AUTODETECT_TYPE=YES -oo QUOTED_FIELDS_AS_STRING=NO PG:...-lco DIM=2 -lco PRECISION=NO /tmp/imports/20150323-11111-pg1v6m/ne_10m_admin_0_countries_lakes.version.csv  -nln cdb_importer.importer_2ec34844d14211e4ab9a0e5e07bb5d8a -nlt PROMOTE_TO_MULTI
2015-03-23 09:51:40 UTC: ogr2ogr output:    
2015-03-23 09:51:40 UTC: ogr2ogr exit code: 0
2015-03-23 09:51:40 UTC: Georeferencing...
2015-03-23 09:51:40 UTC: Disabling autovacuum for "cdb_importer"."importer_2ec34844d14211e4ab9a0e5e07bb5d8a"
2015-03-23 09:51:40 UTC: Trying ip guessing...
2015-03-23 09:51:40 UTC: Trying country guessing...
2015-03-23 09:51:40 UTC: Creating the_geom column
2015-03-23 09:51:40 UTC: Enabling autovacuum for "cdb_importer"."importer_2ec34844d14211e4ab9a0e5e07bb5d8a"
2015-03-23 09:51:40 UTC: Georeferenced
2015-03-23 09:51:40 UTC: Finished importing data from /tmp/imports/20150323-11111-pg1v6m/ne_10m_admin_0_countries_lakes.version.csv
2015-03-23 09:51:40 UTC: Filename: /tmp/imports/20150323-11111-pg1v6m/ne_10m_admin_0_countries_lakes.shp Size (bytes): 8995932
2015-03-23 09:51:40 UTC: Importing data from /tmp/imports/20150323-11111-pg1v6m/ne_10m_admin_0_countries_lakes.shp
2015-03-23 09:51:40 UTC: File-based import load
2015-03-23 09:51:44 UTC: Detected encoding UTF-8
2015-03-23 09:51:44 UTC: Using database connection with....
2015-03-23 09:51:51 UTC: ogr2ogr call:      OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8 SHAPE_ENCODING=UTF-8 /usr/bin/ogr2ogr -f PostgreSQL  PG:"...." -t_srs EPSG:4326  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20150323-11111-pg1v6m/ne_10m_admin_0_countries_lakes.shp  -nln cdb_importer.importer_2ec34844d14211e4ab9a0e5e07bb5d8a -nlt PROMOTE_TO_MULTI
2015-03-23 09:51:51 UTC: ogr2ogr output:    FAILED: Layer cdb_importer.importer_2ec34844d14211e4ab9a0e5e07bb5d8a already exists, and -append not specified.
        Consider using -append, or -overwrite.
ERROR 1: Terminating translation prematurely after failed
translation of layer ne_10m_admin_0_countries_lakes (use -skipfailures to skip errors)


2015-03-23 09:51:51 UTC: ogr2ogr exit code: 256
2015-03-23 09:51:51 UTC: Errored importing data from /tmp/imports/20150323-11111-pg1v6m/ne_10m_admin_0_countries_lakes.shp:
2015-03-23 09:51:51 UTC: CartoDB::Importer2::LoadError: #<CartoDB::Log:0x00000008a17360>
2015-03-23 09:51:51 UTC: ----------------------------------------------------
2015-03-23 09:51:51 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/loader.rb:258:in `run_ogr2ogr'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/loader.rb:62:in `block (2 levels) in run'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/loader.rb:61:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/loader.rb:50:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:223:in `file_based_loader_run'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:178:in `import'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:256:in `block (3 levels) in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:249:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:249:in `block (2 levels) in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:248:in `block in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:227:in `single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:92:in `run_import'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:85:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/services/importer/lib/importer/runner.rb:84:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/app/connectors/importer.rb:39:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/app/models/data_import.rb:523:in `new_importer'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/app/models/data_import.rb:266:in `dispatch'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/app/models/data_import.rb:107:in `run_import!'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/lib/resque/importer_jobs.rb:9:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/20150323092414/lib/resque/importer_jobs.rb:9:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:19:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:19:in `<main>'"]
2015-03-23 09:51:51 UTC: ----------------------------------------------------
2015-03-23 09:51:51 UTC: Proceeding to register
2015-03-23 09:51:51 UTC: Before renaming from importer_2ec34844d14211e4ab9a0e5e07bb5d8a to ne_10m_admin_0_countries_lakes.version
2015-03-23 09:51:51 UTC: Before moving schema 'ne_10m_admin_0_countries_lakes_version_3' from cdb_importer to basemaptest
2015-03-23 09:51:51 UTC: Before persisting metadata 'ne_10m_admin_0_countries_lakes_version_3' data_import_id: ee8b0b58-587d-4dc3-b2f5-b80fc9bb49ff
2015-03-23 09:51:53 UTC: Table 'ne_10m_admin_0_countries_lakes_version_3' registered
2015-03-23 09:51:53 UTC: After importer run
2015-03-23 09:51:53 UTC: After dispatch
2015-03-23 09:51:53 UTC: Import finished
```

**Comment by zenitraM** [comment]
To add to this, the problem seems to happen also when importing a file with multiple SHPs.

Any of the files at "Distritos" here is an example:
http://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=a4f36d34fa86c410VgnVCM2000000c205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD

Only the first is imported, the rest are tried but they fail as they get written to the same cdb_importer temporary table

**Comment by ohasselblad** [comment]
hola, adding myself to this to track it

**Comment by ohasselblad** [comment]
Hey @Kartones have you been able to work on this? Soon I'm going to be talking to some professors who use Natural Earth data and have had these import problems in the past..

**Comment by Kartones** [comment]
No, sorry, talk with @saleiva or @javisantana so they reprioritize it if it becomes urgent

**Comment by ohasselblad** [comment]
@saleiva any chance we can get this prioritized to be done in the next month? i know some professors who depend on pulling data from here but were very frustrated from this bug.

**Comment by Kartones** [comment]
Oh, sorry for not noticing this ticket @ohasselblad (I had another similar one), I fixed this issue two weeks ago with [this branch](https://github.com/CartoDB/cartodb/pull/4498), now it works (one of the tests I did was using natural earth downloads) :smiley:

**Comment by ohasselblad** [comment]
Ah, perfect! Thanks @Kartones :+1:
