### ISSUE TITLE
Fix broken tests after merging with master

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3058]
At least currently some failures like this one:
```Rails
Failures:

  1) Api::Json::VisualizationsController behaves like visualization controllers main behaviour tests exclude_shared and only_shared filters
     Failure/Error: private_tables_enabled: true
       
       expected: true
            got: false
       
       (compared using ==)
     Shared Example Group: "visualization controllers" called from ./spec/requests/api/json/visualizations_controller_spec.rb:8
     # ./spec/support/factories/users.rb:68:in `create_user'
     # ./spec/requests/api/json/visualizations_controller_shared_examples.rb:105:in `block (3 levels) in <top (required)>'
```

**Comment by rafatower** [comment]
The problem seems to be that the user is already created by a previous stage:
```
(rdb:1) user.valid?
false
(rdb:1) user.errors
{:email=>["is already taken"]}
```
hard to control as far as we have duplicate code (just check `git grep 'client@example.com'`)

**Comment by rafatower** [comment]
the user in section `before(:all)` was colliding with the one created in the `include_context 'visualization creation helpers'`
