### ISSUE TITLE
User deletion with geocodings does not work

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#3073]
While deleting an user which has an import with geocodings:

```
ERROR:  update or delete on table "data_imports" violates foreign key constraint "geocodings_data_import_id_fkey" on table "geocodings"
DETAIL:  Key (id)=(....) is still referenced from table "geocodings".
STATEMENT:  DELETE FROM "data_imports" WHERE "id" = '....'
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

It seems that the `data_import` model is dropped before the `geocoding` model, but does not cascade the deletion nor drops the dependencies first. (ask me for an example of this in prod)

**Comment by juanignaciosl** [comment]
It's likely to happen only for organization users, because of [this method](https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L2360) ([diff](https://github.com/CartoDB/cartodb/commit/ac5423d23b763f0a9cf9a4fe5e9fae67760bf129#diff-4676c008b11a5480d73d4a6de01e45b9)) which is an attempt to fix CartoDB/cartodb-central#511.

Nevertheless I don't see why at first sight, since data import deletion has always been done before geocoding deletion. @zenitraM have you got the full stack trace?

cc @Kartones

**Comment by zenitraM** [comment]
@juanignaciosl nope, this is with a free account, doesn't seem to have ever been related to an organization

Rails trace is:

```
Sequel::DatabaseError: PG::Error: ERROR:  current transaction is aborted, commands ignored until end of transaction block

	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:37:in `log_yield'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in `check_database_errors'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/dataset/actions.rb:778:in `execute'
... 13 levels...
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:323:in `_transaction'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:285:in `block in transaction'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:278:in `transaction'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `checked_transaction'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1017:in `block in destroy'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1713:in `checked_save_failure'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1017:in `destroy'
	from (irb):48
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.2/lib/rails/commands/console.rb:47:in `start'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.2/lib/rails/commands/console.rb:8:in `start'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.2/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'irb(main):049:0>
```

which does not look very useful :(. I got that error from the PostgreSQL logs.

**Comment by juanignaciosl** [comment]
Oh, it looks like it doesn't come from the application. Since it's a free user _shouldn't_ be related with my last changes then but with the change, months ago, that linked geocodings with data imports. Just what you said in the issue, then. Nevertheless, just cascading is not a valid solution if we want to move geocodings to organization owner when a user is deleted.
