### ISSUE TITLE
Twitter import seemed to fail w/o exception but throwing a backtrace

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3459]
See import ID: `9bdbc780-8ae3-478a-bec3-1f65d8ccf07c`

This is the backtrace:
```
services/importer/lib/importer/runner.rb:241:in `block (2 levels) in single_resource_import'
services/importer/lib/importer/importer_stats.rb:33:in `block in timing'
shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'
services/importer/lib/importer/importer_stats.rb:31:in `timing'
services/importer/lib/importer/runner.rb:239:in `block in single_resource_import'
services/importer/lib/importer/importer_stats.rb:33:in `block in timing'
shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'
services/importer/lib/importer/importer_stats.rb:31:in `timing'
services/importer/lib/importer/runner.rb:230:in `single_resource_import'
services/importer/lib/importer/runner.rb:95:in `run_import'
services/importer/lib/importer/runner.rb:88:in `block in run'
services/importer/lib/importer/importer_stats.rb:33:in `block in timing'
shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'
services/importer/lib/importer/importer_stats.rb:31:in `timing'
services/importer/lib/importer/runner.rb:87:in `run'
app/connectors/importer.rb:39:in `run'
app/models/data_import.rb:588:in `new_importer'
app/models/data_import.rb:331:in `dispatch'
app/models/data_import.rb:158:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

**Comment by Kartones** [comment]
This is a `raise CartoDB::Importer2::FileTooBigError` error, user is already properly notified, was just the import log the one lacking better context. New format:

```
2015-06-18 14:18:57 UTC: Starting import for /tmp/imports/20150618-5199-8uegii/twitter_xxxx.csv
2015-06-18 14:18:57 UTC: Errored importing data:
2015-06-18 14:18:57 UTC: CartoDB::Importer2::FileTooBigError: /tmp/imports/20150618-5199-8uegii/twitter_xxxxxx.csv
2015-06-18 14:18:57 UTC: ----------------------------------------------------
2015-06-18 14:18:57 UTC: ["/home/kartones/src/cartodb/services/importer/lib/importer/runner.rb:245:in `block in single_resource_import'"
```
