### ISSUE TITLE
Error occurring when running create_importer_schema

### ISSUE THREAD

**Issue by bencolonna** [CartoDB/cartodb#365]
An error keeps on occurring when I am trying to run bundle exec rake cartodb:db:create_importer_schema.  I don't think that it is an issue with my installation.

```
$ bundle exec rake cartodb:db:create_importer_schema --trace
rake aborted!
Don't know how to build task 'cartodb:db:create_importer_schema'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/task_manager.rb:49:in `[]'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:115:in `invoke_task'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.2-p320@cartodb/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
