### ISSUE TITLE
Table merging two+ tables should merge two twitters.csv test fails with Ruby 2

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3695]
`$ bundle exec rspec ./spec/models/table_spec.rb:1714`

```
  1) Table merging two+ tables should merge two twitters.csv
     Failure/Error: table.append_to_table(:from_table => append_this)
     ArgumentError:
       invalid number of elements (4 for 1..2)
     # ./app/models/table.rb:313:in `[]'
     # ./app/models/table.rb:313:in `append_to_table'
     # ./spec/models/table_spec.rb:1732:in `block (3 levels) in <top (required)>'
```

This is the only failing test with Ruby 2.1.3 at the moment (and the only weird behaviour after a week using Ruby 2.1.3 in development).

cc @Kartones @rafatower @javisantana @zenitraM

**Comment by alonsogarciapablo** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
