### ISSUE TITLE
167K rows file import fails sometimes because of lat/long guessing

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3740]
While debugging another issue with a file of 167K rows, we detected that this import is failing often because of a statement timeout while trying to populate the_geom column from lat long columns.

````
2015-05-22 12:32:32 UTC: Errored importing data from /tmp/imports/20150522-17213-1of2wz4/stocktonca_realproperty.csv: 
2015-05-22 12:32:32 UTC: Sequel::DatabaseError: PG::Error: ERROR: canceling statement due to statement timeout 
2015-05-22 12:32:32 UTC: ---------------------------------------------------- 
2015-05-22 12:32:32 UTC: ["/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in `check_database_errors'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/g
ems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'",
 "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/query_batcher.rb:110:in `process_batched_query'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/query_batcher.rb:93:in `process'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/query_batcher.rb:84:in `execute'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/table-geocoder/lib/internal-geocoder/latitude_longitude.rb:40:in `geocode'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/georeferencer.rb:284:in `populate_the_geom_from_latlon'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/georeferencer.rb:82:in `create_the_geom_from_latlon'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/georeferencer.rb:47:in `run'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/loader.rb:96:in `post_ogr2ogr_tasks'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/loader.rb:66:in `block (2 levels) in run'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:31:in `timing'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/loader.rb:65:in `block in run'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'",
 "/home/ubuntu/www/production.cartodb.
com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/loader.rb:50:in `run'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:226:in `file_based_loader_run'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:181:in `import'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:259:in `block (3 levels) in single_resource_import'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:252:in `each'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:252:in `block (2 levels) in single_resource_import'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:31:in `timing'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:251:in `block in single_resource_import'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:31:in `timing'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:230:in `single_resource_import'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:95:in `run_import'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:88:in `block in run'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", 
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/importer_stats.rb:31:in `timing'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/services/importer/lib/importer/runner.rb:87:in `run'", 
"/home/ubuntu/www/production.cartodb.com/releases/20150522104852/app/connectors/importer.rb:39:in `run'", 
`````

cc @juanignaciosl

**Comment by javisantana** [comment]
I'd consider this a normal behavior, we are working on this to improve it in two ways:

1) improveing the cartodbfication https://github.com/CartoDB/cartodb-postgresql/pull/78
2) moving that logic to gdal

**Comment by juanignaciosl** [comment]
If we can't fix the error itself we might also not fail an import because of guessing errors.

**Comment by javisantana** [comment]
it's not being reported to the user?

**Comment by saleiva** [comment]
I propose we import the file anyway so the user can geocode it manually (but this scenario would be pretty negative for our magical onboarding :))

**Comment by rafatower** [comment]
ogr2ogr2 timeouts are the last one of a long list to get fixed yet: https://github.com/CartoDB/cartodb/issues/5009

**Comment by iriberri** [comment]
Closing because of duplication.

**Comment by rafatower** [comment]
@jgoizueta just a bit more info about timeouts, in case you find it useful. There's also something I forgot to tell you about timeouts.

The workaround is in some cases the `QueryBatcher`, that I'd say was a mistake at the time: https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/query_batcher.rb
