### ISSUE TITLE
CartoDB::Importer2::LoadError

### ISSUE THREAD

**Issue by zhenyanghua** [CartoDB/cartodb#3822]
Only when I upload zipped shapefiles, it throws this error:
my gdal version is 1.11.0

16:21:27 web.1    | 2015-05-27 20:21:11 UTC: ogr2ogr call:      OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8  /usr/local/bin/ogr2ogr -f PostgreSQL  PG:"host=localhost port=5432 user=development_cartodb_user_99fcd49c-fa81-4da0-b4bb-acf51cd9ba00 dbname=cartodb_dev_user_99fcd49c-fa81-4da0-b4bb-acf51cd9ba00_db password=563a0c571d52566909f98e28f4d5c947621a7007development_cartodb_user_99fcd49c-fa81-4da0-b4bb-acf51cd9ba00"  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20150527-65108-kpgbhe/ne_110m_admin_0_countries.version.csv  -nln cdb_importer.importer_ea2b67a804ad11e5b167000c2903cc0e -nlt PROMOTE_TO_MULTI
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: ogr2ogr output:  
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: ogr2ogr exit code: 0
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: Georeferencing...
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: Disabling autovacuum for "cdb_importer"."importer_ea2b67a804ad11e5b167000c2903cc0e"
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: Creating the_geom column
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: Enabling autovacuum for "cdb_importer"."importer_ea2b67a804ad11e5b167000c2903cc0e"
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: Georeferenced
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: Finished importing data from /tmp/imports/20150527-65108-kpgbhe/ne_110m_admin_0_countries.version.csv
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: Filename: /tmp/imports/20150527-65108-kpgbhe/ne_110m_admin_0_countries.shp Size (bytes): 179828
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: Importing data from /tmp/imports/20150527-65108-kpgbhe/ne_110m_admin_0_countries.shp
16:21:27 web.1    | 2015-05-27 20:21:11 UTC: File-based import load
16:21:27 web.1    | 2015-05-27 20:21:19 UTC: Detected encoding WIN1252
16:21:27 web.1    | 2015-05-27 20:21:19 UTC: Using database connection with {:adapter=>"postgres", :encoding=>"unicode", :host=>"localhost", :port=>5432, :database=>"cartodb_dev_user_99fcd49c-fa81-4da0-b4bb-acf51cd9ba00_db", :username=>"postgres", :conn_validator_timeout=>900, :user=>"development_cartodb_user_99fcd49c-fa81-4da0-b4bb-acf51cd9ba00"}
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: ogr2ogr call:      OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=WIN1252 SHAPE_ENCODING=WIN1252 /usr/local/bin/ogr2ogr -f PostgreSQL  PG:"host=localhost port=5432 user=development_cartodb_user_99fcd49c-fa81-4da0-b4bb-acf51cd9ba00 dbname=cartodb_dev_user_99fcd49c-fa81-4da0-b4bb-acf51cd9ba00_db password=563a0c571d52566909f98e28f4d5c947621a7007development_cartodb_user_99fcd49c-fa81-4da0-b4bb-acf51cd9ba00" -t_srs EPSG:4326  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20150527-65108-kpgbhe/ne_110m_admin_0_countries.shp  -nln cdb_importer.importer_ea2b67a804ad11e5b167000c2903cc0e -nlt PROMOTE_TO_MULTI
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: ogr2ogr output:    FAILED: Layer cdb_importer.importer_ea2b67a804ad11e5b167000c2903cc0e already exists, and -append not specified.
16:21:27 web.1    |         Consider using -append, or -overwrite.
16:21:27 web.1    | ERROR 1: Terminating translation prematurely after failed
16:21:27 web.1    | translation of layer ne_110m_admin_0_countries (use -skipfailures to skip errors)
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: ogr2ogr exit code: 256
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: Errored importing data from /tmp/imports/20150527-65108-kpgbhe/ne_110m_admin_0_countries.shp:
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: CartoDB::Importer2::LoadError: #CartoDB::Log:0x000000099a4b70
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: ----------------------------------------------------
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: ["/home/hua/cdb/cartodb/services/importer/lib/importer/loader.rb:258:in `run_ogr2ogr''", "/home/hua/cdb/cartodb/services/importer/lib/importer/loader.rb:62:in`block (2 levels) in run''", "/home/hua/cdb/cartodb/services/importer/lib/importer/importer_stats.rb:56:in `timing''", "/home/hua/cdb/cartodb/services/importer/lib/importer/loader.rb:61:in`block in run''", "/home/hua/cdb/cartodb/services/importer/lib/importer/importer_stats.rb:56:in `timing''", "/home/hua/cdb/cartodb/services/importer/lib/importer/loader.rb:50:in`run''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:226:in `file_based_loader_run''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:181:in`import''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:259:in `block (3 levels) in single_resource_import''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:252:in`each''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:252:in `block (2 levels) in single_resource_import''", "/home/hua/cdb/cartodb/services/importer/lib/importer/importer_stats.rb:56:in`timing''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:251:in `block in single_resource_import''", "/home/hua/cdb/cartodb/services/importer/lib/importer/importer_stats.rb:56:in`timing''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:230:in `single_resource_import''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:95:in`run_import''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:88:in `block in run''", "/home/hua/cdb/cartodb/services/importer/lib/importer/importer_stats.rb:56:in`timing''", "/home/hua/cdb/cartodb/services/importer/lib/importer/runner.rb:87:in `run''", "/home/hua/cdb/cartodb/app/connectors/importer.rb:39:in`run''", "/home/hua/cdb/cartodb/app/models/data_import.rb:599:in `new_importer''", "/home/hua/cdb/cartodb/app/models/data_import.rb:342:in`dispatch''", "/home/hua/cdb/cartodb/app/models/data_import.rb:159:in `run_import!''", "/home/hua/cdb/cartodb/lib/resque/importer_jobs.rb:9:in`block in perform''", "/home/hua/cdb/cartodb/lib/resque/base_job.rb:21:in `call''", "/home/hua/cdb/cartodb/lib/resque/base_job.rb:21:in`run_action''", "/home/hua/cdb/cartodb/lib/resque/importer_jobs.rb:9:in `perform''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/job.rb:240:in`block (3 levels) in perform''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/job.rb:239:in`block (2 levels) in perform''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/job.rb:247:in `call''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/job.rb:247:in`perform''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/worker.rb:189:in`block in work''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/worker.rb:166:in`work''", "/home/hua/.rvm/gems/ruby-1.9.3-p551@cartodb/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:205:in`call''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:200:in`each''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:200:in `execute''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:158:in`block in invoke_with_call_chain''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:151:in`invoke_with_call_chain''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/task.rb:144:in `invoke''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:116:in`invoke_task''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:94:in`each''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:133:in`standard_exception_handling''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:88:in `top_level''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:66:in`block in run''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rake/application.rb:63:in`run''", "/home/hua/.rvm/rubies/ruby-1.9.3-p551/bin/rake:32:in `<main>''"]
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: ----------------------------------------------------
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: Proceeding to register
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: Before renaming from importer_ea2b67a804ad11e5b167000c2903cc0e to ne_110m_admin_0_countries.version
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: Before moving schema ''ne_110m_admin_0_countries_version'' from cdb_importer to public
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: Before persisting metadata ''ne_110m_admin_0_countries_version'' data_import_id: 4aedf08c-673b-4493-9b5c-47156fa2b006
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: Table ''ne_110m_admin_0_countries_version'' registered
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: After importer run
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: After dispatch
16:21:27 web.1    | 2015-05-27 20:21:27 UTC: Import finished

**Comment by alonsogarciapablo** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
