### ISSUE TITLE
"Column" column provokes georeferenciation error

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4049]
**Steps**
(This can be done in an easier way, but this was my use case)
* In any table, construct an address form a SQL query:
`SELECT 'Eloy Gonzalo, 27'  FROM tablename`
* Create table from dataset. The column is created with name "column"
* Try to geocode by street address - geocoding error.

**Error**
```
body.message.error_info.error	ERROR: syntax error at or near "column"
LINE 1: ...im(both from regexp_replace(regexp_replace(concat(column), E...
^
````

**Trace**

````
["/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:272:in `block in copy_table'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:271:in `copy_table'", "/home/ubuntu/www/production.cartodb.com/releases/20150612185648/services/table-geocoder/lib/table_geocoder.rb:58:in `generate_csv'", "/home/ubuntu/www/production.cartodb.com/releases/20150612185648/services/table-geocoder/lib/table_geocoder.rb:47:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150612185648/app/models/geocoding.rb:132:in `run_geocoding!'", "/home/ubuntu/www/production.cartodb.com/releases/20150612185648/app/models/geocoding.rb:122:in `run!'", "/home/ubuntu/www/production.cartodb.com/releases/20150612185648/lib/resque/geocoder_jobs.rb:9:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/20150612185648/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/20150612185648/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/20150612185648/lib/resque/geocoder_jobs.rb:9:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:19:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:19:in `<main>'"]
````

**More**
Would it make sense to use a non-reserved word as alias when a user runs a query and it doesn't provide a name for the resulting columns? This is affecting geocoding at the moment but calling it "?column?" => "column" by default  could provoke other issues in the platform.

**Comment by rafatower** [comment]
Relevant trace:
```
gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'
gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'
gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'
gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'
gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'
gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:272:in `block in copy_table'
gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'
gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:271:in `copy_table'
services/table-geocoder/lib/table_geocoder.rb:58:in `generate_csv'
services/table-geocoder/lib/table_geocoder.rb:47:in `run'
app/models/geocoding.rb:132:in `run_geocoding!'
app/models/geocoding.rb:122:in `run!'
lib/resque/geocoder_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/geocoder_jobs.rb:9:in `perform'
```
It can also be reproduced with this query:
```sql
SELECT 'Eloy Gonzalo, 27';
```

**Comment by rafatower** [comment]
There are a few issues with this ticket:
- The table got imported with a reserved column name `column`
- the column `column` got imported with `unknown` type.
- The hires geocoder tried to geocode using the `unknown`. This was already solved at UI level.

**Comment by rafatower** [comment]
Fixed. As a side note, this is the correct way of selecting with column name and type:
```sql
SELECT text 'ola k ase' as address, cartodb_id FROM table;
```

but now the code is prepared to "sanitize" both column names and types :)
