### ISSUE TITLE
Error deleting org because of undefined method `acl' for nil:NilClass

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4092]
@zenitraM found this issue when he was testing #3881.

When he tried to delete an organization it failed (user schemas were there afterwards), and he found this trace:

```
Started DELETE "/superadmin/organizations/04b4cbb3-d22f-4ead-a13d-cdb0350253c4" for 198.211.121.239 at 2015-06-17 10:35:40 +0000
Processing by Superadmin::OrganizationsController#destroy as JSON
  Parameters: {"id"=>"04b4cbb3-d22f-4ead-a13d-cdb0350253c4"}
[CartoDB Log] === Error destroying user juanimedio. undefined method `acl' for nil:NilClass
["/home/ubuntu/www/production.cartodb.com/releases/20150616165000/app/models/visualization/member.rb:340:in `organization?'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_map.rb:121:in `get_template_data'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_map.rb:59:in `update'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/app/models/visualization/member.rb:762:in `update_named_map'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/app/models/visualization/member.rb:750:in `save_named_map'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/app/models/visualization/member.rb:427:in `invalidate_cache'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/app/models/map.rb:97:in `block in invalidate_vizjson_varnish_cache'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/app/models/map.rb:96:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/app/models/map.rb:96:in `invalidate_vizjson_varnish_cache'", "/home/ubuntu/www/production.cartodb.com/releases/20150616165000/app/models/map.rb:69:in `before_destroy'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1501:in `block in _destroy'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in `around_destroy'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1499:in `_destroy'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1017:in `block (2 levels) in destroy'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `block in checked_transaction'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:283:in `block in tr
```

**Comment by juanignaciosl** [comment]
Fixed in PR #3881 branch
