### ISSUE TITLE
New AR models won't work until restarting Rails after metadata failure

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#4362]
```
ActiveRecord::StatementInvalid (PG::Error: connection not open
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"data_imports"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum
):
  app/services/carto/data_imports_service.rb:14:in `process_recent_user_imports'
  app/controllers/carto/api/imports_controller.rb:10:in `index'
  app/controllers/application_controller.rb:74:in `wrap_in_profiler'
```

It seems ActiveRecord cannot handle gracefully a metadata connection closed - it won't work until restarting Rails

**Comment by zenitraM** [comment]
monkeypatched fix at #4390
