### ISSUE TITLE
Import failed and error trace doesn't seem complete

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4815]
Error code: 99999
stats: "[{"type":".csv","size":183093,"file_rows":null,"imported_rows":null,"error_percent":null,"fallback_executed":null}]",

````
2015-07-31 00:22:29 UTC: Running on server xxx with PID: xxx 
2015-07-31 00:22:29 UTC: new_importer() 
2015-07-31 00:22:29 UTC: Fetching datasource public_url metadata for item id xxx
2015-07-31 00:22:29 UTC: File will be downloaded from xxx
2015-07-31 00:22:29 UTC: Before importer run 
2015-07-31 00:22:29 UTC: Starting import for /tmp/imports/xxx.csv 
2015-07-31 00:22:29 UTC: Unpacking /tmp/imports/xxx.csv 
2015-07-31 00:22:29 UTC: Filename: /tmp/imports/xxx.csv Size (bytes): 183093 
2015-07-31 00:22:29 UTC: Importing data from /tmp/imports/xxx.csv 
2015-07-31 00:22:29 UTC: File-based import load 
2015-07-31 00:22:29 UTC: Detected encoding ISO-8859-1 
2015-07-31 00:22:29 UTC: Using database connection with {:adapter=>"postgres", :encoding=>"unicode", :host=>"10.0.128.17", :database=>"cartodb_user_xxx", :username=>"postgres", :port=>5432, :connect_timeout=>2.5, :user=>"cartodb_userxxx 
2015-07-31 00:22:32 UTC: ogr2ogr call: OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=ISO-8859-1 /usr/bin/ogr2ogr2 -f PostgreSQL -oo AUTODETECT_TYPE=YES -oo QUOTED_FIELDS_AS_STRING=NO PG:"host=xxx port=xxx user=xxx
2015-07-31 00:22:32 UTC: ogr2ogr output: Warning 1: Field 'Latitude' already exists. Renaming it as 'latitude2' Warning 1: Field 'Longitude' already exists. Renaming it as 'longitude2' Warning 1: Field 'Latitude' already exists. Renaming it as 'latitude3' Warning 1: Field 
2015-07-31 00:22:32 UTC: ogr2ogr exit code: 0 
2015-07-31 00:22:32 UTC: Georeferencing... 2015-07-31 00:22:32 UTC: Disabling autovacuum for "cdb_importer"."importer_xxx" 
2015-07-31 00:22:32 UTC: Errored importing data from /tmp/imports/xxx.csv: 
2015-07-31 00:22:32 UTC: Sequel::DatabaseError: PG::Error: ERROR: relation "cdb_importer.importer_xxx" does not exist 
2015-07-31 00:22:32 UTC: ---------------------------------------------------- 
2015-07-31 00:22:32 UTC: ["/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in `check_database_errors'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:79:in `execute_dui'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:72:in `execute_ddl'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:135:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/georeferencer.rb:61:in `disable_autovacuum'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/georeferencer.rb:42:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/loader.rb:102:in `post_ogr2ogr_tasks'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/loader.rb:66:in `block (2 levels) in run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/loader.rb:65:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/loader.rb:51:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:225:in `file_based_loader_run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:180:in `import'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:328:in `execute_import'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:259:in `block (3 levels) in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:252:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:252:in `each_with_index'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:252:in `block (2 levels) in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:251:in `block in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:229:in `single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:98:in `run_import'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:91:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/importer_stats.rb:31:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:90:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/connectors/importer.rb:38:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/models/data_import.rb:617:in `new_importer'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/models/data_import.rb:350:in `dispatch'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/models/data_import.rb:161:in `run_import!'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/lib/resque/importer_jobs.rb:9:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/lib/resque/importer_jobs.rb:9:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:19:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:19:in `<main>'"] 
2015-07-31 00:22:32 UTC: ---------------------------------------------------- 
2015-07-31 00:22:32 UTC: Proceeding to register 
2015-07-31 00:22:32 UTC: After importer run 
2015-07-31 00:22:32 UTC: After dispatch 
2015-07-31 00:22:32 UTC: ERROR! 
===LOG END==="

````

**Comment by iriberri** [comment]
cc @Kartones @javisantana

**Comment by javisantana** [comment]
what information are you missing?

**Comment by Kartones** [comment]
It failed after georeferencing (or maybe inside it, I'd have to check the code) but before registering. The log is not clear where.

**Comment by iriberri** [comment]
I would expect a clear error as the logs shows in perhaps +90% of the cases. If it's not possible because this is exploding somewhere in an ugly way no problem, but I wonder if this could be telling us that we're missing something somewhere.

**Comment by Kartones** [comment]
there's something I don't like inside the error trace:
```
"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:72:in `execute_ddl'",
```

Yes please, try to get the file and ask the user if possible to do a simple import to make sure he can import ok and doesn't has anything messed up with the DDL triggers

**Comment by iriberri** [comment]
The user can import other files according to the logs
