### ISSUE TITLE
Resque "undefined method '-'" when geocoding any table

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#4846]
When geocoding any table, resque spits out this error:

```
exception:  undefined method `-' for nil:NilClass
/home/ubuntu/www/production.cartodb.com/current/app/models/user.rb:978:in `remaining_geocoding_quota'
 /home/ubuntu/www/production.cartodb.com/current/app/models/geocoding.rb:203:in `remaining_quota'
 /home/ubuntu/www/production.cartodb.com/current/app/models/geocoding.rb:265:in `metrics_payload'
 /home/ubuntu/www/production.cartodb.com/current/app/models/geocoding.rb:165:in `report'
 /home/ubuntu/www/production.cartodb.com/current/app/models/geocoding.rb:329:in `handle_geocoding_success'
 /home/ubuntu/www/production.cartodb.com/current/app/models/geocoding.rb:159:in `run_geocoding!'
 /home/ubuntu/www/production.cartodb.com/current/app/models/geocoding.rb:132:in `run!'
 /home/ubuntu/www/production.cartodb.com/current/lib/resque/geocoder_jobs.rb:9:in `block in perform'
 /home/ubuntu/www/production.cartodb.com/current/lib/resque/base_job.rb:21:in `call'
 /home/ubuntu/www/production.cartodb.com/current/lib/resque/base_job.rb:21:in `run_action'
 /home/ubuntu/www/production.cartodb.com/current/lib/resque/geocoder_jobs.rb:9:in `perform'
 /var/lib/gems/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'
 /var/lib/gems/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'
 /var/lib/gems/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'
 /var/lib/gems/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'
 /var/lib/gems/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'
 /var/lib/gems/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
 /var/lib/gems/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
...
```

Although the geocoding continues successfully, this should be fixed

**Comment by gfiorav** [comment]
This issue is caused by the lack of `to_i' at the end of `geocoding_quota` in file https://github.com/CartoDB/cartodb/blame/master/app/models/user.rb#L977.

I'm fixing this, creating a spec test for it and submitting a PR.

**Comment by gfiorav** [comment]
Solving in PR #4848
