### ISSUE TITLE
In Ruby 2.2.2 you get undefined method `name` for nil:NilClass when try to delete object from array

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5000]
If you execute the test:

```RAILS_ENV=test bundle exec rspec spec/requests/carto/api/imports_controller_spec.rb -e "returns oauth_valid false for not valid tokens and deletes them"```

you are going to get fails in the tests but the root cause is:

`undefined method `name` for nil:NilClass` in

```/home/ubuntu/www/production.cartodb.com/current/app/services/carto/data_imports_service.rb:128:in `delete_oauth'
 /home/ubuntu/www/production.cartodb.com/current/app/services/carto/data_imports_service.rb:59:in `validate_synchronization_oauth'
 /home/ubuntu/www/production.cartodb.com/current/app/controllers/carto/api/imports_controller.rb:30:in `service_token_valid?’```

**Comment by ethervoid** [comment]
The problem is that the version prior to 3.2.22 don't support ruby 2.2.X so we need to upgrade to it.
