### ISSUE TITLE
PG::Error: ERROR:  relation already exists while geocoding

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5193]
S/B: 6360351
```
2015-08-21 17:02:42 UTC: Running geocoding job on server que02.useb.cartodb.net with PID: 19223
2015-08-21 17:02:42 UTC: TableGeocoderFactory.get()
2015-08-21 17:02:42 UTC: params: {:original_formatter=>"{postcode}", :formatter=>"postcode", :remote_id=>nil, :countries=>"'United States'", :regions=>nil, :geometry_type=>"point", :kind=>"postalcode", :max_rows=>50000, :country_column=>nil, :region_column=>nil}
2015-08-21 17:02:42 UTC: geocoder_class = CartoDB::InternalGeocoder::Geocoder
2015-08-21 17:02:43 UTC: run_geocoding!()
2015-08-21 17:02:43 UTC: run()
2015-08-21 17:02:43 UTC: download_results()
2015-08-21 17:02:43 UTC: Saving results to /tmp/d20150821-19223-ervpcj/public.internal_geocoding_1440176562_results.csv
2015-08-21 17:02:43 UTC: Saving results to /tmp/d20150821-19223-ervpcj/public.internal_geocoding_1440176562_results.csv
2015-08-21 17:02:44 UTC: Saving results to /tmp/d20150821-19223-ervpcj/public.internal_geocoding_1440176562_results.csv
2015-08-21 17:02:44 UTC: create_temp_table()
2015-08-21 17:02:44 UTC: load_results_to_temp_table()
2015-08-21 17:02:44 UTC: copy_results_to_table()
2015-08-21 17:02:44 UTC: Unexpected exception: PG::Error: ERROR:  relation "seq_cartodb_processed_1811360765145766324" already exists
```

and the backtrace:
```
services/importer/lib/importer/query_batcher.rb:77:in `prepare_id_column'
services/importer/lib/importer/query_batcher.rb:29:in `execute_update'
services/table-geocoder/lib/internal_geocoder.rb:106:in `copy_results_to_table'
services/table-geocoder/lib/internal_geocoder.rb:50:in `run'
app/models/geocoding.rb:149:in `run_geocoding!'
app/models/geocoding.rb:132:in `run!'
lib/resque/geocoder_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/geocoder_jobs.rb:9:in `perform'
```

**Comment by rafatower** [comment]
@Kartones AFAIK the name of the temporary sequence is computed materialistically from the table name (or similiar) so I think for some reason we're dropping the table but not the sequence in an earlier query batch operation on the same table. Any ideas?

**Comment by Kartones** [comment]
uhm, so the query batcher misses the existance of the column and fails trying to add it again, no?

the name is calculated excusively using table name, yes `"cartodb_processed_#{qualified_table_name.hash.abs}"`... but both table and sequence are dropped on the same call
(`remove_id_column` at `QueryBatcher`), so is weird.

Maybe we have a non-fatal PG error dropping the sequence (but not dropping the table) and the next call hits it? Maybe would be worth to drop first the sequence and then the column?

**Comment by rafatower** [comment]
No, no sorry, the problem is that the sequence already exists (though PG reports it as if it were a table):
```
Unexpected exception: PG::Error: ERROR:  relation "seq_cartodb_processed_1811360765145766324" already exists
```

**Comment by rafatower** [comment]
fixed in the extension: https://github.com/CartoDB/cartodb-postgresql/pull/173
