### ISSUE TITLE
raster import failure

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5274]
See data import id `16691887-f54a-459b-8cb9-95ec808ce911`

Beautified trace from logs:

```
2015-08-26 11:09:12 UTC: CartoDB::Importer2::TiffToSqlConversionError: (pid 16624 exit 1)
Creating output file that is 103596P x 95800L.
Processing input file /tmp/imports/20150826-16327-15nk1nw/some_file.tif.
Using internal nodata values (e.g. 0) for image /tmp/imports/201
2015-08-26 11:09:12 UTC: ----------------------------------------------------
services/importer/lib/importer/raster2pgsql.rb:80:in `reproject_raster'
services/importer/lib/importer/raster2pgsql.rb:32:in `run'
services/importer/lib/importer/tiff_loader.rb:23:in `run'
services/importer/lib/importer/runner.rb:222:in `file_based_loader_run'
services/importer/lib/importer/runner.rb:177:in `import'
services/importer/lib/importer/runner.rb:325:in `execute_import'
services/importer/lib/importer/runner.rb:256:in `block (3 levels) in single_resource_import'
services/importer/lib/importer/runner.rb:249:in `each'
services/importer/lib/importer/runner.rb:249:in `each_with_index'
services/importer/lib/importer/runner.rb:249:in `block (2 levels) in single_resource_import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:248:in `block in single_resource_import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:226:in `single_resource_import'
services/importer/lib/importer/runner.rb:95:in `run_import'
services/importer/lib/importer/runner.rb:88:in `block in run'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:87:in `run'
app/connectors/importer.rb:39:in `run'
app/models/data_import.rb:618:in `new_importer'
app/models/data_import.rb:354:in `dispatch'
app/models/data_import.rb:163:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
2015-08-26 11:09:12 UTC: ----------------------------------------------------
2015-08-26 11:09:13 UTC: Proceeding to register
2015-08-26 11:09:13 UTC: After importer run
2015-08-26 11:09:13 UTC: After dispatch
2015-08-26 11:09:13 UTC: ERROR!
```

cc/  @iriberri

**Comment by alonsogarciapablo** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
