### ISSUE TITLE
Questions and suggestions on new instruction page

### ISSUE THREAD

**Issue by raquel-ucl** [CartoDB/cartodb#5421]
Hi,

I was trying to install CartoDB on a brand new Ubuntu 12.04.5 Desktop 64-bit, and thought I'd list somewhere a few things that came up while following the new CartoDB instructions list. Maybe they help someone else who runs into problems and contribute to improve the existing instructions.
- [x] In `pg_hba.conf` all references to peer should be changed to trust, otherwise I get `createuser: could not connect to database postgres: FATAL:  Peer authentication failed for user "postgres"
  ` errors. In the instructions in appears as it only two lines need to be modified, but in fact is three, including `local   all             postgres                                trust`
- [x] Before the `createuser` commands for Postgres, the database needs to be started with `sudo service postgresql restart` for the pg_hba.conf changes to take effect. Otherwise this error is displayed `createuser: could not connect to database postgres: FATAL:  Peer authentication failed for user "postgres"`
- [x] The `installcheck` on the instructions happens too early - almost all tests fail because postgis hasn't been installed:
  `The following tests are failing:
    test_quota_for_each_user
    test_cdb_tablemetadatatouch
    test_cdb_tablemetadatatouch_fails_for_unexistent_table
    test_cdb_tablemetadatatouch_fails_from_user_without_permission
    test_cdb_column_names
    test_cdb_column_type
    test_cdb_querytables_schema_and_table_names_with_dots
    test_cdb_querytables_table_name_with_dots
    test_cdb_querytables_happy_cases`
  
  Some of them break because `ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/postgis.control": No such file or directory`. Others fail because raster, raster_2, o_2_raster, raster_overviews, etc. don't exists.
- [ ] If I run  `installcheck` after installing postgis, I get this error:
  `> Executing query 'SELECT count(*) FROM cdb_testmember_1.foo;' as cdb_testmember_2
  ERROR:  permission denied for schema cdb_testmember_1
  LINE 1: SELECT count(*) FROM cdb_testmember_1.foo;
                                                   ^
  FAILED TO EXECUTE QUERY: SELECT count(*) FROM cdb_testmember_1.foo;`
  
  And this fun one, which might be expected: `ERROR:  relation "unexistent_example" does not exist
  LINE 1: SELECT CDB_TableMetadataTouch('unexistent_example');
                                    ^
  FAILED TO EXECUTE QUERY: SELECT CDB_TableMetadataTouch('unexistent_example');`
  
  And at the end: `The following tests are failing:
    test_member_2_cannot_read_without_permission`
- [x] When trying to install npm, I get:
  
  ```
  Reading package lists... Done
  Building dependency tree       
  Reading state information... Done
  Some packages could not be installed. This may mean that you have
  requested an impossible situation or if you are using the unstable
  distribution that some required packages have not yet been created
  or been moved out of Incoming.
  The following information may help to resolve the situation:
  
  The following packages have unmet dependencies:
  npm : Depends: nodejs but it is not going to be installed
       Depends: nodejs-dev
       Depends: node-request but it is not going to be installed
       Depends: node-mkdirp but it is not going to be installed
       Depends: node-minimatch but it is not going to be installed
       Depends: node-semver but it is not going to be installed
       Depends: node-ini but it is not going to be installed
       Depends: node-graceful-fs but it is not going to be installed
       Depends: node-abbrev but it is not going to be installed
       Depends: node-nopt but it is not going to be installed
       Depends: node-fstream but it is not going to be installed
       Depends: node-rimraf but it is not going to be installed
       Depends: node-tar but it is not going to be installed
       Depends: node-which but it is not going to be installed
  E: Unable to correct problems, you have held broken packages.
  ```
  
  Not sure if it's enough just by installing `nodejs`, it seems to install npm as well by default:
  
  ```
  $ npm -v
  1.4.3
  ```
  
  Is that the correct version? Should I install it some other way? It seems to of well when running `npm install` for the SQL API.
- [x]  `npm install` works for the SQL API, but for Windshaft it shows some error messages: 
  
  ```
  Package cairo was not found in the pkg-config search path.
  Perhaps you should add the directory containing `cairo.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'cairo' found
  gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0.
  gyp ERR! configure error 
  gyp ERR! stack Error: `gyp` failed with exit code: 1
  gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
  gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
  gyp ERR! System Linux 3.13.0-32-generic
  gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
  gyp ERR! cwd /home/raquel/Windshaft-cartodb/node_modules/windshaft/node_modules/canvas
  gyp ERR! node -v v0.10.26
  gyp ERR! node-gyp -v v0.12.2
  gyp ERR! not ok 
  ```
  
  Can be solved by installing `sudo apt-get install libpango1.0-dev` and running `npm install` again.
- [x] When I run `sudo gem install bundler` I get an error because the gem command is not found. After installing ruby with ruby-install, it's also needed to add this to the PATH:
  
  `export PATH=$PATH:/opt/rubies/ruby-1.9.3-p547/bin`
  
  `sudo gem install bundler` will continue causing the same trouble, but it can be run without sudoing like this:
  
  `gem install bundler`
- [x] Pip needs installing as well. For example
  
  ```
  sudo wget  -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
  sudo python /tmp/get-pip.py 
  ```
- [x] Pip fails when installing gdal
  
  ```
  Running setup.py install for gdal
  Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3LXqYw/gdal/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Bbnnox-record/install-record.txt --single-version-externally-managed --compile:
  running install
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying gdal.py -> build/lib.linux-x86_64-2.7
  copying ogr.py -> build/lib.linux-x86_64-2.7
  copying osr.py -> build/lib.linux-x86_64-2.7
  copying gdalconst.py -> build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gdalnumeric.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gdalconst.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gdal.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/ogr.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/gdal_array.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/__init__.py -> build/lib.linux-x86_64-2.7/osgeo
  copying osgeo/osr.py -> build/lib.linux-x86_64-2.7/osgeo
  running build_ext
  building 'osgeo._gdal' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/extensions
  gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I/usr/include/python2.7 -I. -I/usr/include -c extensions/gdal_wrap.cpp -o build/temp.linux-x86_64-2.7/extensions/gdal_wrap.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
  extensions/gdal_wrap.cpp:149:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3LXqYw/gdal/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Bbnnox-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3LXqYw/gdal
  /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  ```
- [x] `bundle exec ./node_modules/grunt-cli/bin/grunt --environment development` fails: 
  - It needs grunt to be in the PATH, otherwise the cdb tasks abort because `make[1]: grunt: Command not found`
  - `bundle install` is needed before the grunt command, otherwise a never ending list of missing gems starts to come up.
- [x] Change order of the rake db setup and migrate tasks, otherwise if I run db:setup, I get this error: 
  `/home/raquel/cartodb/db/schema.rb doesn't exist yet. Run "rake db:migrate" to create it then try again.`
- [x] It'd be nice to add `&& sudo apt-get update` in all `add-apt-repository` commands, otherwise it's easy to forget. I panic when I got an error because things can't be installed until I remember I haven'd updated.
- [ ] It'd be nice to have somewhere the recommended or minimum RAM to run CartoDB.
- [ ] It'd be nice to have a list of the versions of the packages that are required. For example npm's version, etc.
- [ ] The rails server and rescue daemon command appear twice both in the installation instructions and the section to run CartoDB. It's a little confusing, I think they've be better only in one place.

**Comment by javisantana** [comment]
Many thanks, It would be nice if you could send a PR with those things, the source for the manual is here: https://github.com/CartoDB/cartodb/blob/master/doc/manual/source/install.rst

**Comment by raquel-ucl** [comment]
Great! I tried from the Edit link in the instructions page, but it didn't seem to work. I'll modify and send a PR.

**Comment by raquel-ucl** [comment]
How can I generate  the html out of the rst to see if it looks alrgith?

**Comment by vhamer** [comment]
Hi @raquel-ucl - Thank you for this contribution! I will email you a moment with the CLA so we can get you squared away.

**Comment by javisantana** [comment]
@raquel-ucl sorry for the late response.

There are steps here: https://github.com/CartoDB/cartodb/blob/master/doc/manual/README.md

In any case your PR looks good, we can check if you find problems installing and running sphinx

**Comment by raquel-ucl** [comment]
Sorry it's taking a little too long. I've been on holidays and I'm waiting for someone at UCL to sign the CLA. Hopefully it'll be done early next week.

**Comment by vhamer** [comment]
Thanks for the update!

**Comment by raquel-ucl** [comment]
Sent over to you @vhamer, hope it's alright!

**Comment by raquel-ucl** [comment]
@javisantana, when I do ```make html```, it complains about no having a ```theme.conf``` file. I can't find it anywhere in the repo, should I create my own one? Or should it be in the repo?

**Comment by javisantana** [comment]
could you paste the full error trace?

**Comment by vhamer** [comment]
Hi @javisantana - Noting here that UCL has signed the CLA on Raquel's behalf. Once ready, you can merge.

**Comment by raquel-ucl** [comment]
Thanks @vhamer. 
@javisantana, here's the error message:

```
[raquel:~/workspace/mycartodb/doc/manual] corrections_to_instructions ± make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.2.3
loading pickled environment... not yet created

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)
make: *** [html] Error 1
```

**Comment by raquel-ucl** [comment]
OK, I've just figured out how to fix this. I'll include it in the PR. 

FYI:

This needs to be done: 

```pip install sphinx_rtd_theme```

And conf.py need to be changed so that it includes:

```
sphinx_rtd_theme

html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```

**Comment by drzhouq** [comment]
I found this post 2 days and 16 hours late. Can someone pull Raquel's suggestions into the installation guide? What Rquel found is exactly I experienced.

**Comment by alonsogarciapablo** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
