### ISSUE TITLE
Arcgis import issue

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5612]
S/B: 6671042

The import is failing but it is unclear the root cause. Here's a trimmed down trace:
```
...
true: Running in append mode
true: ogr2ogr output:          Warning 6: driver GeoJSON does not support open option X_POSSIBLE_NAMES
Warning 6: driver GeoJSON does not support open option Y_POSSIBLE_NAMES

true: ogr2ogr exit code:       0
true: Errored importing data from /tmp/imports/20150917-7490-1ux674k/somefile.json:
===LOG END===
true: ----------------------------------------------------
false: [backtrace]
true: ----------------------------------------------------
2015-09-17 18:45:39 UTC: Proceeding to register
2015-09-17 18:45:39 UTC: After importer run
2015-09-17 18:45:39 UTC: After dispatch
2015-09-17 18:45:39 UTC: ERROR!
===LOG END===
```

and here the relevant backtrace:
```
services/importer/lib/importer/loader.rb:319:in `check_for_import_errors'
services/importer/lib/importer/loader.rb:262:in `run_ogr2ogr'
services/importer/lib/importer/loader.rb:90:in `streamed_run_continue'
services/importer/lib/importer/runner.rb:214:in `streamed_loader_run'
services/importer/lib/importer/runner.rb:175:in `import'
services/importer/lib/importer/runner.rb:325:in `execute_import'
services/importer/lib/importer/runner.rb:256:in `block (3 levels) in single_resource_import'
services/importer/lib/importer/runner.rb:249:in `each'
services/importer/lib/importer/runner.rb:249:in `each_with_index'
services/importer/lib/importer/runner.rb:249:in `block (2 levels) in single_resource_import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:248:in `block in single_resource_import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:226:in `single_resource_import'
services/importer/lib/importer/runner.rb:95:in `run_import'
services/importer/lib/importer/runner.rb:88:in `block in run'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:87:in `run'
app/connectors/importer.rb:39:in `run'
app/models/data_import.rb:617:in `new_importer'
app/models/data_import.rb:353:in `dispatch'
app/models/data_import.rb:162:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

I'll eliminate the incorrect `[X|Y]_POSSIBLE_NAMES` options that produce the warning, but there must be something else. Note it is running in append mode. Also note the ogr2ogr generic check at the point of raising the exception fails if the ret value is != 0 or there's an `ERROR` in its output.

**Comment by rafatower** [comment]
This is the error we should be logging:
```
(rdb:1) ogr2ogr.command_output
"ERROR 1: COPY statement failed.\nERROR:  duplicate key value violates unique constraint \"importer_7d543e4e605011e5bb950242ac110001_pkey\"\nDETAIL:  Key (id)=(22) already exists.\nCONTEXT:  COPY importer_7d543e4e605011e5bb950242ac110001, line 1: \"0106000020E61000000100000001030000000100000032000000EED8D90D8AC756C01D28502FD37A3E40735DBFB879C756C0...\"\n\n"
(rdb:1) puts ogr2ogr.command_output
ERROR 1: COPY statement failed.
ERROR:  duplicate key value violates unique constraint "importer_7d543e4e605011e5bb950242ac110001_pkey"
DETAIL:  Key (id)=(22) already exists.
CONTEXT:  COPY importer_7d543e4e605011e5bb950242ac110001, line 1: "0106000020E61000000100000001030000000100000032000000EED8D90D8AC756C01D28502FD37A3E40735DBFB879C756C0..."
```
seems related to cartodbfy

**Comment by rafatower** [comment]
The duplicate key error is produced before the cartodbfycation process. So my hypothesis of failure is that this fails now because ogr2og2 builds tables with PK's on the first import and then it is not able to append.

We moved from ogr2ogr gdal v1.11 to ogr2ogr2 based on gdal trunk v2.1.X quite recently.

E.g, in the middle of the process:
```
# \d cdb_importer.importer_e7e2951e608011e5b6450242ac110001
                                                 Table "cdb_importer.importer_e7e2951e608011e5b6450242ac110001"
        Column        |            Type             |                                                 Modifiers                                                 
----------------------+-----------------------------+-----------------------------------------------------------------------------------------------------------
 objectid             | integer                     | not null default nextval('cdb_importer.importer_e7e2951e608011e5b6450242ac110001_objectid_seq'::regclass)
...
Indexes:
    "importer_e7e2951e608011e5b6450242ac110001_pkey" PRIMARY KEY, btree (objectid)
    "importer_e7e2951e608011e5b6450242ac110001_wkb_geometry_geom_idx" gist (wkb_geometry)
```

**Comment by rafatower** [comment]
Confirmed: it is a difference in behavior between ogr2ogr versions. I'll try to figure out a solution w/o resorting to using old gdal v1.11

**Comment by rafatower** [comment]
But seems like a difference in behavior with respect to `-append`:

with ogr-gdal v1.11:
```
# \d cdb_importer.importer_9acbb5ba608711e5a6ac0242ac110001 
                                                Table "cdb_importer.importer_9acbb5ba608711e5a6ac0242ac110001"
        Column        |            Type             |                                                Modifiers                                                 
----------------------+-----------------------------+----------------------------------------------------------------------------------------------------------
 ogc_fid              | integer                     | not null default nextval('cdb_importer.importer_9acbb5ba608711e5a6ac0242ac110001_ogc_fid_seq'::regclass)
 wkb_geometry         | geometry(MultiPolygon,4326) | 
...
Indexes:
    "importer_9acbb5ba608711e5a6ac0242ac110001_pkey" PRIMARY KEY, btree (ogc_fid)
    "importer_9acbb5ba608711e5a6ac0242ac110001_wkb_geometry_geom_idx" gist (wkb_geometry)
```

**Comment by rafatower** [comment]
It works with `2.0.0+svn.29247c-precise1ubuntu1` but not with `2.1.0+svn.29639-precise1`. So it is a bug introduced in `2.1.0`. I'll check if it is reported/fixed in trunk but otherwise we'll have to contact Even. cc/ @javisantana

**Comment by javisantana** [comment]
Ok, add me to the loop

**Comment by rafatower** [comment]
I went through gdal tickets and couldn't find any new related to `-append`. I tested with latest version `trunk@30648` but it also fails there.

I'll try to provide a scenario to reproduce. It is unlikely that it breaks in all cases.

**Comment by rafatower** [comment]
Here is a workaround: https://github.com/CartoDB/cartodb/compare/5612-append-mode-workaround?expand=1

but not all geometries are imported, seems like some of them are overwritten.

**Comment by rafatower** [comment]
I was wrong about the versions:
- gdal `1.11.0`: ok
- gdal `2.0.0+svn.29247c`: broken
- gdal `2.1.0+svn.29639`: broken

**Comment by rafatower** [comment]
I think I got to the root cause:
```
2015-09-23 10:32:33 UTC ERROR:  duplicate key value violates unique constraint "importer_4e8bb1de61de11e5b3130242ac110001_pkey"
2015-09-23 10:32:33 UTC DETAIL:  Key (id)=(22) already exists.
2015-09-23 10:32:33 UTC CONTEXT:  COPY importer_4e8bb1de61de11e5b3130242ac110001, line 1: "0106000020E61000000100000001030000000100000032000000EED8D90D8AC756C01D28502FD37A3E40735DBFB879C756C0..."
2015-09-23 10:32:33 UTC STATEMENT:  COPY "cdb_importer"."importer_4e8bb1de61de11e5b3130242ac110001" ("wkb_geometry", "police_district_id", "police_district_no", "police_district_desc") FROM STDIN;
```
with the same input dataset, ogr2ogr in some cases is using the sequence value and in others providing an explicit `id`.

**Comment by rafatower** [comment]
With gdal 1.11:
```
# \d cdb_importer.importer_b99cae0061df11e584a20242ac110001
                                                Table "cdb_importer.importer_b99cae0061df11e584a20242ac110001"
        Column        |            Type             |                                                Modifiers                                                 
----------------------+-----------------------------+----------------------------------------------------------------------------------------------------------
 ogc_fid              | integer                     | not null default nextval('cdb_importer.importer_b99cae0061df11e584a20242ac110001_ogc_fid_seq'::regclass)
 wkb_geometry         | geometry(MultiPolygon,4326) | 
 id                   | integer                     | 
Indexes:
    "importer_b99cae0061df11e584a20242ac110001_pkey" PRIMARY KEY, btree (ogc_fid)
    "importer_b99cae0061df11e584a20242ac110001_wkb_geometry_geom_idx" gist (wkb_geometry)
```
so it is making up its own ID as PK and that's why it did not fail. It is then safe to remove the PK and the import will be way faster.

**Comment by rafatower** [comment]
It is fixed in master. I'll keep this ticket open until I test and merge another improvement

**Comment by ztephm** [comment]
Notified S/B 6671042 that issue was fixed.

**Comment by mappingvermont** [comment]
I'm appending a 9,000,000 record .shp to a cartoDB table using ogr2ogr. My current workflow is to create the FC with the first 1,000,000 records, then append the rest 1,000,000 records at a time.

I'm running into this issue (duplicate key value violates unique constraint) near the end of my append loop. Was this fixed on the cartodb side, or do I need to upgrade my gdal/ogr2ogr version (currently GDAL 2.1.0dev). Thanks!
