### ISSUE TITLE
Can't import a file with long name and special characters

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5716]
[This file](https://github.com/juanignaciosl/test-data-repository/blob/master/many_characters_%C3%A1%C3%81%C3%B1%C3%91%C3%A7%C3%87%C3%A0%C3%80.csv) previously worked but it won't work now. It fails with "relation "many_characters_c3_a1_c3_81_c3_b1_c3_91_c3_a7_c3_87_c3_a0_c3_80" already exists" but I've double-checked it didn't exist. Table gets imported in the schema but it's not cartodbfied. This is the [error trace](https://rollbar.com/vizzuality/CartoDB/items/424/occurrences/7813142576/).

cc @rafatower 

````
PG::Error: ERROR: CDB(_CDB_Rewrite_Table:42P07:relation "many_characters_c3_a1_c3_81_c3_b1_c3_91_c3_a7_c3_87_c3_a0_c3_80" already exists): CREATE SEQUENCE public.many_characters_c3_a1_c3_81_c3_b1_c3_91_c3_a7_c3_87_c3_a0_c3_80_cartodb_id_seq
CONTEXT: SQL statement "SELECT _CDB_SQL(Format('CREATE SEQUENCE %s', destseq), '_CDB_Rewrite_Table')"
PL/pgSQL function _cdb_rewrite_table(regclass,text) line 121 at PERFORM
SQL statement "SELECT _CDB_Rewrite_Table(reloid, destschema)"
PL/pgSQL function cdb_cartodbfytable(text,regclass) line 51 at PERFORM
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in `check_database_errors'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:79:in `execute_dui'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:72:in `execute_ddl'/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:135:in `run'/home/ubuntu/www/production.cartodb.com/releases/20150923132622/app/models/table.rb:1170:in `block (2 levels) in cartodbfy'/home/ubuntu/www/production.cartodb.com/releases/20150923132622/app/models/user.rb:635:in `in_database'/home/ubuntu/www/production.cartodb.com/releases/20150923132622/app/models/table.rb:1169:in `block in cartodbfy'/home/ubuntu/www/production.cartodb.com/releases/20150923132622/lib/cartodb/stats/aggregator.rb:45:in 
```

**Comment by iriberri** [comment]
Not reproducible anymore. Now, the following behavior happens instead: https://github.com/CartoDB/cartodb/issues/5993

Since the issue was reported, we've also created a valid name generator which takes care of the length of it.
