### ISSUE TITLE
Geocoding modal won't display an error if geocoding fails

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5792]
1.- Clear `organization.geocoding_quota` for an organization.
2.- Try to geocode. It will fail with this error but modal will keep spinning:

```
** [07:52:01 2015-09-29] 19733: Running after_fork hooks with [(Job{geocodings} | Resque::GeocoderJobs | [{"job_id"=>"110ce665-a32b-46eb-b303-e14e97dc0902"}])]
NOTICE:  identifier "resque-1.25.2: Processing geocodings since 1443513121 [Resque::GeocoderJobs]" will be truncated to "resque-1.25.2: Processing geocodings since 1443513121 [Resque::"
exception:  undefined method `-' for nil:NilClass
/vagrant/app/models/user.rb:1002:in `remaining_geocoding_quota'
 /vagrant/app/models/geocoding.rb:232:in `max_geocodable_rows'
 /vagrant/app/models/geocoding.rb:87:in `table_geocoder'
 /vagrant/app/models/geocoding.rb:121:in `run!'
 /vagrant/lib/resque/geocoder_jobs.rb:9:in `block in perform'
 /vagrant/lib/resque/base_job.rb:21:in `call'
 /vagrant/lib/resque/base_job.rb:21:in `run_action'
 /vagrant/lib/resque/geocoder_jobs.rb:9:in `perform'
 /home/vagrant/.rvm/gems/ruby-2.2.2/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'
 /home/vagrant/.rvm/gems/ruby-2.2.2/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'
 /home/vagrant/.rvm/gems/ruby-2.2.2/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'
```

**Comment by xavijam** [comment]
But that geocoding task is throwing an error to the UI?

**Comment by juanignaciosl** [comment]
I saw it during debugging another issue, I'll complete this asap, just wrote down this not to forget.

**Comment by xavijam** [comment]
:+1:
