### ISSUE TITLE
Google Drive datasource imports failing with http response error

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5887]
**Steps**
* Try to import a file from the Google Drive datasource

````
2015-10-06 15:44:45 UTC: Exception: undefined method `http_response_code' for #<CartoDB::Importer2::DatasourceDownloader:0x000000076c2710> 2015-10-06 15:44:45 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/xx/app/models/data_import.rb:638:in `store_results'", "/home/ubuntu/www/production.cartodb.com/releases/xx/app/models/data_import.rb:622:in `new_importer'", "/home/ubuntu/www/production.cartodb.com/releases/xx/app/models/data_import.rb:354:in `dispatch'", "/home/ubuntu/www/production.cartodb.com/releases/xx/app/models/data_import.rb:163:in `run_import!'", "/home/ubuntu/www/production.cartodb.com/releases/xx/lib/resque/importer_jobs.rb:9:in `block in perform'", 
````

**Comment by gfiorav** [comment]
On it

**Comment by gfiorav** [comment]
Found the bug, hot fixed.

Deploying to test in staging (can't try locally due to Google and Dropbox APIs)

**Comment by iriberri** [comment]
Thank you so much! :-)
