### ISSUE TITLE
Errno::EADDRINUSE: (Test parallelization)

### ISSUE THREAD

**Issue by jesusvazquez** [CartoDB/cartodb#5909]
**spec/requests/api/imports_spec.rb**
```
Failures:

  1) Imports API raises an error if the user attempts to import tables when being over quota
     Failure/Error: serve_file(Rails.root.join('spec/support/data/ESP_adm.zip')) do |url|
     Errno::EADDRINUSE:
       Address already in use - bind(2)
     # ./spec/support/helpers.rb:30:in `new'
     # ./spec/support/helpers.rb:30:in `serve_file'
     # ./spec/requests/api/imports_spec.rb:154:in `block (2 levels) in <top (required)>'

  2) Imports API raises an error if the user attempts to import tables when being over disk quota
     Failure/Error: serve_file(Rails.root.join('spec/support/data/ESP_adm.zip')) do |url|
     Errno::EADDRINUSE:
       Address already in use - bind(2)
     # ./spec/support/helpers.rb:30:in `new'
     # ./spec/support/helpers.rb:30:in `serve_file'
     # ./spec/requests/api/imports_spec.rb:167:in `block (2 levels) in <top (required)>'

Finished in 1 minute 28.03 seconds
13 examples, 2 failures, 1 pending
```

**Comment by jesusvazquez** [comment]
Adding two new specs with the same issue:

**spec/requests/carto/api/imports_controller_spec.rb**
```
ailures:

  1) Carto::Api::ImportsController gets a list of all pending imports
     Failure/Error: serve_file(Rails.root.join('spec/support/data/ESP_adm.zip')) do |url|
     Errno::EADDRINUSE:
       Address already in use - bind(2)
     # ./spec/support/helpers.rb:30:in `new'
     # ./spec/support/helpers.rb:30:in `serve_file'
     # ./spec/requests/carto/api/imports_controller_spec.rb:31:in `block (2 levels) in <top (required)>'

  2) Carto::Api::ImportsController doesn't return old pending imports
     Failure/Error: serve_file(Rails.root.join('spec/support/data/ESP_adm.zip')) do |url|
     Errno::EADDRINUSE:
       Address already in use - bind(2)
     # ./spec/support/helpers.rb:30:in `new'
     # ./spec/support/helpers.rb:30:in `serve_file'
     # ./spec/requests/carto/api/imports_controller_spec.rb:49:in `block (2 levels) in <top (required)>'

......

  8) Carto::Api::ImportsController returns derived visualization id if created with create_vis flag
     Failure/Error: response.code.should be == '200'
       expected: == "200"
            got:    "429"
     # ./spec/requests/carto/api/imports_controller_spec.rb:176:in `block (2 levels) in <top (required)>'

Finished in 24.23 seconds
29 examples, 8 failures

```

**spec/models/asset_spec.rb**

```
Failures:

  1) Asset#create on local filesystem should save the public url when passing it as an argument
     Failure/Error: serve_file file do |url|
     Errno::EADDRINUSE:
       Address already in use - bind(2)
     # ./spec/support/helpers.rb:30:in `new'
     # ./spec/support/helpers.rb:30:in `serve_file'
     # ./spec/models/asset_spec.rb:70:in `block (4 levels) in <top (required)>'

  2) Asset#create on local filesystem should download the file and move it to the public assets path wh
en passing an url as an argument
     Failure/Error: serve_file file do |url|
     Errno::EADDRINUSE:
       Address already in use - bind(2)
     # ./spec/support/helpers.rb:30:in `new'
     # ./spec/support/helpers.rb:30:in `serve_file'
     # ./spec/models/asset_spec.rb:78:in `block (4 levels) in <top (required)>'

```

I add them to this issue because the solution for them might be the same.

**Comment by rafatower** [comment]
The offending lines:
```ruby
  def upload_file(file_path, mime_type)
    file = Rack::Test::UploadedFile.new(Rails.root.join(file_path), mime_type)
  end
```

The `EADDRINUSE` is typical of processes trying to start services in a given occupied port, which doesn't make much sense. The thing is the file upload done through `Rack::Test::...` is supposed to be already mocked.

**Comment by gfiorav** [comment]
@rafatower @jesusvazquez 

Maybe I'm wrong but I think that `EADDRINUSE` might make sense.

Here are the steps to reproduce in local:

1. Set a `debugger` stop in one of the offending tests like in https://github.com/CartoDB/cartodb/blob/master/spec/requests/carto/api/imports_controller_spec.rb#L29:
```ruby
it 'gets a list of all pending imports' do
  Resque.inline = false
  serve_file(Rails.root.join('spec/support/data/ESP_adm.zip')) do |url|
    debugger
    post api_v1_imports_create_url, params.merge(:url        => url,
                                      :table_name => "wadus")
end
```

2. Run the modified test as `bundle exec rspec spec/requests/carto/api/imports_controller_spec.rb:29`
3. When it stops at the debugger, open another terminal and run the same test again (`bundle exec rspec spec/requests/carto/api/imports_controller_spec.rb:29`)

You get the `EADDRINUSE` on the second terminal because I suspect `Rack::Test::UploadedFile` is using a given fixed port so only one instance can be run at a time, hence parallel test using it at the same time will fail.

I will do 2 things:
1. Check the Rack::Test::UploadedFile code to see if I'm right
2. See if we can overcome this in some hacky way (but i think it will be more a systems than code thing)

**Comment by gfiorav** [comment]
I'll rewrite method `serve_file` in [helper.rb](https://github.com/CartoDB/cartodb/blob/master/spec/support/helpers.rb#L28-L57) to be able to look for an unused port and serve the file on it. This should fix the parallelisation problem.

**Comment by jesusvazquez** [comment]
Yes the error makes sense but we need to remove it in order to run them in parallel. I hope this solution you're proposing is good enough :).
