### ISSUE TITLE
import process fails with .xlsx files

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#5939]
When users import .xlsx files to CartoDB, the import process fails. The error log shows the next message:
```
Errored importing data from /tmp/imports/20151014-20847-1x5jkx3/29.xls:\nfalse: NoMethodError: undefined method `force_normalize' for #<Hash:0x000000058e2ee8>
true: ----------------------------------------------------
false: [\"/home/ubuntu/www/production.cartodb.com/releases/20151014090018/services/importer/lib/importer/excel2csv.rb:51:in `run'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/20151014090018/services/importer/lib/importer/loader.rb:124:in `block (2 levels) in normalize'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/20151014090018/lib/cartodb/stats/aggregator.rb:45:in `block in timing'\", 
\"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'\"

`````
If you transform the .xlsx file into .csv it import it correctly to the account.

**Comment by Kartones** [comment]
Also will fail with XLS, as both share common code and in this case common error
