### ISSUE TITLE
SQL API install issues

### ISSUE THREAD

**Issue by dgeorgievski** [CartoDB/cartodb#5941]
I am trying to install CartoDB on Ubuntu 12.04 following the instructions at http://cartodb.readthedocs.org/en/latest/install.htm

The installation breaks at the step with SQL API when I try to install dependencies by running  
"npm install" 

The instructions are available at http://cartodb.readthedocs.org/en/latest/install.html#sql-api

The error I get is 
> hiredis@0.1.17 install /opt/CartoDB-SQL-API/node_modules/cartodb-redis/node_modules/redis-mpool/node_modules/hiredis
> node-gyp rebuild
>
>gyp ERR! UNCAUGHT EXCEPTION 
>gyp ERR! stack Error: Cannot find module 'brace-expansion'
>gyp ERR! stack     at Function.Module._resolveFilename (module.js:338:15)
>gyp ERR! stack     at Function.Module._load (module.js:280:25)
>gyp ERR! stack     at Module.require (module.js:364:17)
>gyp ERR! stack     at require (module.js:380:17)
>gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node->gyp/node_modules/glob/node_modules/minimatch/minimatch.js:10:14)
>gyp ERR! stack     at Module._compile (module.js:456:26)
>gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
>gyp ERR! stack     at Module.load (module.js:356:32)
>gyp ERR! stack     at Function.Module._load (module.js:312:12)
>gyp ERR! stack     at Module.require (module.js:364:17)
>gyp ERR! System Linux 3.13.0-32-generic
>gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node->gyp.js" "rebuild"
>gyp ERR! cwd /opt/CartoDB-SQL-API/node_modules/cartodb-redis/node_modules/redis->mpool/node_modules/hiredis
>gyp ERR! node -v v0.10.26
>gyp ERR! node-gyp -v v0.12.2
>gyp ERR! This is a bug in `node-gyp`.
>gyp ERR! Try to update node-gyp and file an Issue if it does not help:
>gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
>npm ERR! hiredis@0.1.17 install: `node-gyp rebuild`
>npm ERR! Exit status 7

I tried to install hiredis module separately without success. 

Has anyone else experienced the same issue?  If yes, I would like to know what was the fix.

Thanks

Dimitar

**Comment by dgeorgievski** [comment]
I was able to resolve the issue by cleaning the npm cache and installing  signumd package globally in order to install hiredis.

I also had to install libgdal-dev and libcairo2-dev Ubuntu packages as well.

The overall impression with Ubuntu 12.04 is negative. There were few packaging issues for both npm and apt that were hard to explain.
