### ISSUE TITLE
One click seems to be broken

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5956]
Try with this URL: http://catalog.data.gov/dataset/waofm-gis-congressional-district-boundary
Getting this:
```
2015-10-19 13:12:10 UTC: Running on server que02.useb.cartodb.net with PID: 5271
2015-10-19 13:12:10 UTC: new_importer()
2015-10-19 13:12:10 UTC: Fetching datasource public_url metadata for item id https://data.wa.gov/api/geospatial/dbza-zduy?method=export
2015-10-19 13:12:10 UTC: File will be downloaded from https://data.wa.gov/api/geospatial/dbza-zduy?method=export
2015-10-19 13:12:10 UTC: Before importer run
2015-10-19 13:12:11 UTC: Errored importing data:
2015-10-19 13:12:11 UTC: CartoDB::Importer2::DownloadError: DOWNLOAD ERROR: Code:400 Body:
2015-10-19 13:12:11 UTC: ----------------------------------------------------

services/importer/lib/importer/downloader.rb:271:in `download_and_store'
services/importer/lib/importer/downloader.rb:193:in `set_downloaded_source_file'
services/importer/lib/importer/downloader.rb:126:in `run'
services/importer/lib/importer/runner.rb:229:in `block (2 levels) in single_resource_import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:228:in `block in single_resource_import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:227:in `single_resource_import'
services/importer/lib/importer/runner.rb:96:in `run_import'
services/importer/lib/importer/runner.rb:89:in `block in run'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:88:in `run'
app/connectors/importer.rb:39:in `run'
app/models/data_import.rb:620:in `new_importer'
app/models/data_import.rb:355:in `dispatch'
app/models/data_import.rb:163:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'

2015-10-19 13:12:11 UTC: ----------------------------------------------------
2015-10-19 13:12:11 UTC: Proceeding to register
2015-10-19 13:12:11 UTC: After importer run
2015-10-19 13:12:11 UTC: After dispatch
2015-10-19 13:12:11 UTC: ERROR!
```

**Comment by ethervoid** [comment]
The problem is located in the onclick project.

**Comment by rafatower** [comment]
Is there a related ticket?

**Comment by ethervoid** [comment]
Yes in the onclick repository.
