### ISSUE TITLE
Tar.gz Extraction Error During Import

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6072]
@rafatower @iriberri 

S/B 7145749

## Context
Uploading a NOAA tar.gz compressed file results in a CartoDB::Importer2::ExtractionError. This file is used in a CartoDB tutorial (https://vimeo.com/78298157). I also tried uploading this USGS tar.gz shapefile and failed as well: https://catalog.data.gov/dataset/usgs-small-scale-dataset-state-boundaries-of-the-united-states-200506-shapefile

## Process
1) Download dataset from this link: http://www.srh.noaa.gov/ridge2/Precip/qpehourlyshape/latest/last_1_hours.tar.gz
2) Upload from the CartoDB Editor 
3) Import Error will occur

## Expected Result
User should be able to upload tar.gz file as supported compression format

## Current Result
File fails to import. Can upload if uncompress, then recompress as tar.gz and upload again (works fine!) or uploading as a zip compressed file

**Comment by iriberri** [comment]
Hi @michellechandra, could you please paste the output of the import log? the part where the error is stated as well as the stack trace that appears below. This will help us knowing where the error happens. :-)

**Comment by michellechandra** [comment]
@iriberri - here you go! I was having trouble yesterday in superadmin showing the logs, but it's working today:

2015-11-02 15:50:45 UTC: Before importer run
2015-11-02 15:50:45 UTC: Starting import for /tmp/imports/20151102-28477-nyd1uz/last1hours.tar.gz
2015-11-02 15:50:45 UTC: Unpacking /tmp/imports/20151102-28477-nyd1uz/last1hours.tar.gz
2015-11-02 15:50:45 UTC: Errored importing data:
2015-11-02 15:50:45 UTC: CartoDB::Importer2::ExtractionError: CartoDB::Importer2::ExtractionError
2015-11-02 15:50:45 UTC: ----------------------------------------------------
2015-11-02 15:50:45 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/20151102085348/services/importer/lib/importer/unp.rb:98:in `extract'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/services/importer/lib/importer/unp.rb:42:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/services/importer/lib/importer/runner.rb:247:in `block (2 levels) in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/services/importer/lib/importer/runner.rb:244:in `block in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/services/importer/lib/importer/runner.rb:228:in `single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/services/importer/lib/importer/runner.rb:97:in `run_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/services/importer/lib/importer/runner.rb:90:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/services/importer/lib/importer/runner.rb:89:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/app/connectors/importer.rb:41:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/app/models/data_import.rb:632:in `new_importer'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/app/models/data_import.rb:366:in `dispatch'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/app/models/data_import.rb:166:in `run_import!'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/resque/importer_jobs.rb:9:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/20151102085348/lib/resque/importer_jobs.rb:9:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `<main>'"]

**Comment by rafatower** [comment]
Reproduced locally:
```
stdout: latest/last_1_hours.dbf
latest/last_1_hours.shp
latest/last_1_hours.shx
latest/last_1_hours.prj
stderr: 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

gzip: /tmp/imports/20151104-26747-3oet1o/last_1_hours.tar.gz: not in gzip format

gzip: /tmp/imports/20151104-26747-3oet1o/last_1_hours.tar.gz: not in gzip format
WARNING: There were errors while processing files!
```

Indeed **the file extension is wrong**:
```
$ file last_1_hours.tar.gz 
last_1_hours.tar.gz: POSIX tar archive (GNU)
```

```
$ tar --list --gzip --file=last_1_hours.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

```
$ tar --list --file=last_1_hours.tar.gz 
latest/last_1_hours.dbf
latest/last_1_hours.shp
latest/last_1_hours.shx
latest/last_1_hours.prj
```

I renamed the file to `last_1_hours.tar` without the `.gz` extension and uploaded ok.

@michellechandra It is not an issue in our end. I'd notify the NWS about this so that they can either:
- rename the file, or
- actually compress it with gzip
