### ISSUE TITLE
ERR unknown command 'zscan' in dashboard

### ISSUE THREAD

**Issue by Worvast** [CartoDB/cartodb#6117]
Hi, resume:

We install and create first user, development, try to connect, login ok but when go to:

http://development.localhost.lan:3000/dashboard/

Show this error:

        Redis::CommandError in Admin/visualizations#index
	
	Showing /home/cartodbuser/cartodb/app/views/admin/visualizations/index.html.erb where line #11 raised:
	
	ERR unknown command 'zscan'
	
	Extracted source (around line #11):
	
	8:         </script>
	9:   <% end %>
	10:   <script type="text/javascript">
	11:     var username = "<%= current_user.username %>";
	12:     var user_data = <%= safe_js_object current_user.data.to_json %>;
	13:     var config = <%= safe_js_object frontend_config %>;
	14:     var upgrade_url = config.upgrade_url;
	
	Rails.root: /home/cartodbuser/cartodb
	Full Trace
	
	redis (3.2.1) lib/redis/client.rb:113:in `call'
	redis (3.2.1) lib/redis.rb:2345:in `block in _scan'
	redis (3.2.1) lib/redis.rb:37:in `block in synchronize'
	/opt/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	redis (3.2.1) lib/redis.rb:37:in `synchronize'
	redis (3.2.1) lib/redis.rb:2344:in `_scan'
	redis (3.2.1) lib/redis.rb:2444:in `zscan'
	lib/cartodb/stats/api_calls.rb:113:in `get_api_calls_from_redis_source'
	lib/cartodb/stats/api_calls.rb:75:in `block in get_api_calls_from_redis'
	lib/cartodb/stats/api_calls.rb:74:in `each'
	lib/cartodb/stats/api_calls.rb:74:in `get_api_calls_from_redis'
	lib/cartodb/stats/api_calls.rb:37:in `get_api_calls'
	lib/cartodb/stats/api_calls.rb:12:in `get_api_calls_without_dates'
	app/models/user.rb:761:in `get_api_calls'
	app/models/user/user_decorator.rb:7:in `data'
	app/views/admin/visualizations/index.html.erb:11:in `block in _app_views_admin_visualizations_index_html_erb__3645883873081481451_73375920'
	actionpack (3.2.22) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
	actionpack (3.2.22) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
	actionpack (3.2.22) lib/action_view/helpers/capture_helper.rb:40:in `capture'
	actionpack (3.2.22) lib/action_view/helpers/capture_helper.rb:138:in `content_for'
	app/views/admin/visualizations/index.html.erb:4:in `_app_views_admin_visualizations_index_html_erb__3645883873081481451_73375920'
	actionpack (3.2.22) lib/action_view/template.rb:145:in `block in render'
	activesupport (3.2.22) lib/active_support/notifications.rb:125:in `instrument'
	actionpack (3.2.22) lib/action_view/template.rb:143:in `render'
	actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
	actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
	activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
	activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
	actionpack (3.2.22) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
	actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
	actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
	actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
	actionpack (3.2.22) lib/action_view/renderer/template_renderer.rb:18:in `render'
	actionpack (3.2.22) lib/action_view/renderer/renderer.rb:36:in `render_template'
	actionpack (3.2.22) lib/action_view/renderer/renderer.rb:17:in `render'
	actionpack (3.2.22) lib/abstract_controller/rendering.rb:110:in `_render_template'
	actionpack (3.2.22) lib/action_controller/metal/streaming.rb:225:in `_render_template'
	actionpack (3.2.22) lib/abstract_controller/rendering.rb:103:in `render_to_body'
	actionpack (3.2.22) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
	actionpack (3.2.22) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
	actionpack (3.2.22) lib/abstract_controller/rendering.rb:88:in `render'
	actionpack (3.2.22) lib/action_controller/metal/rendering.rb:16:in `render'
	actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
	activesupport (3.2.22) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
	/opt/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
	activesupport (3.2.22) lib/active_support/core_ext/benchmark.rb:5:in `ms'
	actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
	actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
	/home/cartodbuser/.bundler/ruby/1.9.1/sequel-rails-f61f914b55ff/lib/sequel-rails/railties/controller_runtime.rb:17:in `cleanup_view_runtime'
	actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:39:in `render'
	app/controllers/admin/visualizations_controller.rb:51:in `block (2 levels) in index'
	actionpack (3.2.22) lib/action_controller/metal/mime_responds.rb:196:in `call'
	actionpack (3.2.22) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
	app/controllers/admin/visualizations_controller.rb:50:in `index'
	actionpack (3.2.22) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
	actionpack (3.2.22) lib/abstract_controller/base.rb:167:in `process_action'
	actionpack (3.2.22) lib/action_controller/metal/rendering.rb:10:in `process_action'
	actionpack (3.2.22) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
	activesupport (3.2.22) lib/active_support/callbacks.rb:547:in `block in _run__1599520593726252089__process_action__4254056074125354639__callbacks'
	activesupport (3.2.22) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1329'
	app/controllers/application_controller.rb:77:in `wrap_in_profiler'
	activesupport (3.2.22) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1329'
	activesupport (3.2.22) lib/active_support/callbacks.rb:425:in `_run__1599520593726252089__process_action__4254056074125354639__callbacks'
	activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
	activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
	activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
	actionpack (3.2.22) lib/abstract_controller/callbacks.rb:17:in `process_action'
	actionpack (3.2.22) lib/action_controller/metal/rescue.rb:29:in `process_action'
	actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
	activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
	activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
	actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
	actionpack (3.2.22) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
	actionpack (3.2.22) lib/abstract_controller/base.rb:121:in `process'
	actionpack (3.2.22) lib/abstract_controller/rendering.rb:45:in `process'
	actionpack (3.2.22) lib/action_controller/metal.rb:203:in `dispatch'
	actionpack (3.2.22) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
	actionpack (3.2.22) lib/action_controller/metal.rb:246:in `block in action'
	actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `call'
	actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
	actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:36:in `call'
	journey (1.0.4) lib/journey/router.rb:68:in `block in call'
	journey (1.0.4) lib/journey/router.rb:56:in `each'
	journey (1.0.4) lib/journey/router.rb:56:in `call'
	actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:608:in `call'
	warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
	warden (1.2.3) lib/warden/manager.rb:34:in `catch'
	warden (1.2.3) lib/warden/manager.rb:34:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
	rack (1.4.7) lib/rack/etag.rb:23:in `call'
	rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/head.rb:14:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/flash.rb:242:in `call'
	rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
	rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/cookies.rb:341:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
	activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `_run__2942016553251240453__call__1622190076650486253__callbacks'
	activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
	activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
	activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
	actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	rack (1.4.7) lib/rack/sendfile.rb:102:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
	rollbar (0.12.14) lib/rollbar/middleware/rails/show_exceptions.rb:19:in `call_with_rollbar'
	actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
	railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
	railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
	activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
	railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
	request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
	rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
	rack (1.4.7) lib/rack/runtime.rb:17:in `call'
	activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
	actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
	railties (3.2.22) lib/rails/engine.rb:484:in `call'
	railties (3.2.22) lib/rails/application.rb:231:in `call'
	rack (1.4.7) lib/rack/content_length.rb:14:in `call'
	thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
	thin (1.6.3) lib/thin/connection.rb:84:in `catch'
	thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
	thin (1.6.3) lib/thin/connection.rb:53:in `process'
	thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
	eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
	eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
	thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
	thin (1.6.3) lib/thin/server.rb:162:in `start'
	rack (1.4.7) lib/rack/handler/thin.rb:13:in `run'
	rack (1.4.7) lib/rack/server.rb:268:in `start'
	railties (3.2.22) lib/rails/commands/server.rb:70:in `start'
	railties (3.2.22) lib/rails/commands.rb:55:in `block in <top (required)>'
	railties (3.2.22) lib/rails/commands.rb:50:in `tap'
	railties (3.2.22) lib/rails/commands.rb:50:in `<top (required)>'
	script/rails:6:in `require'
	script/rails:6:in `<main>'
	
	Request
	
	Parameters:
	
	None
	
	Show session dump
	
	_csrf_token: "JyCrffd/g2DHPS6r03ZET1ATmJkRb7TBbU4R3vGp9KM="
	flash: #<ActionDispatch::Flash::FlashHash:0x00000009283bc0 @used=#<Set: {"logged"}>, @closed=false, @flashes={"logged"=>true}, @now=nil>
	session_id: "182042abec0dbed199ce2b0bd82bfb99"
	warden.user.development.key: "development"
	warden.user.development.session: {:sec_token=>"b7c51d59fdb8d53f488ded2d536eaf69532cd3aa"}
	
	Show env dump
	
	GATEWAY_INTERFACE: "CGI/1.2"
	HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
	HTTP_ACCEPT_ENCODING: "gzip, deflate"
	HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.5"
	REMOTE_ADDR: "myip"
	SERVER_NAME: "development.localhost.lan"
	SERVER_PROTOCOL: "HTTP/1.1"
	
	Response
	
	Headers:
	
	None

Any idea what happend here?

**Comment by Worvast** [comment]
I see when i launch dashboard page Ruby on Rails generate this log:

    Rendered admin/visualizations/index.html.erb within layouts/application (2.5ms)
	Completed 500 Internal Server Error in 58.6ms
	[Rollbar] Reporting exception: ERR unknown command 'zscan'
	[Rollbar] Exception not reported because Rollbar is disabled
	
	ActionView::Template::Error (ERR unknown command 'zscan'):
	    8:         </script>
	    9:   <% end %>
	    10:   <script type="text/javascript">
	    11:     var username = "<%= current_user.username %>";
	    12:     var user_data = <%= safe_js_object current_user.data.to_json %>;
	    13:     var config = <%= safe_js_object frontend_config %>;
	    14:     var upgrade_url = config.upgrade_url;
	  lib/cartodb/stats/api_calls.rb:113:in `get_api_calls_from_redis_source'
	  lib/cartodb/stats/api_calls.rb:75:in `block in get_api_calls_from_redis'
	  lib/cartodb/stats/api_calls.rb:74:in `each'
	  lib/cartodb/stats/api_calls.rb:74:in `get_api_calls_from_redis'
	  lib/cartodb/stats/api_calls.rb:37:in `get_api_calls'
	  lib/cartodb/stats/api_calls.rb:12:in `get_api_calls_without_dates'
	  app/models/user.rb:761:in `get_api_calls'
	  app/models/user/user_decorator.rb:7:in `data'
	  app/views/admin/visualizations/index.html.erb:11:in `block in _app_views_admin_visualizations_index_html_erb__4100319944646783025_69258180'
	  app/views/admin/visualizations/index.html.erb:4:in `_app_views_admin_visualizations_index_html_erb__4100319944646783025_69258180'
	  app/controllers/admin/visualizations_controller.rb:51:in `block (2 levels) in index'
	  app/controllers/admin/visualizations_controller.rb:50:in `index'
	  app/controllers/application_controller.rb:77:in `wrap_in_profiler'
	
	
	  Rendered /opt/rubies/ruby-1.9.3-p547/lib/ruby/gems/1.9.1/gems/actionpack-3.2.22/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.2ms)
	  Rendered /opt/rubies/ruby-1.9.3-p547/lib/ruby/gems/1.9.1/gems/actionpack-3.2.22/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.9ms)
	  Rendered /opt/rubies/ruby-1.9.3-p547/lib/ruby/gems/1.9.1/gems/actionpack-3.2.22/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (6.8ms)

**Comment by Worvast** [comment]
Updated Redis version and work. Sorry.
