### ISSUE TITLE
TiffToSqlConversion Error

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6205]
S/B 7519508

@rafatower 

## Context
Tiff file when imported to CartoDB returns error:

CartoDB::Importer2::TiffToSqlConversionError
ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for /tmp/imports/20151201-20144-10pihhz/soybean_yield.tif. There is no affine transformation and no GCPs.

## Process
Import file using CartoDB Editor. Error occurs. File looks correctly geocoded:

~/Desktop $ gdalinfo soybean_yield.tif                                                             
Driver: GTiff/GeoTIFF
Files: soybean_yield.tif
Size is 1750, 1188
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 1188.0)
Upper Right ( 1750.0,    0.0)
Lower Right ( 1750.0, 1188.0)
Center      (  875.0,  594.0)
Band 1 Block=1750x1 Type=Byte, ColorInterp=Red
  NoData Value=nan
Band 2 Block=1750x1 Type=Byte, ColorInterp=Green
  NoData Value=nan
Band 3 Block=1750x1 Type=Byte, ColorInterp=Blue
  NoData Value=nan

**Comment by rafatower** [comment]
For the record:
```
CartoDB::Importer2::TiffToSqlConversionError: (pid 20166 exit 1) |ERROR 1: Unable to compute a transformation between pixel/line

["/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/raster2pgsql.rb:76:in `reproject_raster'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/raster2pgsql.rb:32:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/tiff_loader.rb:23:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:224:in `file_based_loader_run'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:179:in `import'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:331:in `execute_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:261:in `block (3 levels) in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:255:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:255:in `each_with_index'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:255:in `block (2 levels) in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:250:in `block in single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:228:in `single_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:97:in `run_import'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:90:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/services/importer/lib/importer/runner.rb:89:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/app/connectors/importer.rb:41:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/app/models/data_import.rb:632:in `new_importer'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/app/models/data_import.rb:366:in `dispatch'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/app/models/data_import.rb:166:in `run_import!'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/resque/importer_jobs.rb:9:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/20151201150041/lib/resque/importer_jobs.rb:9:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `<main>'"]
```

**Comment by rafatower** [comment]
By googling the issue, the file lacks the geographical extents
https://lists.osgeo.org/pipermail/gdal-dev/2011-October/030571.html

**Comment by rafatower** [comment]
This is how it should look like (example in EPSG:4326):
```
Corner Coordinates:
Upper Left  (-180.0000000,  90.0000000) (180d 0' 0.00"W, 90d 0' 0.00"N)
Lower Left  (-180.0000000, -90.0000000) (180d 0' 0.00"W, 90d 0' 0.00"S)
Upper Right ( 180.0000000,  90.0000000) (180d 0' 0.00"E, 90d 0' 0.00"N)
Lower Right ( 180.0000000, -90.0000000) (180d 0' 0.00"E, 90d 0' 0.00"S)
Center      (   0.0000000,  -0.0000000) (  0d 0' 0.00"E,  0d 0' 0.00"S)
```

that is, corners mapped to some real place on earth.
