### ISSUE TITLE
Detect "reached limit on number of templates" error on import

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6275]
````
2015-12-15 08:55:44 UTC: Exception: POST:400 http://xxxxx.cartodb.com:80/api/v1/map/named?api_key=xxxxx{\"errors\":[\"User 'xxxx' reached limit on number of templates (4096/4096)\"]}
2015-12-15 08:55:44 UTC: [\"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_map.rb:49:in `block in create_new'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/lib/cartodb/stats/aggregator.rb:45:in `block in timing'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/lib/cartodb/stats/aggregator.rb:43:in `timing'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_map.rb:35:in `create_new'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_maps.rb:36:in `create'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/visualization/member.rb:825:in `create_named_map'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/visualization/member.rb:661:in `save_named_map'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/visualization/member.rb:756:in `do_store'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/visualization/member.rb:173:in `store'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/table.rb:534:in `create_default_visualization'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/table.rb:406:in `after_create'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/table/user_table.rb:189:in `after_create'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1585:in `block (2 levels) in _save'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in `around_create'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1578:in `block in _save'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in `around_save'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1573:in `_save'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `block (2 levels) in save'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `block in checked_transaction'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:323:in `_transaction'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:285:in `block in transaction'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/query.rb:278:in `transaction'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `checked_transaction'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `block in save'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1710:in `checked_save_failure'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `save'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/table.rb:88:in `save'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/table_registrar.rb:18:in `register'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/connectors/importer.rb:205:in `persist_metadata'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/connectors/importer.rb:75:in `register'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/connectors/importer.rb:52:in `block in run'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/connectors/importer.rb:51:in `each'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/connectors/importer.rb:51:in `run'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/data_import.rb:638:in `new_importer'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/data_import.rb:372:in `dispatch'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/app/models/data_import.rb:172:in `run_import!'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/lib/resque/importer_jobs.rb:9:in `block in perform'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/lib/resque/base_job.rb:21:in `call'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/lib/resque/base_job.rb:21:in `run_action'\", \"/home/ubuntu/www/production.cartodb.com/releases/20151214170219/lib/resque/importer_jobs.rb:9:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'\", \"/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `load'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `<main>'\"]\n2015-12-15 08:55:44 UTC: ERROR!\n\n
`````

**Comment by iriberri** [comment]
Should we be raising a specific exception for this directly in the named maps wrapper?

**Comment by rafatower** [comment]
Can you provide the full stack trace?

There's already an `HTTPResponseError`. The exception should be more specific. See the file `named-maps-wrapper/exceptions.rb`.

@rochoa are the `400` errors just used for the limit on templates?

**Comment by rochoa** [comment]
400 is the generic way of saying ... the client did/sent something wrong.

We could raise `409 Conflict` for this case.

**Comment by iriberri** [comment]
This was still pending to merge, but it seems that the `409` error just got added into Windshaft: https://github.com/CartoDB/Windshaft-cartodb/issues/346#event-512497962 so I can work into improving that part before merging.

**Comment by rochoa** [comment]
I just merged it to master. I had the code in a git stash since a few weeks ago but forgot to push it.

**Comment by iriberri** [comment]
@rochoa when do you plan this to be deployed (if it isn't already)? No rush, just for me to know to work on the improvement after that happens.

**Comment by rochoa** [comment]
End of week, worst case scenario.

**Comment by iriberri** [comment]
:+1:
