### ISSUE TITLE
"ArgumentError: invalid byte sequence in UTF-8" error on ZIP import

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6276]
````
2015-12-14 15:32:01 UTC: Unpacking /tmp/imports/xxxxx-1455-1gqe5as/xxxxxx.zip
2015-12-14 15:32:01 UTC: Errored importing data:
2015-12-14 15:32:01 UTC: ArgumentError: invalid byte sequence in UTF-8
2015-12-14 15:32:01 UTC: ----------------------------------------------------
2015-12-14 15:32:01 UTC: [\"/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/unp.rb:180:in `=~'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/unp.rb:180:in `unp_failure?'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/unp.rb:91:in `extract'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/unp.rb:42:in `run'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/runner.rb:247:in `block (2 levels) in single_resource_import'\"

```

**Comment by iriberri** [comment]
b57e8686-a383-4e10-81f7-da82f9f2fe0e

**Comment by iriberri** [comment]
After everything we discussed time ago, I think I'm just gonna rescue the encoding error and return it to the user so that it is not an unknown error and people can sort it out. These would also start counting as user errors and not as platform errors.

**Comment by iriberri** [comment]
![image](https://cloud.githubusercontent.com/assets/1730320/13315967/12b5f7ec-dbae-11e5-944e-6f79622ef03f.png)

:-)
