### ISSUE TITLE
Mail notifier after timeout error: Exception: can't convert nil into String

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#6296]
When trying to create a table from a table view, a timeout occurs. 
The error message the user is getting is: Duplicated column name

## Context

```
 "2015-12-18 01:31:55 UTC: Running on server xx.uxxseb.cartodb.net with PID: 28047 2015-12-18 01:31:55 UTC: from_table() 2015-12-18 01:31:55 UTC: import_from_query() 2015-12-18 01:36:55 UTC: Going to set merge error with code 8003 2015-12-18 01:36:55 UTC: Additional error info: PG::Error: ERROR: canceling statement due to statement timeout 2015-12-18 01:36:55 UTC: After dispatch 2015-12-18 01:36:55 UTC: ERROR! 2015-12-18 01:36:55 UTC: Exception: can't convert nil into String 2015-12-18 01:36:55 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/20151217145621/services/importer/lib/importer/mail_notifier.rb:58:in `basename'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/services/importer/lib/importer/mail_notifier.rb:58:in `extract_file_names'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/services/importer/lib/importer/mail_notifier.rb:31:in `send!'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/services/importer/lib/importer/mail_notifier.rb:18:in `notify_if_needed'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/app/models/data_import.rb:812:in `notify'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/app/models/data_import.rb:330:in `handle_failure'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/app/models/data_import.rb:191:in `run_import!'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/lib/resque/importer_jobs.rb:9:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/20151217145621/lib/resque/importer_jobs.rb:9:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake:23:in `<main>'"] ===LOG END==="
```

**Comment by iriberri** [comment]
Related: https://github.com/CartoDB/cartodb/issues/6502

**Comment by juanignaciosl** [comment]
Related, but it's failing on success: https://rollbar.com/vizzuality/CartoDB/items/15446/?item_page=0&#traceback

**Comment by ethervoid** [comment]
Ok, thank you @juanignaciosl

**Comment by iriberri** [comment]
Basically, table copys, merges and tables created from sql do not have a populated `service_item_id`. In that case, `table_name` contains the name too.

**Comment by iriberri** [comment]
Reassigning the issue to me, @ethervoid, as @rafatower spotted it here and scheduled it: https://github.com/CartoDB/cartodb/issues/7146

**Comment by iriberri** [comment]
Noticing that this is something likely to happen in local if the mail notifier is enabled, because as there's no file upload/download, there's no `service_item_id`.
