### ISSUE TITLE
Set "Errno::EISDIR: Is a directory" as import user error

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6307]
Sometimes, when using the API, users send incorrectly the file path and CartoDB is raising this error. This is not being detected as a user error at the moment.

Sample trace:

````
2016-01-20 01:37:27 UTC: Unpacking ./\n2016-01-20 01:37:27 UTC: Errored importing data:\n2016-01-20 01:37:27 UTC: Errno::EISDIR: Is a directory @ rb_sysopen - /tmp/imports/20160120-8589-x4cxv5/./.
2016-01-20 01:37:27 UTC: ----------------------------------------------------
2016-01-20 01:37:27 UTC: [\"/usr/lib/ruby/2.2.0/fileutils.rb:1392:in `initialize'\", 
\"/usr/lib/ruby/2.2.0/fileutils.rb:1392:in `open'\",
 \"/usr/lib/ruby/2.2.0/fileutils.rb:1392:in `block in copy_file'\", 
\"/usr/lib/ruby/2.2.0/fileutils.rb:1391:in `open'\", 
\"/usr/lib/ruby/2.2.0/fileutils.rb:1391:in `copy_file'\",
 \"/usr/lib/ruby/2.2.0/fileutils.rb:485:in `copy_file'\", 
\"/usr/lib/ruby/2.2.0/fileutils.rb:402:in `block in cp'\", 
\"/usr/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'\",
 \"/usr/lib/ruby/2.2.0/fileutils.rb:1584:in `fu_each_src_dest0'\",
 \"/usr/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'\", 
\"/usr/lib/ruby/2.2.0/fileutils.rb:401:in `cp'\", 
\"/home/ubuntu/www/production.cartodb.com/releases/x/services/importer/lib/importer/unp.rb:50:in `without_unpacking'\",
````

**Comment by iriberri** [comment]
@rafatower if you're not against, adding this to my list. This one seems to be punching import errors a lot, and it's indeed a user error and not a platform error (as it's detected now).

**Comment by iriberri** [comment]
```
[46, 55] in /home/ubuntu/www/production.cartodb.com/current/services/importer/lib/importer/unp.rb
   46:       end
   47: 
   48:       def without_unpacking(path)
   49:         local_path = "#{temporary_directory}/#{File.basename(path)}"
   50:         debugger
=> 51:         FileUtils.cp(path, local_path)
   52:         
   53:         self.source_files.push(source_file_for(normalize(local_path)))
   54:         @source_files = split(source_files)
   55:         self
(byebug) path
"./"
(byebug) local_path
"/tmp/imports/20160120-32727-vv1wvk/."

(byebug) File.directory?(path)
true
```
