### ISSUE TITLE
Bad interaction between test files

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#6465]
```
10:25:30 Failures:
10:25:30 
10:25:30   1) Carto::Api::OrganizationUsersController user creation correctly creates a user
10:25:30      Failure/Error: last_user_created.username.should == username
10:25:30      NoMethodError:
10:25:30        undefined method `username' for nil:NilClass
10:25:30      # ./spec/requests/carto/api/organization_users_controller_spec.rb:75:in `block (3 levels) in <top (required)>'
10:25:30 
10:25:30   2) Carto::Api::OrganizationUsersController user creation assigns soft_geocoding_limit to false by default
10:25:30      Failure/Error: last_user_created.soft_geocoding_limit.should == false
10:25:30      NoMethodError:
10:25:30        undefined method `soft_geocoding_limit' for nil:NilClass
10:25:30      # ./spec/requests/carto/api/organization_users_controller_spec.rb:94:in `block (3 levels) in <top (required)>'
10:25:30 
10:25:30 Finished in 6 minutes 30.02 seconds
10:25:30 258 examples, 2 failures, 1 pending
10:25:30 
10:25:30 Failed examples:
10:25:30 
10:25:30 rspec ./spec/requests/carto/api/organization_users_controller_spec.rb:62 # Carto::Api::OrganizationUsersController user creation correctly creates a user
10:25:30 rspec ./spec/requests/carto/api/organization_users_controller_spec.rb:81 # Carto::Api::OrganizationUsersController user creation assigns soft_geocoding_limit to false by default
10:25:35 Coverage report generated for specs_15070, specs_18225, specs_24259, specs_24307 to /home/ubuntu/workspace/CartoDB-master-testing/coverage. 16323 / 40027 LOC (40.78%) covered.
10:25:40 make: *** [check-4] Error 1
10:25:40 Build step 'Execute shell' marked build as failure
10:25:40 Finished: FAILURE
```

How to reproduce:
```
RAILS_ENV=test bundle exec rspec --fail-fast spec/rspec_configuration.rb spec/requests/carto/api/organization_users_controller_spec.rb spec/requests/carto/api/imports_controller_spec.rb
```

(similar to what `make check-4` does)

**Comment by javitonino** [comment]
Seems to be solved with @rafatower commit
