### ISSUE TITLE
Importer fails at renaming table when fed with public.csv

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#6609]
How to reproduce: try to import a CSV file called `public.csv`
Expected: it gets imported.
Actual:
```
2016-02-17 15:25:39 UTC: Before importer run
2016-02-17 15:25:50 UTC: Starting import for /tmp/imports/20160217-17920-1u1xmce/public.csv
2016-02-17 15:25:50 UTC: Unpacking /tmp/imports/20160217-17920-1u1xmce/public.csv
2016-02-17 15:25:51 UTC: Filename: /tmp/imports/20160217-17920-zwrh5u/public.csv Size (bytes): 63677977
...
true: Finished importing data from /tmp/imports/20160217-17920-zwrh5u/public.csv
2016-02-17 15:26:06 UTC: Proceeding to register
2016-02-17 15:26:06 UTC: Before renaming from importer_b30ce374d58a11e59849040111176f01 to public
2016-02-17 15:26:07 UTC: Before moving schema 'public' from cdb_importer to common_data
2016-02-17 15:26:07 UTC: Before persisting metadata 'public' data_import_id: 846e26fc-75d9-4089-a8ad-6c9098bdccca
2016-02-17 15:26:07 UTC: Exception: PG::Error: ERROR:  table "public" does not exist
```

Stacktrace:
```
lib/importer/lib/cartodb-migrator/migrator.rb:102:in `rescue in migrate!'
lib/importer/lib/cartodb-migrator/migrator.rb:107:in `migrate!'
app/models/table.rb:293:in `import_to_cartodb'
app/models/table.rb:376:in `before_create'
app/models/table/user_table.rb:184:in `before_create'
app/models/table.rb:88:in `save'
app/models/table_registrar.rb:18:in `register'
app/connectors/importer.rb:205:in `persist_metadata'
app/connectors/importer.rb:75:in `register'
app/connectors/importer.rb:52:in `block in run'
app/connectors/importer.rb:51:in `each'
app/connectors/importer.rb:51:in `run'
app/models/data_import.rb:638:in `new_importer'
app/models/data_import.rb:372:in `dispatch'
app/models/data_import.rb:172:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

This shall be easy to fix and might be a cause of stale tables in `cdb_importer` schema (I haven't checked).

Exported tables get that name in many cases (will create a ticket for that in the corresponding repository).

cc/ @zenitraM

**Comment by iriberri** [comment]
I haven't been able to reproduce this issue, but I've been able to trace:

````
2016-02-22 12:57:53 UTC: Proceeding to register\n2016-02-22 12:57:53 UTC: Before renaming from importer_de0622fcd96311e5a91d080027880ca6 to _public\n2016-02-22 12:57:53 UTC: Before moving schema '_public' from cdb_importer to pepes\n2016-02-22 12:57:55 UTC: Exception: PG::Error: ERROR:  type \"_public\" already exists in schema \"pepes\"\n\n2016-02-22 12:57:55 UTC: [\"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `exec'\",
 \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'\", 
\"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/database/logging.rb:37:in `log_yield'\",
 \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'\", 
\"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'\",
 \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'\", 
\"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'\", \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'\", \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'\", \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in `check_database_errors'\", \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'\",
 \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'\", 
\"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'\", 
\"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'\", \"/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'\",
 \"/home/ubuntu/www/production.cartodb.com/current/app/connectors/importer.rb:126:in `move_to_schema'\",
 \"/home/ubuntu/www/production.cartodb.com/current/app/connectors/importer.rb:72:in `register'\"
`````

When a table is imported, Postgres generates a type with name `_` + `tablename`.

This causes the following workflow:

- Import table `my_table`
- Everything is okay
- Try to import table `_my_table`. The name has not been used, so when `get_valid_table_name` is called, `_my_table` is a valid one.
- The import crashes (stack trace above) because the first import created a `_my_table`  type in the User DB

See: http://stackoverflow.com/questions/26631976/how-to-rename-a-postgresql-table-by-prefixing-an-underscore

We're preparing a fix atm.
