### ISSUE TITLE
cdb_org_member_78ab1431540d62afc6035c120ead8c57 does not exist

### ISSUE THREAD

**Issue by sabala12** [CartoDB/cartodb#6823]
Hello,
I have some problems deploying CartoDB with Docker.

When I try to create a new user using:
RAILS_ENV=development bundle exec rake cartodb:db:setup_user SUBDOMAIN="${SUBDOMAIN}" \
        PASSWORD="${PASSWORD}" \
        EMAIL="${EMAIL}"

I get the following error:
"PG::Error: ERROR:  role 'cdb_org_member_0c105a4c7f4a44eececb5c0d9dc8d660' does not exist"
"CONTEXT:  SQL statement "GRANT "cdb_org_member_0c105a4c7f4a44eececb5c0d9dc8d660" TO "development_cartodb_user_98eeac7c-8460-4ce5-9b83-95ca0806ecb5""
PL/pgSQL function cdb_organization_create_member(text) line 3 at EXECUTE statement"

All cartodb-postgresql.git installcheck tests had passed with no errors.

I run postgres, redis, sql-api, maps-api, and cartodb on different containers, with Ubuntu 12.04 images.
My kernel is 3.19.0-32-generic.

Thanks,
Eran

**Comment by javisantana** [comment]
What docker image are you using?

**Comment by sabala12** [comment]
ubuntu:12.04

**Comment by sabala12** [comment]
https://github.com/sabala12/docker-cartodb

**Comment by snario** [comment]
@sabala12 did you get it to work?

**Comment by sabala12** [comment]
Yes

**Comment by GISlator** [comment]
Hi,
I have the same issue, how did you solve it?

**Comment by sabala12** [comment]
Hello,

If I remember correctly, I had to run "bundle exec rake db:migrate" before "
script/create_dev_user".

2016-07-27 8:40 GMT+03:00 GISlator <notifications@github.com>:

**Comment by GISlator** [comment]
Thanks.
I still get the same error.

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.

**Comment by mondeja** [comment]
I'm getting the same error on development database and I can't fix it with ``bundle exec rake db:migrate``. If I recreate the database entirely, it doesn't appears, but this error continues appearing after some days of work. Why could it be happening?

```
D, [2019-02-26T12:59:17.916089 #21208] DEBUG -- :   Sequel::Postgres::Database (1.0ms)  SELECT cartodb.CDB_Organization_Create_Member('development_cartodb_user_f66d6fba-f391-49ee-b6aa-e7ce53f355e8');
E, [2019-02-26T12:59:17.916155 #21208] ERROR -- : PG::Error: ERROR:  role "cdb_org_member_f1f69e3b139d5800b89a1299feccef3e" does not exist
CONTEXT:  SQL statement "GRANT "cdb_org_member_f1f69e3b139d5800b89a1299feccef3e" TO "development_cartodb_user_f66d6fba-f391-49ee-b6aa-e7ce53f355e8""
PL/pgSQL function cdb_organization_create_member(text) line 3 at EXECUTE: SELECT cartodb.CDB_Organization_Create_Member('development_cartodb_user_f66d6fba-f391-49ee-b6aa-e7ce53f355e8');
D, [2019-02-26T12:59:17.916394 #21208] DEBUG -- :   Sequel::Postgres::Database (0.1ms)  ROLLBACK
I, [2019-02-26T12:59:17.916433 #21208]  INFO -- : (0.000161s) ROLLBACK
D, [2019-02-26T12:59:17.916782 #21208] DEBUG -- :   Sequel::Postgres::Database (0.2ms)  ROLLBACK
rake aborted!
PG::Error: ERROR:  role "cdb_org_member_f1f69e3b139d5800b89a1299feccef3e" does not exist
CONTEXT:  SQL statement "GRANT "cdb_org_member_f1f69e3b139d5800b89a1299feccef3e" TO "development_cartodb_user_f66d6fba-f391-49ee-b6aa-e7ce53f355e8""
PL/pgSQL function cdb_organization_create_member(text) line 3 at EXECUTE
/var/lib/gems/2.2.0/gems/sequel-3.44.0/lib/sequel/adapters/postgres.rb:145:in `exec'
/var/lib/gems/2.2.0/gems/sequel-3.44.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
/var/lib/gems/2.2.0/gems/sequel-rails-0.9.15/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
/var/lib/gems/2.2.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.2.0/gems/sequel-rails-0.9.15/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
/var/lib/gems/2.2.0/gems/sequel-rails-0.9.15/lib/sequel_rails/sequel/database/active_support_notification.rb:28:in `log_yield'
/var/lib/gems/2.2.0/gems/sequel-3.44.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
/var/lib/gems/2.2.0/gems/sequel-3.44.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'
```
