### ISSUE TITLE
Importer tests failing on PSQL 9.5 executors

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#6852]
```
18:05:27 rspec ./services/importer/spec/acceptance/csv_spec.rb:38 # csv regression tests imports XLS files
18:05:27 rspec ./spec/requests/carto/api/visualizations_controller_spec.rb:1597 # Carto::Api::VisualizationsController main behaviour #vizjson3 includes vector flag (true if requested)
18:05:27 
18:05:27 Failures:
18:05:27 
18:05:27   1) csv regression tests imports XLS files
18:05:27      Failure/Error: result.success?.should be_true, "error code: #{result.error_code}, trace: #{result.log_trace}"
18:05:27        error code: 1005, trace: Starting import for /home/ubuntu/workspace/CartoDB-PR-testing/services/importer/spec/acceptance/../fixtures/../../../../spec/support/data/ngos.xlsxUnpacking /home/ubuntu/workspace/CartoDB-PR-testing/services/importer/spec/acceptance/../fixtures/../../../../spec/support/data/ngos.xlsxFilename: /tmp/imports/20160310-18131-p04cw6/ngos.xlsx Size (bytes): 87214Importing data from /tmp/imports/20160310-18131-p04cw6/ngos.xlsxFile-based import loadConverting XLSX to CSVAbout to execute in2csv: in2csv /tmp/imports/20160310-18131-p04cw6/ngos.xlsx | grep -v "WARNING \*\*\* OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero" | grep -v "\*\*\* No CODEPAGE record, no encoding_override: will use 'ascii'" | /home/ubuntu/workspace/CartoDB-PR-testing/lib/importer/misc/csv_remove_newlines.py > /tmp/imports/20160310-18131-p04cw6/ngos.csvdone executing in2csv.Orig file: /tmp/imports/20160310-18131-p04cw6/ngos.xlsx
18:05:27        Temp destination: /tmp/imports/20160310-18131-p04cw6/ngos.csvErrored importing data from /tmp/imports/20160310-18131-p04cw6/ngos.xlsx:CartoDB::Importer2::EmptyFileError: CartoDB::Importer2::EmptyFileError----------------------------------------------------["/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/csv_normalizer.rb:173:in `single_column?'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/csv_normalizer.rb:168:in `needs_normalization?'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/csv_normalizer.rb:48:in `run'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/excel2csv.rb:51:in `run'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/loader.rb:125:in `block (2 levels) in normalize'", "/home/ubuntu/workspace/CartoDB-PR-testing/lib/cartodb/stats/aggregator.rb:97:in `method_missing'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/loader.rb:117:in `block in normalize'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/loader.rb:115:in `each'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/loader.rb:115:in `inject'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/loader.rb:115:in `normalize'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/loader.rb:56:in `block (2 levels) in run'", "/home/ubuntu/workspace/CartoDB-PR-testing/lib/cartodb/stats/aggregator.rb:97:in `method_missing'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/loader.rb:55:in `block in run'", "/home/ubuntu/workspace/CartoDB-PR-testing/lib/cartodb/stats/aggregator.rb:97:in `method_missing'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/loader.rb:52:in `run'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:230:in `file_based_loader_run'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:182:in `import'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:338:in `execute_import'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:267:in `block (3 levels) in single_resource_import'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:261:in `each'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:261:in `each_with_index'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:261:in `block (2 levels) in single_resource_import'", "/home/ubuntu/workspace/CartoDB-PR-testing/lib/cartodb/stats/aggregator.rb:97:in `method_missing'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:256:in `block in single_resource_import'", "/home/ubuntu/workspace/CartoDB-PR-testing/lib/cartodb/stats/aggregator.rb:97:in `method_missing'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:234:in `single_resource_import'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:97:in `run_import'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:90:in `block in run'", "/home/ubuntu/workspace/CartoDB-PR-testing/lib/cartodb/stats/aggregator.rb:97:in `method_missing'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/lib/importer/runner.rb:89:in `run'", "/home/ubuntu/workspace/CartoDB-PR-testing/services/importer/spec/acceptance/csv_spec.rb:47:in `block (2 levels) in <top (required)>'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `instance_eval'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:114:in `block in run'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:254:in `with_around_each_hooks'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/example.rb:111:in `run'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:388:in `block in run_examples'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `map'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:384:in `run_examples'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/example_group.rb:369:in `run'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `map'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:28:in `block in run'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/reporter.rb:34:in `report'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:25:in `run'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'", "/var/lib/gems/2.2.0/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `block in autorun'"]----------------------------------------------------
18:05:27      # ./services/importer/spec/acceptance/csv_spec.rb:50:in `block (2 levels) in <top (required)>'
```
https://ci.cartodb.net/view/PRs/job/CartoDB-PR-testing/756/consoleFull

**Comment by javitonino** [comment]
See https://github.com/CartoDB/cartodb/pull/6804
