### ISSUE TITLE
Time-series widget won't filter with named maps

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7011]
If you create a map with public data, time series widget filtering works. But making the data private won't. The POST request won't finish because tiler fails:

```
[2016-04-01 09:09:31.274] [INFO] [default] - undefined OPTIONS juanignaciosl.localhost.lan:8181/api/v1/map/named/tpl_735e54b2_f7e8_11e5_a5c0_080027880ca6?stat_tag=735e54b2-f7e8-11e5-a5c0-080027880ca6&filters=%7B%22layers%22%3A%5B%7B%22a234da58-cf0f-4fd1-997f-4e80e9d8f446%22%3A%7B%22min%22%3A1422642150%2C%22max%22%3A1422808537.5%7D%7D%5D%7D 200 1 ms -> text/html; charset=utf-8 (undefined)
[2016-04-01 09:09:31.306] [ERROR] [default] - Uncaught exception: TypeError: Cannot read property 'type' of undefined
    at FilterFactory.getFilter (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/filters/factory.js:14:32)
    at /home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:333:34
    at Array.map (native)
    at MapConfig.getLayerFilters (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:332:46)
    at MapConfig.getLayer (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:155:24)
    at MapConfig.<anonymous> (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:169:21)
    at Array.map (native)
    at MapConfig.getLayers (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:168:29)
    at /home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/backends/map_validator.js:58:19
    at Function.finish (/home/ubuntu/www/node-windshaft/current/lib/cartodb/models/mapconfig/create_layergroup_provider.js:37:20)
```

cc @xavijam

**Comment by juanignaciosl** [comment]
PS: it only happens in the editor just after adding the widgets. After a reload it works.

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
