### ISSUE TITLE
Filtering with category widgets does not work in named maps with the new Editor

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7027]
@ramiroaznar commented on [Mon Apr 04 2016](https://github.com/CartoDB/cartodb-management/issues/4430)

It looks like filtering does not work in named maps in the new Editor. After filtering, the tiler request is pending for a long time and then show an error (last screenshot).

Selecting all the data:
![filter_all](https://cloud.githubusercontent.com/assets/5215798/14248045/ab999f1c-fa72-11e5-9e4d-e0435534aeda.png)

Filtering:
![filter_one](https://cloud.githubusercontent.com/assets/5215798/14248047/ae551d30-fa72-11e5-8d32-9196ff5ccd85.png)

Request error:
![error](https://cloud.githubusercontent.com/assets/5215798/14248052/b0ec9866-fa72-11e5-9dfe-462d08ad8c24.png)

**Comment by xavijam** [comment]
cc @juanignaciosl

**Comment by juanignaciosl** [comment]
I see. Not only categories, histogram won't work either. Tiler error:

```
[2016-04-04 14:15:35.252] [ERROR] [default] - Uncaught exception: TypeError: Cannot read property 'type' of undefined
    at FilterFactory.getFilter (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/filters/factory.js:14:32)
    at /home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:333:34
    at Array.map (native)
    at MapConfig.getLayerFilters (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:332:46)
    at MapConfig.getLayer (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:155:24)
    at MapConfig.<anonymous> (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:169:21)
    at Array.map (native)
    at MapConfig.getLayers (/home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/models/mapconfig.js:168:29)
    at /home/ubuntu/www/node-windshaft/current/node_modules/windshaft/lib/windshaft/backends/map_validator.js:58:19
    at Function.finish (/home/ubuntu/www/node-windshaft/current/lib/cartodb/models/mapconfig/create_layergroup_provider.js:37:20)
```

Maybe related to #7011

**Comment by juanignaciosl** [comment]
@ramiroaznar , @xavijam, I've talked to @alonsogarciapablo about this and that and he said that _filtering_ is being changed, so this will be fixed soon.

**Comment by juanignaciosl** [comment]
FYI, analysis branch with updated camshaft works.

**Comment by juanignaciosl** [comment]
Sorry, no, it won't work, I made a mistake running some tests.

**Comment by juanignaciosl** [comment]
This might be related: #7449

**Comment by alonsogarciapablo** [comment]
Closing this as it seems to be working now.
