### ISSUE TITLE
Detect time zone displacement out of range in ogr2ogr2

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#7237]
```
ERROR 1: COPY statement failed. ERROR: time zone displacement out of range: "2016/02/13 22:50:25+2445"
```

from:

```
["/services/importer/lib/importer/loader.rb:335:in `check_for_import_errors'", 
"/services/importer/lib/importer/loader.rb:268:in `run_ogr2ogr'", 
"/services/importer/lib/importer/loader.rb:63:in `block (2 levels) in run'", 
"/services/importer/lib/importer/loader.rb:62:in `block in run'", 
"/services/importer/lib/importer/loader.rb:52:in `run'",
 "/services/importer/lib/importer/runner.rb:236:in `file_based_loader_run'", 
```

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.
