### ISSUE TITLE
Fix raster tests for multiple CI configs

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#7645]
This test is failing in CI in two different ways:

```
08:20:21   1) raster2pgsql acceptance tests keeps the original table unaltered regardless of overviews
08:20:21      Failure/Error: }).first
08:20:21      Sequel::DatabaseError:
08:20:21        PG::Error: ERROR:  invalid input syntax for type double precision: "0.148148148148133,10"
08:20:21        CONTEXT:  SQL function "_raster_constraint_info_scale" statement 1
08:20:21      # ./services/importer/spec/acceptance/raster2pgsql_spec.rb:134:in `block (2 levels) in <top (required)>'
08:20:21 
08:20:21 Finished in 2 minutes 15.09 seconds
08:20:21 29 examples, 1 failure, 7 pending
```

```
08:49:34 Failures:
08:49:34 
08:49:34   1) raster2pgsql acceptance tests keeps the original table unaltered regardless of overviews
08:49:34      Failure/Error: metadata[:srid].should eq 4326
08:49:34      NoMethodError:
08:49:34        undefined method `[]' for nil:NilClass
08:49:34      # ./services/importer/spec/acceptance/raster2pgsql_spec.rb:135:in `block (2 levels) in <top (required)>'
08:49:34 
08:49:34 Finished in 4 minutes 7.4 seconds
08:49:34 35 examples, 1 failure
```

**Comment by rafatower** [comment]
This should have been fixed a long time ago, closing it.
