### ISSUE TITLE
Ghost tables race condition avoided but import broken

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#7708]
https://rollbar.com/vizzuality/CartoDB/items/17012/occurrences/13780142698/

but then I got this (import with id `bbe8f8d4-2b0c-4150-a9e6-54604328aadb`):
```
        | 2016-06-07 13:28:49 UTC: Proceeding to register
        | 2016-06-07 13:28:49 UTC: Before renaming from importer_c3fbd6602cb311e694950ef7f98ade21 to quoted_fields
        | 2016-06-07 13:28:49 UTC: Before moving schema 'quoted_fields_3' from cdb_importer to rtorre
        | 2016-06-07 13:28:49 UTC: Before persisting metadata 'quoted_fields_3' data_import_id: bbe8f8d4-2b0c-4150-a9e6-54604328aadb
        | 2016-06-07 13:29:03 UTC: Exception: name and user_id is already taken
```

ant the full backtrace
```
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1250:in `save'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/models/table.rb:427:in `after_create'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/models/table/user_table.rb:192:in `after_create'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1585:in `block (2 levels) in _save'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in `around_create'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1578:in `block in _save'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in `around_save'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1573:in `_save'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `block (2 levels) in save'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `block in checked_transaction'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/database/query.rb:323:in `_transaction'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/database/query.rb:285:in `block in transaction'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/database/query.rb:278:in `transaction'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `checked_transaction'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `block in save'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1710:in `checked_save_failure'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `save'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/models/table.rb:87:in `save'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/models/table_registrar.rb:18:in `register'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/connectors/importer.rb:207:in `persist_metadata'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/connectors/importer.rb:80:in `register'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/connectors/importer.rb:54:in `block in run'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/connectors/importer.rb:53:in `each'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/connectors/importer.rb:53:in `run'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/models/data_import.rb:665:in `new_importer'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/models/data_import.rb:394:in `dispatch'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/app/models/data_import.rb:176:in `run_import!'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/lib/resque/importer_jobs.rb:9:in `block in perform'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/lib/resque/base_job.rb:21:in `call'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/lib/resque/base_job.rb:21:in `run_action'
/home/ubuntu/www/production.cartodb.com/releases/20160607090509/lib/resque/importer_jobs.rb:9:in `perform'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `load'
/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `<main>'
```

It's metadata exists and it is visible in the dashboard. But the table does not exist in the user database.

I'm trying to reconstruct what happened. cc/ @gfiorav

**Comment by rafatower** [comment]
Here's my table linked:
https://rollbar.com/vizzuality/CartoDB/items/3942/occurrences/13780141846/

and here deleted:
https://rollbar.com/vizzuality/CartoDB/items/3942/occurrences/13780143593/

The sequence of events (all times in UTC):
1. Import created at `13:28:47`
2. Import started running in queue server (almost instantly) at `13:28:47`
3. Import almost done around `13:28:49`
4. GhostTablesManager linked imported table at `13:28:56`
5. GhostTablesManager acquired a new lock at `13:29:00` (me refreshing the dashboard)
6. GhostTablesManager unlinked (deleted) at `13:29:03`
7. Import failed at `13:29:03`

**Comment by gfiorav** [comment]
Thanks for reporting! I'll keep my 👀 on it

**Comment by gfiorav** [comment]
I haven't seen any major issues with this since it was reported. I'm closing this, thanks for the report!
