### ISSUE TITLE
Problem with GeocoderConfig

### ISSUE THREAD

**Issue by mgtf** [CartoDB/cartodb#8556]
Here is the error i have when trying to use Carto::Api::GeocodingsController#available_geometries 👍 

```
0:32:15 web.1    | error: 
10:32:15 web.1    | #<NameError: uninitialized constant CartoDB::GeocoderConfig>
10:32:15 web.1    | /home/ubuntu/cartodb/app/controllers/carto/api/geocodings_controller.rb:74:in `available_geometries_for_postalcode'
```

Same using the Rails console : 

```
irb(main):001:0> CartoDB::GeocoderConfig
NameError: uninitialized constant CartoDB::GeocoderConfig
    from (irb):1
    from /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands/console.rb:47:in `start'
    from /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands/console.rb:8:in `start'
    from /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
irb(main):002:0> Geocoding
(0.001980s) SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key", "pg_namespace"."nspname" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") INNER JOIN "pg_namespace" ON ("pg_namespace"."oid" = "pg_class"."relnamespace") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."relname" = 'geocodings') AND ("pg_namespace"."nspname" !~* 'pg_*|information_schema')) ORDER BY "pg_attribute"."attnum"
# But :
=> Geocoding
irb(main):003:0> CartoDB::GeocoderConfig
=> CartoDB::GeocoderConfig
# It is defined now
```

**Comment by ramiroaznar** [comment]
Closing this because of lack of activity.
