### ISSUE TITLE
import_error_percent NaN breaks file_stats in imports

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#8847]
https://github.com/CartoDB/cartodb/blob/e7e71ee6482cb33c209c7297bd71d66cbe98eda2/app/models/carto/data_import.rb#L31

```ruby
irb(main):004:0> ::JSON.parse('[{"filename":"final_shape.shp","type":".shp","size":100,"file_rows":0,"imported_rows":0,"error_percent":NaN,"fallback_executed":null}]')
JSON::ParserError: 209: unexpected token at 'NaN,"fallback_executed":null}]'
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from (irb):4
	from /usr/bin/irb:12:in `<main>'
````

**Comment by iriberri** [comment]
https://github.com/CartoDB/cartodb/blob/1625e621f327bc4be61a38ad0ab5a8b2f954f9e5/services/importer/lib/importer/job.rb
