### ISSUE TITLE
ArcGIS Connector - Data Import Incomplete

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#8958]
## Context
A user is importing a dataset from ArcGIS using the ArcGIS connector. The dataset has 11 records total but only 2 records import. The user is using a MapServer link that looks structured correctly. Is this an issue with the dataset or the ArcGIS connector?

S/B: 9421774

## Details
**REST API Link:**
https://geo.socioambiental.org/arcgis/rest/services/raisg/raisg_desmat_120m/MapServer

**Carto Table**: 
https://team.carto.com/u/chandra/tables/imagen_no_disponible_1

Tested in my team account (chandra).

**Import Log:**
```
2016-07-18 16:26:06 UTC: Running on server que03.useb.cartodb.net with PID: 28406
2016-07-18 16:26:06 UTC: new_importer()
2016-07-18 16:26:06 UTC: Fetching datasource <CartoDB::Datasources::Url::ArcGis @url= @metadata= @ids_total=0 @ids_retrieved=0 current_block_size=0> metadata for item id https://geo.socioambiental.org/arcgis/rest/services/raisg/raisg_desmat_120m/MapServer
2016-07-18 16:26:07 UTC: Downloading file data from datasource
2016-07-18 16:26:07 UTC: Before importer run
2016-07-18 16:26:07 UTC: Starting multi-resources import
2016-07-18 16:26:08 UTC: Starting import for /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json
2016-07-18 16:26:08 UTC: Filename: /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json Size (bytes): 2799
true: Importing data from /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json
true: Streaming import load
true: Detected encoding UTF-8
true: Using database connection with {:adapter=>"postgres", :encoding=>"unicode", :host=>"10.0.128.236", :database=>"cartodb_user_6b304b59-2c86-4d7b-a8a2-dc98a5a35d48_db", :username=>"cartodb_user_9c56e22e-493a-4f27-8b8e-aae6be514a1d", :port=>6432, :direct_port=>5432, :connect_timeout=>2.5}
true: Running in append mode
false: ogr2ogr call:            OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8  /usr/bin/ogr2ogr2.1 -f PostgreSQL  PG:"host=10.0.128.236 port=5432 user=cartodb_user_9c56e22e-493a-4f27-8b8e-aae6be514a1d dbname=cartodb_user_6b304b59-2c86-4d7b-a8a2-dc98a5a35d48_db password=5dda3e67309ef1594ca35272e49d7e488ce55ef0cartodb_user_9c56e22e-493a-4f27-8b8e-aae6be514a1d" -t_srs EPSG:4326  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json  -nln cdb_importer.importer_54ad43d64d0411e6a5180ef24382571b -nlt PROMOTE_TO_MULTI  -doo PRELUDE_STATEMENTS="SET statement_timeout TO '1h'" -doo CLOSING_STATEMENTS='SET statement_timeout TO DEFAULT' -update 
true: ogr2ogr output:          
true: ogr2ogr exit code:       0
true: Georeferencing...
true: Disabling autovacuum for "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
true: Creating the_geom from wkb_geometry column
true: replace empty strings by nulls?
true: no string column found, nothing replaced
true: geometrifying
true: casting wkb_geometry to geometry
true: Converting to 2D point
true: geometrified
true: Renaming column wkb_geometry TO the_geom
true: Enabling autovacuum for "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
true: Georeferenced
true: Fixing geometry...
true: Disabling autovacuum for "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
true: Fixing geometries
true: Running batched query by id in "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b": 
                UPDATE "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
                SET the_geom = public.ST_MakeValid("the_geom")
                WHERE ST_IsValid("the_geom") = FALSE
              
true: Using as id 'cartodb_processed_3680069972780403997'
true: Finished batched query by 'cartodb_processed_3680069972780403997' in "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b": query
true: Enabling autovacuum for "cdb_importer"."importer_54ad43d64d0411e6a5180ef24382571b"
true: Finished importing data from /tmp/imports/20160718-28406-1u0ij3n/imagen_no_disponible.json
2016-07-18 16:26:13 UTC: Errored importing data:
2016-07-18 16:26:13 UTC: CartoDB::Datasources::ResponseError: Missing data: 'fields'
2016-07-18 16:26:13 UTC: ----------------------------------------------------
2016-07-18 16:26:13 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/datasources/lib/datasources/url/arcgis.rb:252:in `get_subresource_metadata'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/datasources/lib/datasources/url/arcgis.rb:195:in `get_resource_metadata'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:332:in `block (3 levels) in multi_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:328:in `block (2 levels) in multi_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:323:in `block in multi_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:318:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:318:in `each_with_index'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:318:in `multi_resource_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:99:in `run_import'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:92:in `block in run'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:45:in `block in timing'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/statsd-client-0.0.7/lib/statsd.rb:26:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/cartodb/stats/aggregator.rb:43:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/services/importer/lib/importer/runner.rb:91:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/app/connectors/importer.rb:43:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/app/models/data_import.rb:714:in `execute_importer'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/app/models/data_import.rb:401:in `dispatch'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/app/models/data_import.rb:178:in `run_import!'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/resque/importer_jobs.rb:9:in `block in perform'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/resque/base_job.rb:21:in `call'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/resque/base_job.rb:21:in `run_action'", "/home/ubuntu/www/production.cartodb.com/releases/20160718111846/lib/resque/importer_jobs.rb:9:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'", "/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `load'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `<main>'"]
2016-07-18 16:26:13 UTC: ----------------------------------------------------
2016-07-18 16:26:13 UTC: Proceeding to register
2016-07-18 16:26:13 UTC: Before renaming from importer_54ad43d64d0411e6a5180ef24382571b to imagen_no_disponible
2016-07-18 16:26:14 UTC: Before moving schema 'imagen_no_disponible_1' from cdb_importer to chandra
2016-07-18 16:26:14 UTC: Before persisting metadata 'imagen_no_disponible_1' data_import_id: 09cc8373-afb4-4870-b283-2b1ca94160ba
2016-07-18 16:26:16 UTC: Table 'imagen_no_disponible_1' registered
2016-07-18 16:26:16 UTC: After importer run
2016-07-18 16:26:16 UTC: synchronization_id: 53a82514-4d04-11e6-a2ea-0e233c30368f
2016-07-18 16:26:16 UTC: importer.success? success
2016-07-18 16:26:16 UTC: After dispatch
2016-07-18 16:26:16 UTC: Import finished
===LOG END===
```

**Comment by rafatower** [comment]
@jgoizueta could you please take a look to figure out if the problem is on our end or the servers'?

**Comment by jgoizueta** [comment]
I've analyzed what's going on with this REST service; there's an anomaly I still don't know if its a deviation of MapServer from the expected behaviour.

The documention for the ArcGIS REST API is here: http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/The_ArcGIS_REST_API/02r300000054000000/

This service has two layers (https://geo.socioambiental.org/arcgis/rest/services/raisg/raisg_desmat_120m/MapServer/layers?f=json):

* Layer 0 named "Imagen no disponible" which is a "Feature Layer" (vector geometry)
* Layer 1 named "Periodo" which is a Raster Layer

The raster layers (which we don't support) causes the `Missing data: 'fields'` error and is not imported, but that's not the problem here.

The vector layer contains 11 features (https://geo.socioambiental.org/arcgis/rest/services/raisg/raisg_desmat_120m/MapServer/0/query?where=1%3D1&returnIdsOnly=true&f=json) with ids: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

To get the features we use queries with a condition on the `OBJECTID` id attribute to select batches of features.

Note: we do this by POSTing https://geo.socioambiental.org/arcgis/rest/services/raisg/raisg_desmat_120m/MapServer/0/query with parameters:

* `outFields`: (list of comma-separated field names)
* `outSR`: 4326
* `f`: json
* `where`:  OBJECTID >=0 AND OBJECTID <=10

But the `OBJECTID` don't match the object ids (0-10) as expected ad instead have higher values (the `FID` field does have the expected 0-10 values). So most of the objects are note selected by our query and only two features are actually imported.

Note: For the first feature we use the query  `ObjectId`: 0 instead of `where` and it works well.

I'll try to determine if this behaviour (`OBJECTID` not matching the feature id) is acceptable for the versions of the REST service supported or whether it is an anomaly. In the first case we have a but on our part, in the latter it'd be a problem of MapServer.

**Comment by rafatower** [comment]
If it doesn't follow the doc then it is a bug in their arcgis server, I'd tell the user to submit a bug / get a patch.

**Comment by jgoizueta** [comment]
I still have to find what the docs says about what fields (OBJECTID, FID,...) should match the "Object Id" the service returns.

This question is rather messy in general with ESRI products: http://support.esri.com/technical-article/000010834

Maybe we should have been using `FID` and not `OBJECTID` for the filtering (it would work in this case) but I have not it clear from the specification

**Comment by rafatower** [comment]
I think we're mixing up objectids and fids: http://support.esri.com/technical-article/000010834

**Comment by jgoizueta** [comment]
The question is whether the object ids that the REST service uses (see below) should match the `OBJECTID` field values. We where assuming they should. 

This is our requirement. I'm not able to find this stated in ESRI's documentation, though.

Note about the REST service object ids:

* They are returned by https://geo.socioambiental.org/arcgis/rest/services/raisg/raisg_desmat_120m/MapServer/0/query?where=1%3D1&returnIdsOnly=true&f=json
* They can be used to filter with the `ObjectIds` parameter of the [query POST](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Query_Map_Service_Layer/02r3000000p1000000/)

**Comment by jgoizueta** [comment]
Maybe we have a clue here, for this layer (0) we have these fields:

```json
[{:name=>"FID", :type=>"esriFieldTypeOID"}, {:name=>"OBJECTID", :type=>"esriFieldTypeInteger"}, ...]
```

Note that `FID` is an OID, but `OBJECTID` is merely an Integer...

**Comment by rafatower** [comment]
Okay, I'm pretty sure we have to change that and I "guestimate" 2-3 days with code changes and tests and all that. Thanks for the investigation.

**Comment by jgoizueta** [comment]
To clarify the situation: our assumption that the  `OBJECTID` field contains the *Object ids* returned by the API does not hold. At least in this case it is the `FID` field which contains the ids.

We can either change the current `where` filtering to use `FID` (or to use whatever field has type `esriFieldTypeOID`)  or we could use the `ObjectIds` parameter of query instead. Since we don't query for more than 100 objects at a time this should not be a problem.

**Comment by jgoizueta** [comment]
Here we have a layer (from ESRI's examples) which has no `FID`, and for which a field `ObjectID` exists of type `esriFieldTypeOID`: http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Census_USA/MapServer/0?where=1%3D1&returnIdsOnly=true&f=json

So we should either look for a  `esriFieldTypeOID` field or use the `ObjectIds` parameter.
