### ISSUE TITLE
Create map won't work with private shared datasets

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9458]
From #9449

STR

1. Go to Dashboard -> Datasets -> Shared
2. Click on a read-only dataset shared with you.
3. Read-only view is displayed. Click "Create map". It will fail. The error trace is this:

```ruby
log: "2016-08-17 08:57:38 UTC: Running on server que05.useb.cartodb.net with PID: 7456 2016-08-17 08:57:38 UTC: new_importer() 2016-08-17 08:57:38 UTC: Fetching datasource public_url metadata for item id http://juanignaciosl.carto.com:80/api/v2/sql?q=SELECT%20*%20FROM%20xavijam.twitter_t3chfest_reduced_2016&format=shp 2016-08-17 08:57:38 UTC: File will be downloaded from http://juanignaciosl.carto.com:80/api/v2/sql?q=SELECT%20*%20FROM%20xavijam.twitter_t3chfest_reduced_2016&format=shp 2016-08-17 08:57:39 UTC: Before importer run 2016-08-17 08:57:39 UTC: Errored importing data: 2016-08-17 08:57:39 UTC: CartoDB::Importer2::UnauthorizedDownloadError: 2016-08-17 08:57:39 UTC: ---------------------------------------------------- 2016-08-17 08:57:39 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/20160816171534/services/importer/lib/importer/downloader.rb:305:in `download_and_store'", "/home/ubuntu/www/production.cartodb.com/releases/20160816171534/services/importer/lib/importer/downloader.rb:220:in `set_downloaded_source_file'", "/home/ubuntu/www/production.cartodb.com/releases/20160816171534/services/importer/lib/importer/downloader.rb:148:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20160816171534/se
...
```

cc @jatorre @xavijam @javitonino

**Comment by xavijam** [comment]
To check after #6020 is done @javitonino.

**Comment by javitonino** [comment]
Works like a charm after #9519
